# 마스킹 전후 생성 품질 평가

이 노트북은 Hugging Face에 올린 로컬 마스킹 모델을 먼저 로드해보고, 같은 목업 채용 데이터를 두 체인으로 실행해 최종 산출물 품질을 비교합니다.

비교 대상은 다음 두 가지입니다.

- **일반 체인**: 마스킹 없이 회사/JD/이력서를 사용합니다. 체크리스트는 회사/JD와 DB 검색 결과로 생성하고, 분석 그래프 내부에서 STAR 분석을 수행한 뒤 최종 리포트와 면접 질문지를 생성합니다.
- **마스킹 체인**: 로컬 HF 모델로 회사/JD/이력서를 마스킹합니다. 마스킹된 회사/JD와 DB 검색 결과로 체크리스트를 생성하고, 분석 그래프 내부에서 STAR 분석을 수행한 뒤 최종 리포트와 면접 질문지를 생성합니다. 마지막에 `unmask()`로 결과물을 복호화합니다.

마지막에는 LLM judge가 두 결과를 원본 입력 기준으로 평가합니다. 평가 지표는 핵심 내용 보존, 중요 정보 누락, 환각, 체크리스트 반영, 리포트 품질, 질문지 품질, 복호화 품질입니다.

> 실행 순서: 반드시 첫 번째 코드 셀에서 HF 모델 로드 확인을 먼저 통과시킨 뒤 아래 셀들을 실행하세요.

In [1]:
from __future__ import annotations

import contextlib
import importlib.util
import inspect
import json
import os
import re
import sys
import types
from pathlib import Path
from typing import Any, TypedDict


def find_project_root() -> Path:
    current = Path.cwd().resolve()
    for candidate in [current, *current.parents]:
        if (candidate / "backend" / "common").exists():
            return candidate
    raise RuntimeError("프로젝트 루트를 찾지 못했습니다. 노트북을 프로젝트 내부에서 실행하세요.")


PROJECT_ROOT = find_project_root()
BACKEND_DIR = PROJECT_ROOT / "backend"
if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))

try:
    from common.utils import load_env

    load_env()
except Exception:
    try:
        from dotenv import load_dotenv

        load_dotenv(BACKEND_DIR / ".env", encoding="utf-8")
    except Exception:
        pass


BASE_MODEL_NAME = os.getenv("MASKING_BASE_MODEL", "LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct")
ADAPTER_MODEL_NAME = os.getenv("MASKING_ADAPTER_MODEL", "dlfp22/exaone-masking-lora-best")
HF_TOKEN = os.getenv("HF_TOKEN")
USE_4BIT = os.getenv("MASKING_USE_4BIT", "1").lower() not in {"0", "false", "no"}
HF_SMOKE_TEST = os.getenv("MASKING_QUALITY_HF_SMOKE_TEST", "1").lower() not in {"0", "false", "no"}
SMOKE_MAX_NEW_TOKENS = int(os.getenv("MASKING_QUALITY_SMOKE_MAX_NEW_TOKENS", "128"))
MASKING_MAX_NEW_TOKENS = int(os.getenv("MASKING_MAX_NEW_TOKENS", "512"))

LOCAL_HF_REQUIRED_PACKAGES = ["torch", "transformers", "peft", "accelerate", "sentencepiece", "safetensors"]


def missing_local_hf_packages() -> list[str]:
    return [
        package
        for package in LOCAL_HF_REQUIRED_PACKAGES
        if importlib.util.find_spec(package) is None
    ]


missing_packages = missing_local_hf_packages()
if missing_packages:
    raise ModuleNotFoundError(
        "로컬 Hugging Face 마스킹 모델 실행에 필요한 패키지가 없습니다: "
        + ", ".join(missing_packages)
        + "\n설치 예시: %pip install torch transformers peft accelerate sentencepiece safetensors"
    )

import torch
from peft import PeftModel
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig


def should_use_4bit() -> bool:
    return USE_4BIT and torch.cuda.is_available() and importlib.util.find_spec("bitsandbytes") is not None


def _patch_transformers_compat() -> None:
    try:
        import transformers.utils.generic as generic_utils

        if not hasattr(generic_utils, "maybe_autocast"):
            generic_utils.maybe_autocast = lambda *args, **kwargs: contextlib.nullcontext()
    except Exception as exc:
        print(f"[WARN] maybe_autocast patch skipped: {exc}")

    try:
        import transformers.modeling_rope_utils as rope_utils

        if not hasattr(rope_utils, "RopeParameters"):
            class RopeParameters(TypedDict, total=False):
                rope_type: str
                factor: float
                low_freq_factor: float
                high_freq_factor: float
                original_max_position_embeddings: int
                attention_factor: float
                beta_fast: float
                beta_slow: float
                short_factor: list[float]
                long_factor: list[float]

            rope_utils.RopeParameters = RopeParameters
    except Exception as exc:
        print(f"[WARN] RopeParameters patch skipped: {exc}")

    try:
        import transformers.integrations as tf_integrations

        def noop_kernel_patch(*args: Any, **kwargs: Any):
            if args and callable(args[0]) and len(args) == 1:
                return args[0]

            def decorator(fn):
                return fn

            return decorator

        for name in ("use_kernel_forward_from_hub", "use_kernel_func_from_hub", "use_kernelized_func"):
            if not hasattr(tf_integrations, name):
                setattr(tf_integrations, name, noop_kernel_patch)
    except Exception as exc:
        print(f"[WARN] kernel integration patch skipped: {exc}")


def _patch_all_create_causal_mask_refs() -> None:
    def make_compat(original_func):
        if getattr(original_func, "_exaone_input_embeds_compat", False):
            return original_func

        params = inspect.signature(original_func).parameters

        def compat(*args: Any, **kwargs: Any):
            if "input_embeds" in kwargs and "input_embeds" not in params:
                value = kwargs.pop("input_embeds")
                if "inputs_embeds" in params:
                    kwargs["inputs_embeds"] = value
                elif "input_tensor" in params:
                    kwargs["input_tensor"] = value
                else:
                    kwargs["input_ids"] = value
            elif "inputs_embeds" in kwargs and "inputs_embeds" not in params:
                value = kwargs.pop("inputs_embeds")
                if "input_embeds" in params:
                    kwargs["input_embeds"] = value
                elif "input_tensor" in params:
                    kwargs["input_tensor"] = value
                else:
                    kwargs["input_ids"] = value

            accepts_var_kwargs = any(param.kind == inspect.Parameter.VAR_KEYWORD for param in params.values())
            if not accepts_var_kwargs:
                kwargs = {key: value for key, value in kwargs.items() if key in params}
            return original_func(*args, **kwargs)

        compat._exaone_input_embeds_compat = True
        return compat

    patched_count = 0
    for module in list(sys.modules.values()):
        if module is None:
            continue

        # transformers의 lazy module은 hasattr/getattr만으로도 불필요한 하위 모듈을 import할 수 있습니다.
        # 그래서 __dict__에 이미 로드된 create_causal_mask가 있는 경우만 패치합니다.
        module_dict = getattr(module, "__dict__", {})
        if "create_causal_mask" not in module_dict:
            continue

        original_func = module_dict.get("create_causal_mask")
        if not callable(original_func):
            continue
        try:
            compat_func = make_compat(original_func)
        except (TypeError, ValueError):
            continue
        if compat_func is not original_func:
            setattr(module, "create_causal_mask", compat_func)
            patched_count += 1
    print(f"[PATCH] create_causal_mask 호환 패치 적용 모듈 수: {patched_count}")


def _patch_exaone_model(model):
    if getattr(model, "_exaone_compat_patched", False):
        return model

    if hasattr(model, "transformer") and hasattr(model.transformer, "wte"):
        embed = model.transformer.wte
    elif hasattr(model, "transformer") and hasattr(model.transformer, "embed_tokens"):
        embed = model.transformer.embed_tokens
    elif hasattr(model, "model") and hasattr(model.model, "embed_tokens"):
        embed = model.model.embed_tokens
    else:
        embed = None

    if embed is not None:
        model.get_input_embeddings = lambda: embed
        model.set_input_embeddings = lambda value: setattr(embed, "weight", value.weight)

    _patch_all_create_causal_mask_refs()

    backbone = getattr(model, "transformer", None) or getattr(model, "model", None)
    if backbone is not None and not hasattr(backbone, "_exaone_forward_patched"):
        original_forward = backbone.forward

        def patched_forward(self, *args: Any, **kwargs: Any):
            if "input_embeds" in kwargs and "inputs_embeds" not in kwargs:
                kwargs["inputs_embeds"] = kwargs.pop("input_embeds")
            return original_forward(*args, **kwargs)

        backbone.forward = types.MethodType(patched_forward, backbone)
        backbone._exaone_forward_patched = True

    model._exaone_compat_patched = True
    return model


_masking_tokenizer = None
_masking_model = None


def get_local_masking_model():
    global _masking_tokenizer, _masking_model
    if _masking_tokenizer is not None and _masking_model is not None:
        return _masking_tokenizer, _masking_model

    _patch_transformers_compat()

    tokenizer = AutoTokenizer.from_pretrained(
        ADAPTER_MODEL_NAME,
        token=HF_TOKEN,
        trust_remote_code=True,
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    tokenizer.padding_side = "right"

    model_kwargs: dict[str, Any] = {
        "token": HF_TOKEN,
        "trust_remote_code": True,
    }
    if torch.cuda.is_available():
        model_kwargs["device_map"] = "auto"
        if should_use_4bit():
            compute_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
            model_kwargs["quantization_config"] = BitsAndBytesConfig(
                load_in_4bit=True,
                bnb_4bit_quant_type="nf4",
                bnb_4bit_compute_dtype=compute_dtype,
                bnb_4bit_use_double_quant=True,
            )
        else:
            model_kwargs["torch_dtype"] = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16

    print(f"BASE_MODEL_NAME={BASE_MODEL_NAME}")
    print(f"ADAPTER_MODEL_NAME={ADAPTER_MODEL_NAME}")
    print(f"CUDA available={torch.cuda.is_available()}, use_4bit={should_use_4bit()}")

    base_model = AutoModelForCausalLM.from_pretrained(BASE_MODEL_NAME, **model_kwargs)
    base_model = _patch_exaone_model(base_model)
    model = PeftModel.from_pretrained(base_model, ADAPTER_MODEL_NAME, token=HF_TOKEN)
    model.eval()
    if hasattr(model, "config"):
        model.config.use_cache = True

    _patch_all_create_causal_mask_refs()
    _masking_tokenizer = tokenizer
    _masking_model = model
    return tokenizer, model


def parse_masking_json(text: str) -> dict[str, list[str]]:
    label_cats = [
        "comp_name",
        "person_name",
        "address",
        "personal_info",
        "school_edu",
        "project_name",
        "jd_discrimination",
    ]
    cleaned = text.strip()
    cleaned = re.sub(r"^```(?:json)?\s*", "", cleaned)
    cleaned = re.sub(r"\s*```$", "", cleaned)
    first = cleaned.find("{")
    last = cleaned.rfind("}")
    if first == -1 or last == -1 or first >= last:
        raise ValueError(f"마스킹 모델 출력에서 JSON object를 찾지 못했습니다: {cleaned[:300]}")
    obj = json.loads(cleaned[first : last + 1])
    return {
        key: [str(value) for value in obj.get(key, []) if str(value).strip()]
        if isinstance(obj.get(key, []), list)
        else []
        for key in label_cats
    }


MASKING_SYSTEM_PROMPT = """
당신은 한국어 채용 데이터의 개인정보 및 민감 표현 마스킹 전문가입니다.
입력 JSON에서 마스킹이 필요한 원문 표현을 찾아 아래 7개 카테고리로 분류해 JSON object 하나만 반환하세요.

카테고리:
- comp_name: 회사명, 기관명, 고객사명, 이전 근무처명, 조직 식별명
- person_name: 지원자 본인, 교수, 추천인, 동료 등 사람 이름
- address: 주소, 출신지, 거주지
- personal_info: 연락처, 고유식별정보, 생년월일, 나이, 성별, 병역, 장애, 가족, 종교, 정치성향 등 민감 정보
- school_edu: 학교명, 교육기관명, 부트캠프명
- project_name: 내부 프로젝트명, 고객사 식별 가능 프로젝트명
- jd_discrimination: JD의 차별 소지 표현

반드시 아래 7개 키만 포함하는 JSON object 하나만 출력하세요.
{
  "comp_name": [],
  "person_name": [],
  "address": [],
  "personal_info": [],
  "school_edu": [],
  "project_name": [],
  "jd_discrimination": []
}
""".strip()


def predict_masking(input_text: str, max_new_tokens: int = MASKING_MAX_NEW_TOKENS) -> str:
    tokenizer, model = get_local_masking_model()
    messages = [
        {"role": "system", "content": MASKING_SYSTEM_PROMPT},
        {"role": "user", "content": input_text},
    ]
    prompt = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
    inputs = tokenizer(prompt, return_tensors="pt", add_special_tokens=False)
    inputs = inputs.to(next(model.parameters()).device)

    _patch_all_create_causal_mask_refs()
    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )
    generated = outputs[0][inputs["input_ids"].shape[-1] :]
    return tokenizer.decode(generated, skip_special_tokens=True, clean_up_tokenization_spaces=False).strip()


def invoke_local_hf_masking(data: dict[str, Any]) -> dict[str, Any]:
    input_text = json.dumps(data, ensure_ascii=False, indent=2)
    raw = predict_masking(input_text)
    return {"raw": raw, "result": parse_masking_json(raw)}


tokenizer, masking_model = get_local_masking_model()
print("HF 마스킹 모델 로드 성공")

if HF_SMOKE_TEST:
    smoke_input = {"resume": {"name": "홍길동", "school": "한국대학교", "company": "샘플테크"}}
    smoke_raw = predict_masking(json.dumps(smoke_input, ensure_ascii=False), max_new_tokens=SMOKE_MAX_NEW_TOKENS)
    print("HF 마스킹 모델 smoke test raw output:")
    print(smoke_raw)
    print("HF 마스킹 모델 smoke test parsed output:")
    print(parse_masking_json(smoke_raw))

c:\Users\usre\miniconda3\envs\web_service_env\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

BASE_MODEL_NAME=LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct
ADAPTER_MODEL_NAME=dlfp22/exaone-masking-lora-best
CUDA available=False, use_4bit=False

[transformers] The `check_model_inputs` decorator is deprecated in favor of `merge_with_config_defaults`.

[ERROR] `cache_position` is part of ExaoneModel.forward's signature, but not documented. Make sure to add it to the docstring of the function in C:\Users\usre\.cache\huggingface\modules\transformers_modules\LGAI_hyphen_EXAONE\EXAONE_hyphen_3_dot_5_hyphen_2_dot_4B_hyphen_Instruct\ccce25bd39c141fe053e0bc75818a8f5fe962802\modeling_exaone.py.
[ERROR] `cache_position` is part of ExaoneForCausalLM.forward's signature, but not documented. Make sure to add it to the docstring of the function in C:\Users\usre\.cache\huggingface\modules\transformers_modules\LGAI_hyphen_EXAONE\EXAONE_hyphen_3_dot_5_hyphen_2_dot_4B_hyphen_Instruct\ccce25bd39c141fe053e0bc75818a8f5fe962802\modeling_exaone.py.

Loading weights: 100%|██████████| 272/272 [00:00<00:00, 2478.31it/s]

[PATCH] create_causal_mask 호환 패치 적용 모듈 수: 3

[transformers] The remote code model you are currently using seems to expect `cache_position`. This arg has been removed from the Transformers library, and will stop being created in `generate` even for remote code models in a future release. Please open a PR on the remote code hub repo to remove any usage of `cache_position`.

[PATCH] create_causal_mask 호환 패치 적용 모듈 수: 0
HF 마스킹 모델 로드 성공
[PATCH] create_causal_mask 호환 패치 적용 모듈 수: 0
HF 마스킹 모델 smoke test raw output:
```json
{
  "comp_name": ["샘플테크"],
  "person_name": ["홍길동"],
  "address": [],
  "personal_info": [],
  "school_edu": ["한국대학교"],
  "project_name": [],
  "jd_discrimination": []
}
```
HF 마스킹 모델 smoke test parsed output:
{'comp_name': ['샘플테크'], 'person_name': ['홍길동'], 'address': [], 'personal_info': [], 'school_edu': ['한국대학교'], 'project_name': [], 'jd_discrimination': []}

## 데이터와 프로젝트 체인 준비

기본 입력 파일은 `backend/common/eval/recruiting_mock_dataset.csv`입니다. 이 파일은 `company information`, `job_description`, `resume` 세 컬럼을 가진 JSON 문자열 CSV입니다.

`MASKING_QUALITY_SAMPLE_SIZE` 환경변수로 실행 샘플 수를 조절할 수 있습니다. 기본값은 3개입니다.

In [2]:
import csv
import time
from copy import deepcopy

try:
    import pandas as pd
except ImportError:
    pd = None

from IPython.display import Markdown, display

from common import analysis_graph, checklist_agent
from common.utils import mask, unmask


EVAL_DIR = BACKEND_DIR / "common" / "eval"
DATA_PATH = EVAL_DIR / "recruiting_mock_dataset.csv"
CHAIN_CACHE_PATH = EVAL_DIR / "masking_quality_chain_outputs.json"
JUDGE_CACHE_PATH = EVAL_DIR / "masking_quality_judge_results.json"

COMPANY_COL = "company information"
JD_COL = "job_description"
RESUME_COL = "resume"
SAMPLE_SIZE = int(os.getenv("MASKING_QUALITY_SAMPLE_SIZE", "3"))
CHECKLIST_COUNT = int(os.getenv("MASKING_QUALITY_CHECKLIST_COUNT", "10"))
FORCE_REGENERATE = os.getenv("MASKING_QUALITY_FORCE_REGENERATE", "0").lower() in {"1", "true", "yes"}
FORCE_REJUDGE = os.getenv("MASKING_QUALITY_FORCE_REJUDGE", "0").lower() in {"1", "true", "yes"}


def read_csv_rows(path: Path) -> list[dict[str, Any]]:
    with path.open(encoding="utf-8-sig", newline="") as f:
        return list(csv.DictReader(f))


def parse_json_cell(value: Any, field_name: str) -> Any:
    if isinstance(value, (dict, list)):
        return value
    text = str(value or "").strip()
    if not text:
        raise ValueError(f"{field_name} 값이 비어 있습니다.")
    return json.loads(text)


def row_to_payload(row: dict[str, Any], index: int) -> dict[str, Any]:
    return {
        "set_id": int(row.get("set_id") or index),
        "company": parse_json_cell(row[COMPANY_COL], COMPANY_COL),
        "jd": parse_json_cell(row[JD_COL], JD_COL),
        "resume": parse_json_cell(row[RESUME_COL], RESUME_COL),
    }


rows = read_csv_rows(DATA_PATH)
samples = [row_to_payload(row, index) for index, row in enumerate(rows[:SAMPLE_SIZE])]

preview_rows = [
    {
        "set_id": item["set_id"],
        "company_name": item["company"].get("company_name", ""),
        "job_name": item["jd"].get("job_name", ""),
        "resume_name": item["resume"].get("name", ""),
    }
    for item in samples
]

if pd is not None:
    display(pd.DataFrame(preview_rows))
else:
    display(preview_rows)

   set_id company_name      job_name resume_name
0       0       그린모빌리티    백엔드 개발자 채용         백수민
1       1       데이터브릿지   데이터 엔지니어 채용         정하람
2       2         코드윈드  프론트엔드 개발자 채용         오건우

## 체인 실행 함수

체크리스트 생성은 두 체인 모두 회사/JD 기반 query 생성, Pinecone DB 검색, 체크리스트 생성 순서로 수행합니다.

- 일반 체인: 원본 회사/JD로 체크리스트 생성 후 원본 입력으로 분석 그래프 실행
- 마스킹 체인: 로컬 HF 마스킹 결과를 적용한 회사/JD로 체크리스트 생성 후 마스킹 입력으로 분석 그래프 실행, 마지막에 복호화

In [3]:
def save_json(path: Path, data: Any) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def load_json(path: Path) -> Any:
    return json.loads(path.read_text(encoding="utf-8"))


def split_analysis_result(result: dict[str, Any]) -> dict[str, Any]:
    questions = result.get("question") or result.get("questions") or []
    report = {key: value for key, value in result.items() if key not in {"question", "questions"}}
    return {"report": report, "questions": questions, "full_result": result}


def generate_checklist(company: dict[str, Any], jd: dict[str, Any], mask_result: dict[str, Any] | None = None) -> dict[str, Any]:
    query = checklist_agent.invoke_extract_query_node(compinfo=deepcopy(company), jdinfo=deepcopy(jd))
    db_data = checklist_agent.invoke_search_embedding_node(query=query, cnt=CHECKLIST_COUNT)
    prompt_db_data = db_data
    if mask_result:
        prompt_db_data = mask({"db_data": deepcopy(db_data)}, mask_result)["db_data"]

    checklist = checklist_agent.invoke_fit_checklist_node(
        company_info=deepcopy(company),
        jd_info=deepcopy(jd),
        db_data=deepcopy(prompt_db_data),
        checklist_count=CHECKLIST_COUNT,
    )
    return {
        "query": query,
        "db_data": db_data,
        "prompt_db_data": prompt_db_data,
        "checklist": checklist,
    }


def run_no_mask_chain(payload: dict[str, Any]) -> dict[str, Any]:
    checklist_bundle = generate_checklist(payload["company"], payload["jd"])
    analysis_result = analysis_graph.invoke(
        company_dict=deepcopy(payload["company"]),
        jd_dict=deepcopy(payload["jd"]),
        checklist=deepcopy(checklist_bundle["checklist"]),
        resume_dict=deepcopy(payload["resume"]),
    )
    result = split_analysis_result(analysis_result)
    result["checklist_generation"] = checklist_bundle
    return result


def run_masked_chain(payload: dict[str, Any]) -> dict[str, Any]:
    source_input = {
        "company": deepcopy(payload["company"]),
        "jd": deepcopy(payload["jd"]),
        "resume": deepcopy(payload["resume"]),
    }
    masking_output = invoke_local_hf_masking(source_input)
    mask_result = masking_output["result"]
    masked_input = mask(deepcopy(source_input), mask_result)
    checklist_bundle = generate_checklist(masked_input["company"], masked_input["jd"], mask_result=mask_result)

    masked_analysis_result = analysis_graph.invoke(
        company_dict=deepcopy(masked_input["company"]),
        jd_dict=deepcopy(masked_input["jd"]),
        checklist=deepcopy(checklist_bundle["checklist"]),
        resume_dict=deepcopy(masked_input["resume"]),
    )
    unmasked_analysis_result = unmask(deepcopy(masked_analysis_result), mask_result)
    result = split_analysis_result(unmasked_analysis_result)
    result["mask_result"] = mask_result
    result["masking_raw"] = masking_output["raw"]
    result["masked_input"] = masked_input
    result["masked_raw_result"] = masked_analysis_result
    result["checklist_generation"] = checklist_bundle
    result["unmasked_checklist_generation"] = unmask(deepcopy(checklist_bundle), mask_result)
    return result

## 일반 체인과 마스킹 체인 실행

이 셀은 OpenAI, Pinecone, 로컬 HF 모델을 모두 사용하므로 시간이 걸릴 수 있습니다. 이미 실행한 결과가 있으면 캐시를 사용합니다. 다시 실행하려면 `MASKING_QUALITY_FORCE_REGENERATE=1`을 설정하세요.

In [4]:
if CHAIN_CACHE_PATH.exists() and not FORCE_REGENERATE:
    chain_records = load_json(CHAIN_CACHE_PATH)
    print(f"캐시 로드: {CHAIN_CACHE_PATH} ({len(chain_records)}건)")
else:
    chain_records = []
    for payload in samples:
        sid = payload["set_id"]
        started_at = time.time()
        print(f"[set_id={sid}] 일반 체인 실행 시작")
        no_mask_output = run_no_mask_chain(payload)
        print(f"[set_id={sid}] 마스킹 체인 실행 시작")
        masked_output = run_masked_chain(payload)
        elapsed_sec = round(time.time() - started_at, 2)

        chain_records.append(
            {
                "set_id": sid,
                "source": {
                    "company": payload["company"],
                    "jd": payload["jd"],
                    "resume": payload["resume"],
                },
                "no_mask": no_mask_output,
                "masked": masked_output,
                "elapsed_sec": elapsed_sec,
            }
        )
        save_json(CHAIN_CACHE_PATH, chain_records)
        print(f"[set_id={sid}] 완료: {elapsed_sec}초")

print(f"총 {len(chain_records)}건 준비 완료")

[set_id=0] 일반 체인 실행 시작
[set_id=0] 마스킹 체인 실행 시작
[PATCH] create_causal_mask 호환 패치 적용 모듈 수: 0
[set_id=0] 완료: 952.52초
[set_id=1] 일반 체인 실행 시작
[set_id=1] 마스킹 체인 실행 시작
[PATCH] create_causal_mask 호환 패치 적용 모듈 수: 0
[set_id=1] 완료: 643.85초
[set_id=2] 일반 체인 실행 시작
[set_id=2] 마스킹 체인 실행 시작
[PATCH] create_causal_mask 호환 패치 적용 모듈 수: 0
[set_id=2] 완료: 590.3초
총 3건 준비 완료

## 결과물 순서대로 확인

각 샘플마다 일반 체인 결과를 먼저 보고, 그 다음 마스킹 체인에서 생성 후 복호화한 결과를 봅니다. 결과물은 최종 리포트와 면접 질문지입니다.

In [5]:
def find_mask_tokens(obj: Any) -> list[str]:
    text = json.dumps(obj, ensure_ascii=False)
    return sorted(set(re.findall(r"\[[A-Z_]+_\d+\]", text)))


def show_questions(questions: list[dict[str, Any]]) -> None:
    if pd is not None:
        display(pd.DataFrame(questions))
    else:
        display(questions)


def display_chain_output(record: dict[str, Any]) -> None:
    sid = record["set_id"]
    display(Markdown(f"## set_id={sid}"))

    display(Markdown("### 1. 일반 체인 결과: 마스킹 없음, STAR 분석 있음"))
    display(Markdown("#### 생성 체크리스트"))
    display(record["no_mask"]["checklist_generation"]["checklist"])
    display(Markdown("#### 최종 리포트"))
    display(record["no_mask"]["report"])
    display(Markdown("#### 면접 질문지"))
    show_questions(record["no_mask"]["questions"])

    display(Markdown("### 2. 마스킹 체인 결과: 마스킹 적용, STAR 분석 있음, 최종 복호화"))
    display(Markdown("#### 마스킹 결과"))
    display(record["masked"]["mask_result"])
    display(Markdown("#### 생성 체크리스트: 복호화 후 표시"))
    display(record["masked"]["unmasked_checklist_generation"]["checklist"])
    display(Markdown(f"잔여 마스킹 토큰: `{find_mask_tokens(record['masked']['full_result'])}`"))
    display(Markdown("#### 최종 리포트"))
    display(record["masked"]["report"])
    display(Markdown("#### 면접 질문지"))
    show_questions(record["masked"]["questions"])


for record in chain_records:
    display_chain_output(record)

## set_id=0

### 1. 일반 체인 결과: 마스킹 없음, STAR 분석 있음

#### 생성 체크리스트

['지원자는 Python과 Django를 활용한 백엔드 API 설계 및 개발 경험이 있어야 한다.',
 '클라우드 인프라 모니터링 솔루션에 대한 이해도가 높아야 한다.',
 '협업이 가능한 인재로서 팀 내에서 원활한 커뮤니케이션을 할 수 있어야 한다.',
 'AWS, PostgreSQL, Docker와 같은 선호 기술에 대한 경험이 있으면 좋다.',
 '신입으로서 백엔드 개발에 대한 열정과 학습 의지가 있어야 한다.',
 '디자인팀 및 기획/PM팀과의 협업 경험이 있으면 우대한다.',
 '빠르게 성장하는 스타트업 환경에 적응할 수 있는 유연성을 가져야 한다.',
 '백엔드 개발 관련 프로젝트 경험이 있으면 좋다.',
 '문제 해결 능력이 뛰어나고, 새로운 기술을 배우는 데 적극적이어야 한다.',
 '그린모빌리티의 비전과 목표에 공감하고 함께 성장할 수 있는 인재여야 한다.']

#### 최종 리포트

{'overall_grade': 'C',
 'overall_summary': '지원자는 총 10개의 체크리스트 항목 중 4개를 충족하여 C 등급으로 평가되었습니다.',
 'candidate_summary': '백수민은 경영학 석사 학위를 보유하고 있으며, 8년 이상의 경력을 가진 지원자로, 대시보드 개발 및 결제 모듈 개발 경험이 있습니다. AWS와 Python, TypeScript에 대한 기술적 역량을 보유하고 있으나, Django를 활용한 백엔드 API 설계 및 개발 경험이 부족합니다.',
 'checklist': [{'content': '지원자는 Python과 Django를 활용한 백엔드 API 설계 및 개발 경험이 있어야 한다.',
   'result': False},
  {'content': '클라우드 인프라 모니터링 솔루션에 대한 이해도가 높아야 한다.', 'result': False},
  {'content': '협업이 가능한 인재로서 팀 내에서 원활한 커뮤니케이션을 할 수 있어야 한다.', 'result': True},
  {'content': 'AWS, PostgreSQL, Docker와 같은 선호 기술에 대한 경험이 있으면 좋다.',
   'result': True},
  {'content': '신입으로서 백엔드 개발에 대한 열정과 학습 의지가 있어야 한다.', 'result': False},
  {'content': '디자인팀 및 기획/PM팀과의 협업 경험이 있으면 우대한다.', 'result': False},
  {'content': '빠르게 성장하는 스타트업 환경에 적응할 수 있는 유연성을 가져야 한다.', 'result': False},
  {'content': '백엔드 개발 관련 프로젝트 경험이 있으면 좋다.', 'result': True},
  {'content': '문제 해결 능력이 뛰어나고, 새로운 기술을 배우는 데 적극적이어야 한다.', 'result': True},
  {'content': '그린모빌리티의 비전과 목표에 공감하고 함께 성장할 수 있는 인재여야 한다.', 'result': False}],
 'competency_analysis': ['지원자는 AWS, Python, TypeScript에 대한 경험이 있으며, 백엔드 개발 관련 프로젝트 경험이 있지만, Django를 활용한 API 설계 경험이 부족합니다.',
  '클라우드 인프라 모니터링 솔루션에 대한 이해도가 낮아 보이며, 스타트업 환경에 적응할 유연성이 부족할 수 있습니다.'],
 'fit_analysis': '지원자는 경영학 석사 학위를 보유하고 있으며, 8년 이상의 경력을 통해 대시보드 및 결제 모듈 개발 경험을 쌓았습니다. 그러나 Python과 Django를 활용한 백엔드 API 설계 및 개발 경험이 부족하여 해당 직무에 대한 적합성이 다소 떨어집니다.',
 'motive': '지원자는 진보적인 가치관을 지향하며 성장해온 과정을 통해 책임감 있는 자세를 강조하고 있습니다. 이는 직무에 대한 열정과 학습 의지를 나타내지만, 신입으로서의 열정이 부족하다는 점은 아쉬운 부분입니다.',
 'collaboration': '지원자는 팀 내에서 원활한 커뮤니케이션을 할 수 있는 능력을 보유하고 있으며, 갈등 상황에서 경청하고 데이터로 설득하는 방식을 통해 팀원들과의 의견 조율을 성공적으로 이끌어낸 경험이 있습니다.',
 'strength': ['AWS, Python, TypeScript에 대한 기술적 역량',
  '대시보드 및 결제 모듈 개발 경험',
  '책임감 있는 자세와 협업 능력'],
 'concern': ['백엔드 API 설계 및 개발 경험 부족',
  '클라우드 인프라 모니터링 솔루션에 대한 이해 부족',
  '스타트업 환경에 적응할 유연성 부족'],
 'check_point': ['Python과 Django를 활용한 백엔드 API 설계 경험 추가 검증 필요',
  '클라우드 인프라 모니터링 솔루션에 대한 이해도 확인 필요',
  '스타트업 환경에서의 적응력 평가 필요'],
 'final_comment': '지원자는 경력과 기술적 역량이 있으나, 직무에 대한 적합성이 다소 부족하여 추가 검증이 필요합니다.'}

#### 면접 질문지

,question,answer,purpose
0,Python과 Django를 활용한 백엔드 API 설계 및 개발 경험이 없다고 하셨...,"저는 Python과 Django에 대한 경험이 부족하지만, AWS와 Python을 ...",지원자의 학습 의지와 기술 습득 계획을 평가하기 위함이다.
1,"클라우드 인프라 모니터링 솔루션에 대한 이해도가 부족하다고 하셨는데, 이 분야에 대...","클라우드 인프라 모니터링 솔루션에 대한 이해가 부족하지만, AWS와 관련된 경험이 ...",지원자의 자기주도적인 학습 능력과 기술에 대한 관심을 평가하기 위함이다.
2,"협업이 가능한 인재로서 팀 내에서 원활한 커뮤니케이션을 할 수 있다고 하셨는데, 구...","이전 직장에서 팀원들과의 의견 충돌이 있었을 때, 먼저 경청하고 데이터로 설득하는 ...",지원자의 커뮤니케이션 능력과 협업 경험을 구체적으로 평가하기 위함이다.
3,"AWS, PostgreSQL, Docker와 같은 선호 기술에 대한 경험이 있다고 ...",저는 AWS를 활용하여 대시보드를 개발한 경험이 있습니다. 이 과정에서 데이터베이스...,지원자의 기술적 경험과 실무 적용 능력을 평가하기 위함이다.
4,"백엔드 개발 관련 프로젝트 경험이 있다고 하셨는데, 그 프로젝트에서 맡은 역할과 기...",대시보드 개발 프로젝트에서 과장으로 팀을 이끌며 API 설계와 데이터 시각화 작업을...,지원자의 프로젝트 경험과 역할 수행 능력을 평가하기 위함이다.
5,"문제 해결 능력이 뛰어나고, 새로운 기술을 배우는 데 적극적이라고 하셨는데, 구체적...",결제 모듈 개발 중 발생한 기술적 문제를 해결하기 위해 관련 문서를 찾아보고 커뮤니...,지원자의 문제 해결 능력과 학습 태도를 평가하기 위함이다.
6,"빠르게 성장하는 스타트업 환경에 적응할 수 있는 유연성을 가져야 한다고 하셨는데, ...","이전 직장에서 프로젝트 일정이 급변했을 때, 팀원들과의 긴밀한 소통을 통해 우선순위...",지원자의 유연성과 적응 능력을 평가하기 위함이다.
7,"디자인팀 및 기획/PM팀과의 협업 경험이 부족하다고 하셨는데, 이러한 팀과의 협업을...","디자인팀 및 기획/PM팀과의 협업 경험이 부족하지만, 원활한 소통을 위해 사전에 프...",지원자의 협업 의지와 개선 방안을 평가하기 위함이다.
8,그린모빌리티의 비전과 목표에 공감하고 함께 성장할 수 있는 인재여야 한다고 하셨는데...,그린모빌리티의 비전은 클라우드 인프라 모니터링 솔루션을 통해 고객의 비즈니스 가치를...,지원자가 회사의 비전과 목표에 대한 이해도를 평가하기 위함이다.
9,"불명확한 요구사항이나 우선순위 충돌이 발생했을 때, 어떻게 대응할 것인지에 대한 생...",불명확한 요구사항이 발생했을 때는 먼저 관련자와의 소통을 통해 요구사항을 명확히 하...,지원자의 문제 해결 능력과 의사소통 능력을 평가하기 위함이다.

### 2. 마스킹 체인 결과: 마스킹 적용, STAR 분석 있음, 최종 복호화

#### 마스킹 결과

{'comp_name': ['그린모빌리티', '스마트셀', '블루오션랩', 'CJ대한통운'],
 'person_name': ['백수민', '서시우'],
 'address': ['대구'],
 'personal_info': ['진보', '노동조합 활동'],
 'school_edu': ['서울대학교 통계학과', '항해99'],
 'project_name': ['페이먼트 게이트웨이 구축'],
 'jd_discrimination': []}

#### 생성 체크리스트: 복호화 후 표시

['지원자는 Python과 Django를 활용한 백엔드 API 설계 및 개발 경험이 있어야 한다.',
 '클라우드 인프라 모니터링 솔루션에 대한 이해도가 높아야 한다.',
 '협업이 가능한 인재로서 팀 내에서 원활한 커뮤니케이션을 할 수 있어야 한다.',
 'AWS 또는 유사한 클라우드 플랫폼에서의 경험이 있으면 우대된다.',
 'PostgreSQL 데이터베이스에 대한 이해와 경험이 필요하다.',
 'Docker를 활용한 컨테이너화 경험이 있으면 좋다.',
 '신입으로서 백엔드 개발에 대한 열정과 학습 의지가 있어야 한다.',
 'REST API 설계 및 운영 경험이 있으면 우대된다.',
 '빠르게 성장하는 스타트업 환경에 적응할 수 있는 유연성을 가져야 한다.',
 '디자인팀 및 기획/PM팀과의 협업 경험이 있으면 좋다.']

잔여 마스킹 토큰: `[]`

#### 최종 리포트

{'overall_grade': 'D',
 'overall_summary': '지원자는 총 10개의 체크리스트 항목 중 3개 항목을 충족하지 못하여 D 등급으로 평가되었습니다.',
 'candidate_summary': '지원자는 경영학 석사 학위를 보유하고 있으며, 8년 이상의 경력을 가지고 있습니다. AWS, Python, TypeScript 등의 기술을 보유하고 있으나, 백엔드 API 설계 및 개발 경험이 부족하여 해당 직무에 적합성은 낮습니다.',
 'checklist': [{'content': '지원자는 Python과 Django를 활용한 백엔드 API 설계 및 개발 경험이 있어야 한다.',
   'result': False},
  {'content': '클라우드 인프라 모니터링 솔루션에 대한 이해도가 높아야 한다.', 'result': False},
  {'content': '협업이 가능한 인재로서 팀 내에서 원활한 커뮤니케이션을 할 수 있어야 한다.', 'result': True},
  {'content': 'AWS 또는 유사한 클라우드 플랫폼에서의 경험이 있으면 우대된다.', 'result': True},
  {'content': 'PostgreSQL 데이터베이스에 대한 이해와 경험이 필요하다.', 'result': False},
  {'content': 'Docker를 활용한 컨테이너화 경험이 있으면 좋다.', 'result': False},
  {'content': '신입으로서 백엔드 개발에 대한 열정과 학습 의지가 있어야 한다.', 'result': False},
  {'content': 'REST API 설계 및 운영 경험이 있으면 우대된다.', 'result': False},
  {'content': '빠르게 성장하는 스타트업 환경에 적응할 수 있는 유연성을 가져야 한다.', 'result': False},
  {'content': '디자인팀 및 기획/PM팀과의 협업 경험이 있으면 좋다.', 'result': False}],
 'competency_analysis': ['지원자는 AWS와 Python에 대한 경험이 있으나, Django 및 REST API 설계 경험이 부족하여 백엔드 개발 직무에 대한 적합성이 낮습니다.',
  '클라우드 플랫폼에 대한 경험이 있으나, PostgreSQL 및 Docker와 같은 필수 기술에 대한 경험이 결여되어 있습니다.'],
 'fit_analysis': '지원자는 대시보드 개발 및 결제 모듈 개발 경험을 통해 기술적 역량을 쌓아왔으나, 지원 직무에 필요한 백엔드 API 설계 및 개발 경험이 부족하여 적합성이 낮습니다.',
 'motive': '지원자는 성장 과정에서 책임감 있는 자세를 강조하며, 맡은 일에 대한 책임을 다하고자 하는 의지를 보였습니다. 그러나 지원 동기가 직무와의 연관성이 부족하여 다소 약하게 느껴집니다.',
 'collaboration': '지원자는 팀원들과의 갈등 상황에서 경청과 데이터 기반 설득을 통해 협력을 이끌어낸 경험이 있습니다. 이는 협업 능력을 잘 보여주지만, 구체적인 협업 경험이 부족하여 추가적인 검증이 필요합니다.',
 'strength': ['AWS 경험', 'Python 및 TypeScript 기술 보유', '책임감 있는 자세'],
 'concern': ['백엔드 API 설계 및 개발 경험 부족',
  'PostgreSQL 및 Docker 경험 결여',
  '직무와의 연관성이 부족한 지원 동기'],
 'check_point': ['백엔드 API 설계 및 개발 경험에 대한 추가 검증 필요',
  'PostgreSQL 및 Docker 관련 경험 확인 필요'],
 'final_comment': '지원자는 기술적 역량이 일부 있으나, 직무에 필요한 경험이 부족하여 채용에 적합하지 않다고 판단됩니다.'}

#### 면접 질문지

,question,answer,purpose
0,Python과 Django를 활용한 백엔드 API 설계 및 개발 경험이 없다고 하셨...,"저는 Python과 Django에 대한 기초 지식을 가지고 있으며, 온라인 강의와 ...",지원자의 학습 의지와 기술 습득 계획을 평가하기 위함입니다.
1,클라우드 인프라 모니터링 솔루션에 대한 이해도가 부족하다고 하셨습니다. 이 분야에 ...,클라우드 인프라 모니터링 솔루션에 대한 이해를 높이기 위해 관련 서적과 온라인 자료...,지원자가 부족한 지식을 보완하기 위한 노력을 평가하기 위함입니다.
2,협업이 가능한 인재로서 팀 내에서 원활한 커뮤니케이션을 할 수 있다고 하셨습니다. ...,"이전 직장에서 팀 프로젝트를 진행하며, 팀원들과의 의견 조율과 갈등 해결을 위해 경...",지원자의 협업 능력과 커뮤니케이션 스킬을 검증하기 위함입니다.
3,AWS 또는 유사한 클라우드 플랫폼에서의 경험이 있다고 하셨습니다. 구체적으로 어떤...,저는 스마트셀에서 클라우드 기반 대시보드 개발 프로젝트에 참여했습니다. 이 과정에서...,지원자의 클라우드 플랫폼 경험을 구체적으로 검증하기 위함입니다.
4,PostgreSQL 데이터베이스에 대한 이해와 경험이 부족하다고 하셨습니다. 이 기...,"PostgreSQL에 대한 기초 지식을 쌓기 위해 온라인 강의를 수강하고, 개인 프...",지원자가 부족한 기술을 보완하기 위한 의지를 평가하기 위함입니다.
5,Docker를 활용한 컨테이너화 경험이 없다고 하셨습니다. 이 기술을 배우기 위해 ...,"Docker에 대한 기본 개념을 이해하고, 온라인 튜토리얼을 통해 실습을 진행할 계...",지원자의 기술 습득 의지와 계획을 평가하기 위함입니다.
6,신입으로서 백엔드 개발에 대한 열정과 학습 의지가 부족하다고 하셨습니다. 이 점을 ...,"백엔드 개발에 대한 열정을 키우기 위해 관련 커뮤니티에 참여하고, 멘토를 찾아 조언...",지원자의 열정과 학습 의지를 평가하기 위함입니다.
7,최근 클라우드 인프라 모니터링 솔루션 산업에서 어떤 이슈가 있다고 생각하시나요?,최근 클라우드 인프라 모니터링 솔루션 산업에서는 데이터 보안과 개인정보 보호가 큰 ...,지원자가 산업의 최근 이슈를 이해하고 있는지를 평가하기 위함입니다.
8,사수나 선임이 적고 스스로 판단해야 하는 환경에서 어떻게 적응할 수 있을까요?,사수나 선임이 적은 환경에서는 스스로 문제를 정의하고 해결책을 찾아야 합니다. 이를...,지원자의 자율성과 문제 해결 능력을 평가하기 위함입니다.
9,"불명확한 요구사항이나 우선순위 충돌이 발생했을 때, 어떻게 대응하시겠습니까?","불명확한 요구사항이 있을 경우, 먼저 관련자와의 소통을 통해 명확한 요구사항을 파악...",지원자의 문제 해결 능력과 유연성을 평가하기 위함입니다.

## set_id=1

### 1. 일반 체인 결과: 마스킹 없음, STAR 분석 있음

#### 생성 체크리스트

['지원자는 컴퓨터공학 전공의 학사 학위를 보유하고 있어야 한다.',
 '지원자는 Python과 Spark에 대한 실무 경험이 있어야 한다.',
 'ETL 파이프라인 구축 및 운영 경험이 있어야 한다.',
 '데이터팀에서의 협업 경험이 있으며, 팀원들과 효과적으로 소통할 수 있어야 한다.',
 '자기주도적으로 문제를 해결하는 능력을 갖추고 있어야 한다.',
 '대용량 스트리밍 처리 기술에 대한 이해도가 있어야 한다.',
 'Airflow, Kafka, AWS와 같은 선호 기술에 대한 경험이 있으면 우대된다.',
 '문제를 끝까지 파고드는 태도를 가지고 있어야 한다.',
 '정규직으로 근무할 수 있는 의지가 있어야 한다.',
 '데이터브릿지의 비전과 목표에 공감하고 함께 성장할 수 있는 열정을 가져야 한다.']

#### 최종 리포트

{'overall_grade': 'B',
 'overall_summary': '지원자는 총 10개의 기준 중 7개를 충족하여 B 등급으로 평가되었습니다. 전반적으로 기술적 역량이 뛰어나며, 관련 경험이 풍부하지만, 협업 경험과 회사 비전에 대한 공감이 부족한 점이 아쉽습니다.',
 'candidate_summary': '정하람은 컴퓨터공학과 학사 학위를 보유하고 있으며, Python, Spark, Airflow, SQL 등 다양한 기술에 대한 실무 경험이 있습니다. 2년 8개월 동안 ETL 파이프라인 운영 및 데이터 품질 개선 업무를 수행하며, 대용량 데이터 처리에 대한 경험을 쌓았습니다.',
 'checklist': [{'content': '지원자는 컴퓨터공학 전공의 학사 학위를 보유하고 있어야 한다.',
   'result': True},
  {'content': '지원자는 Python과 Spark에 대한 실무 경험이 있어야 한다.', 'result': True},
  {'content': 'ETL 파이프라인 구축 및 운영 경험이 있어야 한다.', 'result': True},
  {'content': '데이터팀에서의 협업 경험이 있으며, 팀원들과 효과적으로 소통할 수 있어야 한다.', 'result': False},
  {'content': '자기주도적으로 문제를 해결하는 능력을 갖추고 있어야 한다.', 'result': True},
  {'content': '대용량 스트리밍 처리 기술에 대한 이해도가 있어야 한다.', 'result': False},
  {'content': 'Airflow, Kafka, AWS와 같은 선호 기술에 대한 경험이 있으면 우대된다.',
   'result': True},
  {'content': '문제를 끝까지 파고드는 태도를 가지고 있어야 한다.', 'result': True},
  {'content': '정규직으로 근무할 수 있는 의지가 있어야 한다.', 'result': False},
  {'content': '데이터브릿지의 비전과 목표에 공감하고 함께 성장할 수 있는 열정을 가져야 한다.',
   'result': False}],
 'competency_analysis': ['지원자는 Python, Spark, Airflow, SQL 등 데이터 처리에 필요한 기술을 보유하고 있으며, ETL 파이프라인 운영 경험이 있어 실무에 적합한 역량을 갖추고 있습니다.',
  '대용량 데이터 처리에 대한 경험이 있으며, 문제 해결 능력도 뛰어나지만, 협업 경험이 부족하여 팀워크 측면에서 추가 검증이 필요합니다.'],
 'fit_analysis': '지원자는 대용량 데이터를 안정적으로 처리하는 일에 매력을 느끼고 있으며, 이전 직장에서의 경험을 통해 시스템의 안정성을 높이고 처리 속도를 개선한 사례를 가지고 있습니다. 이러한 경험은 지원 직무에 적합한 역량으로 평가됩니다.',
 'motive': '지원자는 대용량 데이터 처리에 대한 열정을 가지고 있으며, 이전 경험을 통해 문제를 해결한 사례를 제시하여 지원 동기를 명확히 하고 있습니다. 이는 직무에 대한 관심과 의지를 잘 보여줍니다.',
 'collaboration': '지원서에는 팀원들과의 협업 경험이 부족하다는 점이 드러나 있으며, 이는 향후 팀워크와 소통 능력에 대한 추가 검증이 필요함을 시사합니다.',
 'strength': ['대용량 데이터 처리 경험', '문제 해결 능력', '자기주도적인 태도'],
 'concern': ['협업 경험 부족', '대용량 스트리밍 처리 기술 이해 부족', '회사 비전과 목표에 대한 공감 부족'],
 'check_point': ['협업 경험에 대한 구체적인 사례 확인 필요',
  '대용량 스트리밍 처리 기술에 대한 이해도 검증 필요',
  '정규직 근무 의지 확인 필요'],
 'final_comment': '지원자는 기술적 역량이 뛰어나지만, 협업 경험과 회사 비전에 대한 공감이 부족한 점이 아쉽습니다. 추가 검증을 통해 이러한 부분을 보완할 필요가 있습니다.'}

#### 면접 질문지

,question,answer,purpose
0,이전 직장에서 운영한 ETL 파이프라인에 대해 구체적으로 설명해 주실 수 있나요? ...,이전 직장에서 하루 3억 건의 로그를 처리하는 ETL 파이프라인을 운영했습니다. P...,지원자의 ETL 파이프라인 운영 경험과 기술적 역량을 검증하기 위함이다.
1,장애 상황에서 원인을 추적하고 문서화한 경험에 대해 더 자세히 설명해 주실 수 있나...,"장애 발생 시, 먼저 로그를 분석하여 원인을 파악했습니다. 이후, 재발 방지책을 마...",지원자의 문제 해결 능력과 팀 내 소통 능력을 평가하기 위함이다.
2,Python과 Spark을 사용한 프로젝트 경험에 대해 구체적으로 말씀해 주실 수 ...,Python과 Spark을 사용하여 대량의 데이터를 처리하는 프로젝트에 참여했습니다...,지원자의 기술적 경험과 프로젝트에서의 역할을 검증하기 위함이다.
3,"자기주도적으로 문제를 해결한 경험에 대해 말씀해 주세요. 어떤 상황이었고, 어떤 결...","이전 직장에서 데이터 품질 문제를 발견했을 때, 팀의 도움 없이 스스로 문제를 분석...",지원자의 자기주도적 문제 해결 능력을 평가하기 위함이다.
4,"Airflow를 사용한 경험이 있다면, 어떤 프로젝트에서 어떻게 활용했는지 설명해 ...",Airflow를 사용하여 데이터 파이프라인의 스케줄링과 모니터링을 담당했습니다. 이...,지원자의 Airflow 활용 경험과 기술적 이해도를 검증하기 위함이다.
5,"대용량 스트리밍 처리 기술에 대한 이해도가 부족하다고 평가되었는데, 이를 보완하기 ...",대용량 스트리밍 처리 기술에 대한 이해도를 높이기 위해 관련 온라인 강의를 수강하고...,지원자의 부족한 역량을 보완할 의지와 계획을 평가하기 위함이다.
6,"데이터팀에서의 협업 경험이 부족하다고 평가되었는데, 이를 어떻게 보완할 수 있을까요?","데이터팀에서의 협업 경험이 부족하지만, 팀 프로젝트에 참여하여 소통 능력을 키우고,...",지원자의 협업 능력 향상 의지와 계획을 평가하기 위함이다.
7,최근 데이터 산업에서 가장 주목할 만한 이슈는 무엇이라고 생각하시나요? 그 이유는 ...,최근 데이터 산업에서 주목할 만한 이슈는 데이터 프라이버시와 보안 문제입니다. 데이...,지원자가 산업 이슈에 대한 이해도를 평가하기 위함이다.
8,사수나 선임이 적고 스스로 판단해야 하는 환경에서 어떻게 적응할 수 있을까요?,사수나 선임이 적은 환경에서는 스스로 문제를 정의하고 해결책을 찾아야 합니다. 이를...,지원자의 자율성과 문제 해결 능력을 평가하기 위함이다.
9,불명확한 요구사항이나 우선순위 충돌 상황에서 어떻게 대응할 것인가요?,"불명확한 요구사항이 있을 경우, 먼저 관련자와의 소통을 통해 명확한 요구사항을 파악...",지원자의 불확실한 상황에서의 대응 능력을 평가하기 위함이다.

### 2. 마스킹 체인 결과: 마스킹 적용, STAR 분석 있음, 최종 복호화

#### 마스킹 결과

{'comp_name': ['데이터브릿지', '넥스트로그'],
 'person_name': ['정하람', '김도현'],
 'address': [],
 'personal_info': [],
 'school_edu': ['한국데이터산업진흥원'],
 'project_name': [],
 'jd_discrimination': []}

#### 생성 체크리스트: 복호화 후 표시

['지원자는 컴퓨터공학 전공의 학사 학위를 보유하고 있어야 한다.',
 '지원자는 데이터 엔지니어링 분야에서 경력직으로 최소 2년 이상의 경험이 있어야 한다.',
 '지원자는 Python을 활용한 데이터 처리 및 분석 경험이 있어야 한다.',
 '지원자는 Spark를 사용한 데이터 파이프라인 구축 경험이 있어야 한다.',
 '지원자는 ETL 파이프라인 구축 및 운영에 대한 실무 경험이 있어야 한다.',
 '지원자는 Airflow, Kafka, AWS와 같은 도구에 대한 이해와 경험이 있으면 우대된다.',
 '지원자는 문제를 끝까지 파고드는 태도를 가지고 있어야 한다.',
 '지원자는 자기주도적으로 업무를 수행할 수 있는 능력이 있어야 한다.',
 '지원자는 데이터팀 내 다양한 협업 부서와의 커뮤니케이션 경험이 있어야 한다.',
 '지원자는 대용량 스트리밍 처리 기술에 대한 이해가 있어야 한다.']

잔여 마스킹 토큰: `[]`

#### 최종 리포트

{'overall_grade': 'A',
 'overall_summary': '지원자는 데이터 엔지니어링 분야에서 요구되는 모든 기준을 충족하며, 특히 대용량 데이터 처리와 관련된 경험이 풍부합니다.',
 'candidate_summary': '지원자는 컴퓨터공학 전공의 학사 학위를 보유하고 있으며, 2년 8개월의 데이터 엔지니어링 경력을 가지고 있습니다. Python, Spark, Airflow 등 다양한 기술을 활용한 경험이 있으며, 데이터 품질 개선을 위한 실무 경험도 갖추고 있습니다.',
 'checklist': [{'content': '지원자는 컴퓨터공학 전공의 학사 학위를 보유하고 있어야 한다.',
   'result': True},
  {'content': '지원자는 데이터 엔지니어링 분야에서 경력직으로 최소 2년 이상의 경험이 있어야 한다.',
   'result': True},
  {'content': '지원자는 Python을 활용한 데이터 처리 및 분석 경험이 있어야 한다.', 'result': True},
  {'content': '지원자는 Spark를 사용한 데이터 파이프라인 구축 경험이 있어야 한다.', 'result': True},
  {'content': '지원자는 ETL 파이프라인 구축 및 운영에 대한 실무 경험이 있어야 한다.', 'result': True},
  {'content': '지원자는 Airflow, Kafka, AWS과 같은 도구에 대한 이해와 경험이 있으면 우대된다.',
   'result': True},
  {'content': '지원자는 문제를 끝까지 파고드는 태도를 가지고 있어야 한다.', 'result': True},
  {'content': '지원자는 자기주도적으로 업무를 수행할 수 있는 능력이 있어야 한다.', 'result': True},
  {'content': '지원자는 데이터팀 내 다양한 협업 부서와의 커뮤니케이션 경험이 있어야 한다.', 'result': True},
  {'content': '지원자는 대용량 스트리밍 처리 기술에 대한 이해가 있어야 한다.', 'result': True}],
 'competency_analysis': ['지원자는 데이터 엔지니어링에 필요한 기술적 역량을 갖추고 있으며, 특히 대용량 데이터 처리에 대한 경험이 풍부합니다.',
  'ETL 파이프라인 운영 및 데이터 품질 개선에 대한 실무 경험이 있어, 실질적인 문제 해결 능력이 뛰어납니다.'],
 'fit_analysis': '지원자는 대용량 데이터를 안정적으로 처리하는 데 매력을 느끼며, 이전 직장에서의 경험을 통해 시스템의 안정성을 높이고 처리 속도를 개선한 사례가 있습니다. 이러한 경험은 지원 직무에 매우 적합합니다.',
 'motive': '지원자는 대용량 데이터를 안정적으로 처리하는 일에 매력을 느껴 지원하였으며, 이전 직장에서의 경험을 통해 최적화 작업을 수행하여 시스템의 안정성을 높인 점이 인상적입니다.',
 'collaboration': '지원자는 문제 발생 시 원인을 파악하고 재발 방지책을 마련하는 과정에서 팀원들과의 협업을 통해 유사한 문제가 발생할 확률을 줄이는 데 기여하였습니다. 이는 협업 능력이 뛰어난 것을 보여줍니다.',
 'strength': ['대용량 데이터 처리 경험', '문제 해결 능력', '자기주도적 업무 수행 능력'],
 'concern': [],
 'check_point': [],
 'final_comment': '지원자는 데이터 엔지니어링 분야에서 매우 적합한 인재로, 모든 기준을 충족하며 뛰어난 역량을 보유하고 있습니다.'}

#### 면접 질문지

,question,answer,purpose
0,이전 직장에서 하루 3억 건의 로그를 처리하는 ETL 파이프라인을 운영했다고 하셨습...,하루 3억 건의 로그를 처리하는 과정에서 데이터 지연 문제가 발생했습니다. 이를 해...,지원자의 문제 해결 능력과 경험을 구체적으로 평가하기 위함이다.
1,ETL 파이프라인 운영 중 데이터 품질 개선을 위해 어떤 조치를 취하셨는지 구체적으...,데이터 품질 개선을 위해 데이터 검증 프로세스를 도입했습니다. 이를 통해 데이터의 ...,지원자의 데이터 품질 관리 경험과 능력을 평가하기 위함이다.
2,Python을 활용한 데이터 처리 및 분석 경험에 대해 구체적인 사례를 들어 설명해...,Python을 사용하여 대량의 로그 데이터를 처리했습니다. Pandas 라이브러리를...,지원자의 Python 활용 능력과 데이터 처리 경험을 평가하기 위함이다.
3,Spark를 사용한 데이터 파이프라인 구축 경험에 대해 구체적으로 말씀해 주실 수 ...,Spark를 사용하여 대규모 데이터 처리 파이프라인을 구축했습니다. 데이터 소스에서...,지원자의 Spark 활용 능력과 경험을 평가하기 위함이다.
4,"Airflow를 사용한 경험이 있다고 하셨는데, 이를 통해 어떤 작업을 자동화하셨는...",Airflow를 사용하여 ETL 작업을 스케줄링하고 모니터링했습니다. DAG를 구성...,지원자의 Airflow 활용 능력과 자동화 경험을 평가하기 위함이다.
5,자기주도적으로 업무를 수행한 경험에 대해 구체적으로 말씀해 주실 수 있나요?,이전 직장에서 팀원들이 바쁜 상황에서 혼자서 ETL 파이프라인의 성능 개선 작업을 ...,지원자의 자기주도적 업무 수행 능력을 평가하기 위함이다.
6,문제를 끝까지 파고드는 태도를 보여준 경험에 대해 말씀해 주실 수 있나요?,데이터 처리 중 발생한 오류를 해결하기 위해 원인을 철저히 분석했습니다. 여러 로그...,지원자의 문제 해결 태도와 협업 능력을 평가하기 위함이다.
7,최근 데이터 엔지니어링 분야에서 주목받고 있는 이슈나 트렌드에 대해 어떻게 생각하시나요?,최근 데이터 엔지니어링 분야에서는 실시간 데이터 처리와 데이터 파이프라인의 자동화가...,지원자가 산업의 최신 이슈를 이해하고 있는지를 평가하기 위함이다.
8,사수나 선임이 적고 스스로 판단해야 하는 환경에서 어떻게 적응할 수 있을까요?,사수나 선임이 적은 환경에서는 스스로 문제를 정의하고 해결책을 찾아야 합니다. 이를...,지원자의 자율성과 적응 능력을 평가하기 위함이다.
9,불명확한 요구사항이나 우선순위 충돌 상황에서 어떻게 대응하시겠습니까?,"불명확한 요구사항이 있을 경우, 먼저 관련자와의 커뮤니케이션을 통해 요구사항을 명확...",지원자의 문제 해결 능력과 커뮤니케이션 능력을 평가하기 위함이다.

## set_id=2

### 1. 일반 체인 결과: 마스킹 없음, STAR 분석 있음

#### 생성 체크리스트

['프론트엔드 개발에 필요한 React 및 TypeScript 기술을 보유하고 있는가?',
 '웹 프론트엔드 기능 개발 및 성능 최적화 경험이 있는가?',
 'Next.js 또는 Tailwind CSS를 활용한 프로젝트 경험이 있는가?',
 '사용자 경험을 고려한 웹 애플리케이션 개발에 대한 이해가 있는가?',
 '신규 프로덕트 라인 출시를 위한 팀워크와 협업 경험이 있는가?',
 '프론트엔드 성능 최적화에 대한 실무 경험이 있는가?',
 '프론트엔드 개발에 있어 최신 기술 트렌드에 대한 관심과 학습 의지가 있는가?',
 'B2C 스타트업 환경에서의 근무 경험이 있는가?',
 '빠르게 실행하는 인재로서의 업무 스타일을 가지고 있는가?',
 '프론트엔드 팀 내에서의 원활한 커뮤니케이션 능력을 갖추고 있는가?']

#### 최종 리포트

{'overall_grade': 'C',
 'overall_summary': '지원자는 프론트엔드 개발에 필요한 기술과 경험을 보유하고 있으나, 일부 필수 기준을 충족하지 못하여 C 등급으로 평가되었습니다.',
 'candidate_summary': '지원자는 전자공학과 학사 학위를 보유하고 있으며, 이커머스 웹 프론트엔드 개발 및 디자인 시스템 구축에 4년 이상의 경력을 가지고 있습니다. 또한, 앱스토어에서 성과를 달성한 경험이 있어 실무 능력이 뛰어난 것으로 보입니다.',
 'checklist': [{'content': '프론트엔드 개발에 필요한 React 및 TypeScript 기술을 보유하고 있는가?',
   'result': True},
  {'content': '웹 프론트엔드 기능 개발 및 성능 최적화 경험이 있는가?', 'result': True},
  {'content': 'Next.js 또는 Tailwind CSS를 활용한 프로젝트 경험이 있는가?', 'result': True},
  {'content': '사용자 경험을 고려한 웹 애플리케이션 개발에 대한 이해가 있는가?', 'result': True},
  {'content': '신규 프로덕트 라인 출시를 위한 팀워크와 협업 경험이 있는가?', 'result': False},
  {'content': '프론트엔드 성능 최적화에 대한 실무 경험이 있는가?', 'result': True},
  {'content': '프론트엔드 개발에 있어 최신 기술 트렌드에 대한 관심과 학습 의지가 있는가?', 'result': False},
  {'content': 'B2C 스타트업 환경에서의 근무 경험이 있는가?', 'result': False},
  {'content': '빠르게 실행하는 인재로서의 업무 스타일을 가지고 있는가?', 'result': False},
  {'content': '프론트엔드 팀 내에서의 원활한 커뮤니케이션 능력을 갖추고 있는가?', 'result': False}],
 'competency_analysis': ['프론트엔드 개발에 필요한 React 및 TypeScript 기술을 보유하고 있으며, 이커머스 웹 프론트엔드 개발 경험이 있어 실무 능력이 뛰어납니다.',
  'Next.js를 활용한 프로젝트 경험이 있으며, 성능 최적화에 대한 실무 경험도 갖추고 있습니다.'],
 'fit_analysis': '지원자는 이커머스 웹 프론트엔드 개발 및 디자인 시스템 구축에 대한 경험이 풍부하여 해당 직무에 적합한 역량을 보유하고 있습니다. 그러나 팀워크와 협업 경험이 부족하여 일부 프로젝트에서의 기여도가 제한될 수 있습니다.',
 'motive': '지원자는 창업 동아리에서의 프로젝트 경험을 통해 성과를 달성한 바 있으며, 이를 통해 프론트엔드 개발에 대한 열정을 보여주고 있습니다. 또한, 앱스토어에서의 성과는 지원자의 동기 부여에 긍정적인 영향을 미쳤을 것으로 보입니다.',
 'collaboration': '지원자는 팀워크와 협업 경험이 부족하다는 평가를 받았으나, 과거 프로젝트에서의 성과를 통해 협업의 중요성을 인식하고 있을 것으로 예상됩니다. 향후 팀 내에서의 원활한 커뮤니케이션 능력을 개발할 필요가 있습니다.',
 'strength': ['프론트엔드 개발에 필요한 기술 보유', '이커머스 웹 개발 경험', '성과 기반의 프로젝트 경험'],
 'concern': ['팀워크 및 협업 경험 부족', '최신 기술 트렌드에 대한 관심 부족', 'B2C 스타트업 환경 경험 부족'],
 'check_point': ['팀워크와 협업 경험을 강화할 필요가 있음',
  '최신 기술 트렌드에 대한 학습 의지를 높여야 함',
  'B2C 스타트업 환경에서의 경험을 쌓는 것이 중요함'],
 'final_comment': '지원자는 프론트엔드 개발에 필요한 기술과 경험을 보유하고 있으나, 팀워크와 협업 경험이 부족하여 향후 발전이 필요합니다.'}

#### 면접 질문지

,question,answer,purpose
0,React와 TypeScript를 활용한 프로젝트에서의 구체적인 역할과 기여를 설명...,저는 픽셀하우스에서 이커머스 웹 프론트엔드 개발을 담당하며 React와 TypeSc...,지원자의 React 및 TypeScript 기술 활용 능력을 평가하기 위함입니다.
1,웹 프론트엔드 기능 개발 및 성능 최적화 경험에 대해 구체적으로 말씀해 주세요.,"이커머스 웹사이트에서 성능 최적화를 위해 다양한 기법을 적용했습니다. 예를 들어, ...",지원자의 웹 프론트엔드 기능 개발 및 성능 최적화 경험을 검증하기 위함입니다.
2,Next.js 또는 Tailwind CSS를 활용한 프로젝트 경험이 있다면 구체적으...,저는 픽셀하우스에서 Next.js를 사용하여 서버 사이드 렌더링을 구현한 경험이 있...,지원자의 Next.js 및 Tailwind CSS 활용 경험을 확인하기 위함입니다.
3,사용자 경험을 고려한 웹 애플리케이션 개발에 대한 이해를 어떻게 쌓아왔나요?,저는 사용자 경험을 최우선으로 고려하여 UI/UX 디자인 원칙을 학습했습니다. 이커...,지원자의 사용자 경험에 대한 이해도를 평가하기 위함입니다.
4,"신규 프로덕트 라인 출시를 위한 팀워크와 협업 경험이 부족한데, 이를 어떻게 보완할...","팀워크와 협업 경험이 부족하지만, 저는 다양한 온라인 커뮤니티와 오픈소스 프로젝트에...",지원자의 부족한 팀워크 및 협업 경험을 보완할 가능성을 평가하기 위함입니다.
5,"최신 기술 트렌드에 대한 관심과 학습 의지가 부족한데, 이를 어떻게 개선할 계획인가요?","최신 기술 트렌드에 대한 관심이 부족했지만, 앞으로는 기술 블로그를 구독하고, 관련...",지원자의 기술 트렌드에 대한 관심과 학습 의지를 평가하기 위함입니다.
6,"B2C 스타트업 환경에서의 근무 경험이 없는데, 이 환경에 어떻게 적응할 수 있을까요?","B2C 스타트업 환경에 대한 경험은 없지만, 빠르게 변화하는 환경에 적응하기 위해 ...",지원자의 B2C 스타트업 환경 적응 가능성을 평가하기 위함입니다.
7,프론트엔드 팀 내에서의 원활한 커뮤니케이션 능력을 어떻게 향상시킬 계획인가요?,"커뮤니케이션 능력을 향상시키기 위해, 팀원들과의 정기적인 피드백 세션을 통해 의견을...",지원자의 커뮤니케이션 능력 향상 계획을 평가하기 위함입니다.
8,회사가 속한 산업의 최근 이슈에 대해 어떻게 이해하고 있나요?,최근 이커머스 산업에서는 사용자 경험을 극대화하기 위한 개인화 서비스와 AI 기술의...,지원자가 회사 또는 산업의 최근 이슈를 이해하고 있는지를 평가하기 위함입니다.
9,사수나 선임이 적고 스스로 판단해야 하는 환경에서 어떻게 적응할 수 있을까요?,사수나 선임이 적은 환경에서는 스스로 문제를 정의하고 해결책을 찾아야 합니다. 이를...,지원자의 자율적인 판단 능력과 적응력을 평가하기 위함입니다.
10,불명확한 요구사항이나 우선순위 충돌 상황에서 어떻게 대응할 것인가요?,"불명확한 요구사항이 있을 경우, 우선 관련자와의 소통을 통해 명확한 요구사항을 파악...",지원자의 문제 해결 능력과 유연성을 평가하기 위함입니다.

### 2. 마스킹 체인 결과: 마스킹 적용, STAR 분석 있음, 최종 복호화

#### 마스킹 결과

{'comp_name': ['코드윈드', '픽셀하우스', '라온소프트'],
 'person_name': ['오건우', '이서윤'],
 'address': [],
 'personal_info': [],
 'school_edu': ['연세대학교'],
 'project_name': ['중고거래 앱'],
 'jd_discrimination': []}

#### 생성 체크리스트: 복호화 후 표시

['프론트엔드 개발에 필요한 React 및 TypeScript 기술을 보유하고 있는가?',
 '웹 프론트엔드 기능 개발 및 성능 최적화 경험이 있는가?',
 'Next.js 또는 Tailwind CSS를 활용한 프로젝트 경험이 있는가?',
 '사용자 경험을 고려한 디자인 및 개발에 대한 이해가 있는가?',
 '신규 프로덕트 라인 출시를 위한 빠른 실행 능력을 갖추고 있는가?',
 '프론트엔드 성능 최적화에 대한 경험이 있는가?',
 '프론트엔드 팀과의 협업 경험이 있는가?',
 'B2C 스타트업 환경에서의 근무 경험이 있는가?',
 '30만 명 이상의 월 활성 사용자 기반을 가진 서비스에 대한 이해가 있는가?',
 '프론트엔드 기술 스택에 대한 깊은 이해와 실무 경험이 있는가?']

잔여 마스킹 토큰: `[]`

#### 최종 리포트

{'overall_grade': 'B',
 'overall_summary': '지원자는 프론트엔드 개발에 필요한 기술과 경험을 보유하고 있으며, 특히 React, TypeScript, Next.js를 활용한 프로젝트 경험이 있습니다. 그러나 B2C 스타트업 환경에서의 경험과 팀 협업 경험이 부족하여 일부 기준을 충족하지 못했습니다.',
 'candidate_summary': '지원자는 전자공학과 학사 학위를 보유하고 있으며, 4년 이상의 프론트엔드 개발 경험을 가지고 있습니다. 이커머스 웹 프론트엔드 개발 및 디자인 시스템 구축에 대한 경험이 특히 돋보입니다.',
 'checklist': [{'content': '프론트엔드 개발에 필요한 React 및 TypeScript 기술을 보유하고 있는가?',
   'result': True},
  {'content': '웹 프론트엔드 기능 개발 및 성능 최적화 경험이 있는가?', 'result': True},
  {'content': 'Next.js 또는 Tailwind CSS를 활용한 프로젝트 경험이 있는가?', 'result': True},
  {'content': '사용자 경험을 고려한 디자인 및 개발에 대한 이해가 있는가?', 'result': True},
  {'content': '신규 프로덕트 라인 출시를 위한 빠른 실행 능력을 갖추고 있는가?', 'result': False},
  {'content': '프론트엔드 성능 최적화에 대한 경험이 있는가?', 'result': True},
  {'content': '프론트엔드 팀과의 협업 경험이 있는가?', 'result': False},
  {'content': 'B2C 스타트업 환경에서의 근무 경험이 있는가?', 'result': False},
  {'content': '30만 명 이상의 월 활성 사용자 기반을 가진 서비스에 대한 이해가 있는가?', 'result': False},
  {'content': '프론트엔드 기술 스택에 대한 깊은 이해와 실무 경험이 있는가?', 'result': True}],
 'competency_analysis': ['지원자는 React, TypeScript, Next.js 등 최신 프론트엔드 기술에 대한 깊은 이해와 실무 경험을 보유하고 있습니다.',
  '이커머스 웹 프론트엔드 개발 및 성능 최적화 경험이 있어, 실질적인 프로젝트에서의 기여가 기대됩니다.'],
 'fit_analysis': '지원자는 이커머스 웹 프론트엔드 개발 경험을 통해 실질적인 기술 역량을 갖추고 있으며, 특히 성능 최적화에 대한 경험이 돋보입니다. 그러나 B2C 스타트업 환경에서의 경험이 부족하여 해당 직무에 완벽하게 적합하다고 보기는 어렵습니다.',
 'motive': '지원자는 창업 동아리에서의 경험을 통해 프로젝트의 성과를 달성한 바 있으며, 이는 자신의 기술적 역량을 활용하여 실제 문제를 해결하고자 하는 강한 동기를 보여줍니다.',
 'collaboration': '지원서에는 프론트엔드 팀과의 협업 경험이 부족하다고 명시되어 있으며, 이는 팀워크와 협업 능력에 대한 추가 검증이 필요함을 나타냅니다.',
 'strength': ['React 및 TypeScript에 대한 높은 숙련도',
  '이커머스 웹 프론트엔드 개발 경험',
  '성능 최적화에 대한 실질적인 경험'],
 'concern': ['B2C 스타트업 환경에서의 경험 부족', '프론트엔드 팀과의 협업 경험 부족'],
 'check_point': ['B2C 스타트업 환경에서의 경험을 추가로 검증할 필요가 있음',
  '팀 협업 경험에 대한 구체적인 사례를 요청할 필요가 있음'],
 'final_comment': '지원자는 기술적 역량이 뛰어나지만, 팀워크와 스타트업 환경에서의 경험이 부족하여 추가 검증이 필요합니다.'}

#### 면접 질문지

,question,answer,purpose
0,React와 TypeScript를 활용한 프로젝트에서의 구체적인 경험을 말씀해 주실...,저는 픽셀하우스에서 이커머스 웹 프론트엔드 개발을 담당하며 React와 TypeSc...,지원자의 React 및 TypeScript 기술 활용 능력을 평가하기 위함이다.
1,웹 프론트엔드 기능 개발 및 성능 최적화 경험에 대해 구체적으로 설명해 주실 수 있...,저는 렌더링 병목을 해결하기 위해 최적화 작업을 진행했습니다. 초기 로딩 시간을 2...,지원자의 웹 프론트엔드 기능 개발 및 성능 최적화 경험을 검증하기 위함이다.
2,"Next.js 또는 Tailwind CSS를 활용한 프로젝트 경험이 있다면, 그 프...",저는 Next.js를 사용하여 서버 사이드 렌더링을 구현한 경험이 있습니다. 이를 ...,Next.js 및 Tailwind CSS 활용 경험을 확인하기 위함이다.
3,"사용자 경험을 고려한 디자인 및 개발에 대한 이해가 있다고 하셨는데, 구체적인 사례...",이커머스 웹사이트에서 사용자 피드백을 바탕으로 UI/UX 개선 작업을 진행했습니다....,지원자의 사용자 경험에 대한 이해도를 평가하기 위함이다.
4,"신규 프로덕트 라인 출시를 위한 빠른 실행 능력이 부족하다고 평가되었는데, 이를 보...","신규 프로덕트 라인 출시를 위해 Agile 방법론을 학습하고, 스프린트 단위로 작업...",지원자의 부족한 역량을 보완할 가능성을 평가하기 위함이다.
5,"프론트엔드 팀과의 협업 경험이 부족하다고 평가되었는데, 이를 극복하기 위해 어떤 방...","프론트엔드 팀과의 협업을 위해 팀 프로젝트에 참여하고, 코드 리뷰를 통해 피드백을 ...",지원자의 협업 능력 향상 가능성을 평가하기 위함이다.
6,"B2C 스타트업 환경에서의 근무 경험이 부족하다고 평가되었는데, 이러한 환경에 적응...",B2C 스타트업 환경에 적응하기 위해 시장 트렌드와 사용자 요구를 분석하는 데 집중...,지원자의 스타트업 환경 적응 가능성을 평가하기 위함이다.
7,30만 명 이상의 월 활성 사용자 기반을 가진 서비스에 대한 이해가 부족하다고 평가...,이러한 서비스를 이해하기 위해 사용자 분석 및 데이터 기반 의사결정에 대한 학습을 ...,지원자의 사용자 기반 이해도를 높일 가능성을 평가하기 위함이다.
8,최근 B2C 스타트업에서의 트렌드나 이슈에 대해 어떻게 이해하고 계신가요?,최근 B2C 스타트업에서는 개인화된 사용자 경험과 데이터 분석의 중요성이 커지고 있...,지원자가 산업의 최근 이슈를 이해하고 있는지를 평가하기 위함이다.

## LLM judge 루브릭

LLM judge는 원본 회사/JD/이력서를 기준으로 일반 체인과 마스킹 체인의 최종 산출물을 각각 독립 채점합니다. 모든 점수는 1~5점입니다.

- **source_fidelity**: 원본 근거를 왜곡하지 않고 보존했는가
- **critical_information_retention**: 채용 판단에 중요한 회사명, 직무, 기술, 경력, 학력, 자기소개서 근거가 빠지지 않았는가
- **coverage**: 체크리스트, 직무 요구사항, 지원자 핵심 경험을 충분히 다뤘는가
- **hallucination_control**: 원본에 없는 경험, 성과, 수치, 회사 내부 상황을 만들지 않았는가
- **report_quality**: 최종 리포트가 일관적이고 채용 검토에 쓸 수 있는가
- **question_quality**: 질문, 모범 답안, 질문 의도가 근거 기반이고 면접 검증에 유용한가
- **entity_recovery**: 마스킹 체인의 복호화 결과가 자연스럽고 잔여 마스킹 토큰이 없는가

`total_score`는 위 7개 지표 평균입니다. 마지막 비교표에서는 `masked - no_mask` 차이를 계산합니다.

In [6]:
from typing import Literal

from openai import OpenAI
from pydantic import BaseModel, Field


JUDGE_MODEL = os.getenv("MASKING_QUALITY_JUDGE_MODEL", "gpt-4o-mini")


class ChainQualityScore(BaseModel):
    source_fidelity: int = Field(ge=1, le=5)
    critical_information_retention: int = Field(ge=1, le=5)
    coverage: int = Field(ge=1, le=5)
    hallucination_control: int = Field(ge=1, le=5)
    report_quality: int = Field(ge=1, le=5)
    question_quality: int = Field(ge=1, le=5)
    entity_recovery: int = Field(ge=1, le=5)
    total_score: float = Field(ge=1, le=5)
    major_losses: list[str] = Field(default_factory=list)
    hallucinations: list[str] = Field(default_factory=list)
    rationale: str


class PairQualityJudgement(BaseModel):
    set_id: int
    no_mask: ChainQualityScore
    masked: ChainQualityScore
    comparative_preference: Literal["no_mask_better", "masked_better", "tie"]
    masking_delta_summary: str
    unresolved_mask_tokens: list[str] = Field(default_factory=list)
    final_recommendation: str


JUDGE_SYSTEM_PROMPT = """
당신은 채용 분석 리포트와 면접 질문지의 생성 품질을 평가하는 엄격한 LLM judge입니다.
목표는 마스킹 체인이 마스킹 없는 체인 대비 핵심 정보 손실, 환각, 복호화 오류를 일으키는지 평가하는 것입니다.

모든 점수는 1~5점입니다.
5점: 원본 근거와 생성 체크리스트에 충실하며 채용 검토에 바로 사용 가능
4점: 사소한 누락은 있으나 핵심 판단에는 문제 없음
3점: 일부 핵심 근거가 약하거나 질문/리포트 중 하나의 품질이 불안정
2점: 중요한 내용 손실, 부정확한 일반화, 근거 없는 문장이 여러 개 있음
1점: 원본과 의미가 크게 다르거나 채용 판단에 쓰기 어려움

반드시 원본 입력과 각 체인에서 생성한 체크리스트에 있는 정보만 근거로 판단하세요.
원본에 없는 경험, 성과 수치, 회사 내부 정보, 기술 숙련도를 만들면 hallucination_control을 낮게 주세요.
마스킹 체인은 복호화된 최종 결과를 평가하되, 잔여 마스킹 토큰이나 잘못 복원된 엔티티가 있으면 entity_recovery와 total_score를 낮게 주세요.
total_score는 7개 세부 지표의 산술 평균으로 계산하세요.
모든 설명은 한국어로 작성하세요.
""".strip()


def compact_json(obj: Any, max_chars: int = 24000) -> str:
    text = json.dumps(obj, ensure_ascii=False, indent=2)
    if len(text) <= max_chars:
        return text
    return text[:max_chars] + "\n...TRUNCATED..."


def build_judge_payload(record: dict[str, Any]) -> dict[str, Any]:
    return {
        "set_id": record["set_id"],
        "source_input": record["source"],
        "no_mask_output": {
            "generated_checklist": record["no_mask"]["checklist_generation"]["checklist"],
            "report": record["no_mask"]["report"],
            "questions": record["no_mask"]["questions"],
        },
        "masked_then_unmasked_output": {
            "mask_result": record["masked"]["mask_result"],
            "generated_checklist_after_unmask": record["masked"]["unmasked_checklist_generation"]["checklist"],
            "report": record["masked"]["report"],
            "questions": record["masked"]["questions"],
            "unresolved_mask_tokens_detected_by_regex": find_mask_tokens(record["masked"]["full_result"]),
        },
    }


def judge_pair(record: dict[str, Any]) -> dict[str, Any]:
    client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))
    messages = [
        {"role": "system", "content": JUDGE_SYSTEM_PROMPT},
        {"role": "user", "content": "다음 JSON을 평가하세요.\n\n" + compact_json(build_judge_payload(record))},
    ]
    parse_method = getattr(client.beta.chat.completions, "parse", None)
    if parse_method:
        response = parse_method(
            model=JUDGE_MODEL,
            messages=messages,
            response_format=PairQualityJudgement,
            temperature=0,
        )
        return response.choices[0].message.parsed.model_dump()

    response = client.chat.completions.create(
        model=JUDGE_MODEL,
        messages=messages,
        response_format={"type": "json_object"},
        temperature=0,
    )
    return PairQualityJudgement.model_validate_json(response.choices[0].message.content).model_dump()

## LLM judge 실행

이미 평가 결과 캐시가 있으면 재사용합니다. 다시 평가하려면 `MASKING_QUALITY_FORCE_REJUDGE=1`을 설정하세요.

In [7]:
if JUDGE_CACHE_PATH.exists() and not FORCE_REJUDGE:
    judge_records = load_json(JUDGE_CACHE_PATH)
    print(f"judge 캐시 로드: {JUDGE_CACHE_PATH} ({len(judge_records)}건)")
else:
    judge_records = []
    for record in chain_records:
        sid = record["set_id"]
        print(f"[set_id={sid}] LLM judge 실행")
        judgement = judge_pair(record)
        judge_records.append(judgement)
        save_json(JUDGE_CACHE_PATH, judge_records)

if pd is not None:
    display(pd.json_normalize(judge_records))
else:
    display(judge_records)

[set_id=0] LLM judge 실행
[set_id=1] LLM judge 실행
[set_id=2] LLM judge 실행

,set_id,comparative_preference,masking_delta_summary,unresolved_mask_tokens,final_recommendation,no_mask.source_fidelity,no_mask.critical_information_retention,no_mask.coverage,no_mask.hallucination_control,no_mask.report_quality,...,masked.critical_information_retention,masked.coverage,masked.hallucination_control,masked.report_quality,masked.question_quality,masked.entity_recovery,masked.total_score,masked.major_losses,masked.hallucinations,masked.rationale
0,0,no_mask_better,마스킹 후 체크리스트 항목의 일부 내용이 변경되어 평가 결과가 다르게 나타났습니다....,[],"마스킹 없는 결과를 우선적으로 사용하고, 마스킹된 결과는 추가 검증이 필요합니다.",5,5,5,5,5,...,4,4,4,4,4,3,3.71,[일부 체크리스트 항목의 세부 내용이 변경되어 원본과 다르게 평가됨],[지원자의 경력에 대한 구체적인 수치가 누락됨],마스킹 후 복호화 과정에서 일부 체크리스트 항목의 내용이 변경되어 원본과 다르게 평...
1,1,no_mask_better,마스킹 체인은 일부 정보 손실과 엔티티 복원 오류가 발생하여 원본에 비해 품질이 떨어짐.,[],"마스킹 없는 결과를 우선적으로 사용하고, 마스킹된 결과는 보조 자료로 활용할 것을 ...",5,5,5,5,5,...,4,4,4,4,4,3,3.71,"[일부 핵심 정보가 마스킹으로 인해 손실됨, 최종 결과에서 일부 엔티티가 잘못 복원됨]",[],"마스킹 체인은 원본에 비해 일부 정보가 손실되었고, 엔티티 복원에서 오류가 발생했습..."
2,2,no_mask_better,"마스킹된 결과는 원본에 비해 일부 정보가 누락되었으나, 전반적으로 핵심 정보는 잘 ...",[],"마스킹 없는 결과가 더 우수하며, 채용 판단에 바로 사용 가능하다.",5,5,5,5,5,...,4,4,4,4,4,4,4.00,[B2C 스타트업 환경에서의 경험 부족에 대한 구체적인 설명이 부족함],[],"마스킹된 결과는 원본에 비해 일부 정보가 누락되었으나, 전반적으로 핵심 정보는 잘 ..."

## 최종 수치 비교

아래 표의 `delta_masked_minus_no_mask`가 핵심 비교값입니다. 음수이면 마스킹 체인에서 품질 손실이 생긴 것이고, 양수이면 마스킹 체인이 더 좋은 평가를 받은 것입니다.

In [8]:
METRICS = [
    "source_fidelity",
    "critical_information_retention",
    "coverage",
    "hallucination_control",
    "report_quality",
    "question_quality",
    "entity_recovery",
    "total_score",
]


def flatten_dict(obj: dict[str, Any], prefix: str = "") -> dict[str, Any]:
    out = {}
    for key, value in obj.items():
        path = f"{prefix}.{key}" if prefix else key
        if isinstance(value, dict):
            out.update(flatten_dict(value, path))
        else:
            out[path] = value
    return out


judge_rows = [flatten_dict(item) for item in judge_records]

summary_rows = []
for metric in METRICS:
    no_values = [float(row[f"no_mask.{metric}"]) for row in judge_rows]
    masked_values = [float(row[f"masked.{metric}"]) for row in judge_rows]
    no_avg = sum(no_values) / len(no_values)
    masked_avg = sum(masked_values) / len(masked_values)
    summary_rows.append(
        {
            "metric": metric,
            "no_mask_avg": no_avg,
            "masked_avg": masked_avg,
            "delta_masked_minus_no_mask": masked_avg - no_avg,
            "no_mask_min": min(no_values),
            "masked_min": min(masked_values),
        }
    )

pairwise_rows = []
for row in judge_rows:
    no_total = float(row["no_mask.total_score"])
    masked_total = float(row["masked.total_score"])
    pairwise_rows.append(
        {
            "set_id": row["set_id"],
            "comparative_preference": row["comparative_preference"],
            "no_mask_total": no_total,
            "masked_total": masked_total,
            "total_delta": masked_total - no_total,
            "masking_delta_summary": row["masking_delta_summary"],
            "final_recommendation": row["final_recommendation"],
        }
    )

if pd is not None:
    summary_df = pd.DataFrame(summary_rows)
    pairwise_df = pd.DataFrame(pairwise_rows)
    display(summary_df)
    display(pairwise_df)
    summary_df.to_csv(EVAL_DIR / "masking_quality_metric_summary.csv", index=False, encoding="utf-8")
    pairwise_df.to_csv(EVAL_DIR / "masking_quality_pairwise_summary.csv", index=False, encoding="utf-8")
    pd.DataFrame(judge_rows).to_csv(EVAL_DIR / "masking_quality_judge_detail.csv", index=False, encoding="utf-8")
else:
    display(summary_rows)
    display(pairwise_rows)

print("저장 파일:")
print(EVAL_DIR / "masking_quality_metric_summary.csv")
print(EVAL_DIR / "masking_quality_pairwise_summary.csv")
print(EVAL_DIR / "masking_quality_judge_detail.csv")

,metric,no_mask_avg,masked_avg,delta_masked_minus_no_mask,no_mask_min,masked_min
0,source_fidelity,5.0,4.000000,-1.000000,5.0,4.00
1,critical_information_retention,5.0,4.000000,-1.000000,5.0,4.00
2,coverage,5.0,4.000000,-1.000000,5.0,4.00
3,hallucination_control,5.0,4.000000,-1.000000,5.0,4.00
4,report_quality,5.0,4.000000,-1.000000,5.0,4.00
5,question_quality,5.0,4.000000,-1.000000,5.0,4.00
6,entity_recovery,5.0,3.333333,-1.666667,5.0,3.00
7,total_score,5.0,3.806667,-1.193333,5.0,3.71

,set_id,comparative_preference,no_mask_total,masked_total,total_delta,masking_delta_summary,final_recommendation
0,0,no_mask_better,5.0,3.71,-1.29,마스킹 후 체크리스트 항목의 일부 내용이 변경되어 평가 결과가 다르게 나타났습니다....,"마스킹 없는 결과를 우선적으로 사용하고, 마스킹된 결과는 추가 검증이 필요합니다."
1,1,no_mask_better,5.0,3.71,-1.29,마스킹 체인은 일부 정보 손실과 엔티티 복원 오류가 발생하여 원본에 비해 품질이 떨어짐.,"마스킹 없는 결과를 우선적으로 사용하고, 마스킹된 결과는 보조 자료로 활용할 것을 ..."
2,2,no_mask_better,5.0,4.00,-1.00,"마스킹된 결과는 원본에 비해 일부 정보가 누락되었으나, 전반적으로 핵심 정보는 잘 ...","마스킹 없는 결과가 더 우수하며, 채용 판단에 바로 사용 가능하다."

저장 파일:
C:\project_skn\final\Final_project\backend\common\eval\masking_quality_metric_summary.csv
C:\project_skn\final\Final_project\backend\common\eval\masking_quality_pairwise_summary.csv
C:\project_skn\final\Final_project\backend\common\eval\masking_quality_judge_detail.csv