In [1]:
!pip install transformers==4.57.1 accelerate==1.14.0 sentencepiece==0.2.1 safetensors==0.8.0 huggingface_hub==0.36.2 langchain-huggingface==1.2.2 langchain-core==1.4.8

Collecting transformers==4.57.1
  Using cached transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Collecting accelerate==1.14.0
  Using cached accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Collecting sentencepiece==0.2.1
  Using cached sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting safetensors==0.8.0
  Using cached safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting huggingface_hub==0.36.2
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Collecting langchain-huggingface==1.2.2
  Using cached langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)
Collecting langchain-core==1.4.8
  Using cached langchain_core-1.4.8-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (3.20.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (6.0.3)
Collecting regex!=2019.12.17 (from transformers==4.57.1)
  Using cached regex-2026.6.28-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.32.5)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers==4.57.1)
  Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting tqdm>=4.27 (from transformers==4.57.1)
  Using cached tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.36.2) (2024.6.1)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface_hub==0.36.2)
  Using cached hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.36.2) (4.15.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate==1.14.0) (7.1.0)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate==1.14.0) (2.8.0+cu128)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core==1.4.8)
  Using cached jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-protocol>=0.0.17 (from langchain-core==1.4.8)
  Using cached langchain_protocol-0.0.18-py3-none-any.whl.metadata (2.4 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core==1.4.8)
  Using cached langsmith-0.9.3-py3-none-any.whl.metadata (21 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain-core==1.4.8)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain-core==1.4.8)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core==1.4.8)
  Using cached uuid_utils-0.16.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core==1.4.8) (3.0.0)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (4.11.0)
Requirement already satisfied: distro>=1.7.0 in /usr/lib/python3/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (0.28.1)
Collecting orjson>=3.9.14 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (1.3.1)
Collecting websockets>=15.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached websockets-16.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.8 kB)
Collecting xxhash>=3.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached xxhash-3.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (0.16.0)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain-core==1.4.8)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.7.4->langchain-core==1.4.8)
  Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain-core==1.4.8)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate==1.14.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate==1.14.0) (3.0.3)
Using cached transformers-4.57.1-py3-none-any.whl (12.0 MB)
Using cached huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
Using cached accelerate-1.14.0-py3-none-any.whl (389 kB)
Using cached sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
Using cached safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (516 kB)
Using cached langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)
Using cached langchain_core-1.4.8-py3-none-any.whl (557 kB)
Using cached hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Using cached langsmith-0.9.3-py3-none-any.whl (619 kB)
Using cached pydantic-2.13.4-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Using cached uuid_utils-0.16.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (323 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached langchain_protocol-0.0.18-py3-none-any.whl (7.2 kB)
Using cached orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (134 kB)
Using cached regex-2026.6.28-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Using cached tqdm-4.68.3-py3-none-any.whl (78 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached websockets-16.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (184 kB)
Using cached xxhash-3.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (220 kB)
Using cached zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
Installing collected packages: zstandard, xxhash, websockets, uuid-utils, typing-inspection, tqdm, tenacity, sentencepiece, safetensors, regex, pydantic-core, orjson, langchain-protocol, jsonpatch, hf-xet, annotated-types, requests-toolbelt, pydantic, huggingface_hub, tokenizers, langsmith, transformers, langchain-core, accelerate, langchain-huggingface
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25/25 [langchain-huggingface]lerate]ore]]t]
Successfully installed accelerate-1.14.0 annotated-types-0.7.0 hf-xet-1.5.1 huggingface_hub-0.36.2 jsonpatch-1.33 langchain-core-1.4.8 langchain-huggingface-1.2.2 langchain-protocol-0.0.18 langsmith-0.9.3 orjson-3.11.9 pydantic-2.13.4 pydantic-core-2.46.4 regex-2026.6.28 requests-toolbelt-1.0.0 safetensors-0.8.0 sentencepiece-0.2.1 tenacity-9.1.4 tokenizers-0.22.2 tqdm-4.68.3 transformers-4.57.1 typing-inspection-0.4.2 uuid-utils-0.16.2 websockets-16.0 xxhash-3.8.0 zstandard-0.25.0

In [2]:
!pip install hf_transfer

Collecting hf_transfer
  Using cached hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Using cached hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
Installing collected packages: hf_transfer
Successfully installed hf_transfer-0.1.9

In [3]:
!pip install -U datasets peft trl accelerate bitsandbytes "transformers==4.57.1"

Collecting datasets
  Using cached datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Collecting peft
  Using cached peft-0.19.1-py3-none-any.whl.metadata (15 kB)
Collecting trl
  Using cached trl-1.7.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Collecting bitsandbytes
  Using cached bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: transformers==4.57.1 in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2026.6.28)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (4.68.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (4.15.0)
Collecting pyarrow>=21.0.0 (from datasets)
  Using cached pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets)
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.0)
Collecting multiprocess<0.70.20 (from datasets)
  Using cached multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached aiohttp-3.14.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (7.1.0)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.8.0+cu128)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.6.2-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached propcache-0.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached yarl-1.24.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (94 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Using cached datasets-5.0.0-py3-none-any.whl (555 kB)
Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Using cached multiprocess-0.70.19-py312-none-any.whl (150 kB)
Using cached peft-0.19.1-py3-none-any.whl (680 kB)
Using cached trl-1.7.0-py3-none-any.whl (838 kB)
Using cached bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
Using cached aiohttp-3.14.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
Using cached multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (256 kB)
Using cached yarl-1.24.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (105 kB)
Using cached aiohappyeyeballs-2.6.2-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (242 kB)
Using cached propcache-0.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (61 kB)
Using cached pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 54.5 MB/s  0:00:006m0:00:01
Installing collected packages: pyarrow, propcache, multidict, frozenlist, dill, aiohappyeyeballs, yarl, pandas, multiprocess, aiosignal, aiohttp, bitsandbytes, peft, datasets, trl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/15 [trl]32m14/15 [trl]sets]tes]
Successfully installed aiohappyeyeballs-2.6.2 aiohttp-3.14.1 aiosignal-1.4.0 bitsandbytes-0.49.2 datasets-5.0.0 dill-0.4.1 frozenlist-1.8.0 multidict-6.7.1 multiprocess-0.70.19 pandas-3.0.3 peft-0.19.1 propcache-0.5.2 pyarrow-24.0.0 trl-1.7.0 yarl-1.24.2

In [4]:
pip install -U transformers accelerate bitsandbytes

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Collecting transformers
  Using cached transformers-5.12.1-py3-none-any.whl.metadata (33 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Using cached huggingface_hub-1.21.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2026.6.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Collecting typer (from transformers)
  Using cached typer-0.26.8-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.68.3)
Collecting click>=8.4.0 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Collecting typer (from transformers)
  Using cached typer-0.25.1-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer->transformers)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (7.1.0)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.8.0+cu128)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.0)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer->transformers)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Using cached transformers-5.12.1-py3-none-any.whl (11.2 MB)
Using cached huggingface_hub-1.21.0-py3-none-any.whl (721 kB)
Using cached typer-0.25.1-py3-none-any.whl (58 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: shellingham, mdurl, click, annotated-doc, markdown-it-py, rich, typer, huggingface-hub, transformers
  Attempting uninstall: huggingface-hub╺━━━━━━━━━━━━━━━━━ 5/9 [rich]own-it-py]
    Found existing installation: huggingface_hub 0.36.2━━━━━━━ 5/9 [rich]
    Uninstalling huggingface_hub-0.36.2:━━━━━━━━━━━━━━━━━ 5/9 [rich]
      Successfully uninstalled huggingface_hub-0.36.2━━━━━━━━━ 5/9 [rich]
  Attempting uninstall: transformers━━━╺━━━━━━━━ 7/9 [huggingface-hub]
    Found existing installation: transformers 4.57.10m━━━━━━━━ 7/9 [huggingface-hub]
    Uninstalling transformers-4.57.1:━━━━━━╸━━━━ 8/9 [transformers]
      Successfully uninstalled transformers-4.57.11m╸━━━━ 8/9 [transformers]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [transformers][0m [transformers]
Successfully installed annotated-doc-0.0.4 click-8.4.2 huggingface-hub-1.21.0 markdown-it-py-4.2.0 mdurl-0.1.2 rich-15.0.0 shellingham-1.5.4 transformers-5.12.1 typer-0.25.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import os
from huggingface_hub import login

hf_token = os.environ.get("HF_TOKEN")

if hf_token is None:
    raise ValueError(
        "HF_TOKEN 환경변수가 없습니다. RunPod Secrets에 HF_TOKEN을 등록했는지 확인하세요."
    )

login(token=hf_token)

print("Hugging Face login completed.")

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Hugging Face login completed.

In [3]:
import json
from collections import Counter

from datasets import load_dataset


JSONL_PATH = "masking_train_500.jsonl"

LABEL_CATS = [
    "comp_name",
    "person_name",
    "address",
    "personal_info",
    "school_edu",
    "project_name",
    "jd_discrimination",
]


def _assistant_text(example):
    for message in reversed(example["messages"]):
        if message.get("role") == "assistant":
            return message.get("content", "")
    return ""


def add_strata(example):
    label = example.get("label")

    if isinstance(label, dict):
        clean = all(not label.get(category) for category in LABEL_CATS)
    else:
        try:
            obj = json.loads(_assistant_text(example))
            clean = all(not obj.get(category) for category in LABEL_CATS)
        except Exception:
            clean = False

    return {
        "strata": "clean" if clean else "sensitive"
    }


dataset = load_dataset(
    "json",
    data_files={"train": JSONL_PATH},
)["train"]

dataset = dataset.map(add_strata)
dataset = dataset.class_encode_column("strata")

names = dataset.features["strata"].names
print("total size:", len(dataset))
print("total strata:", Counter(names[i] for i in dataset["strata"]))

total size: 500
total strata: Counter({'sensitive': 400, 'clean': 100})

In [6]:
from collections import Counter
import json


OUTPUT_DIR = "./exaone-masking-lora-622-epoch8-earlystop"

LABEL_CATS = [
    "comp_name",
    "person_name",
    "address",
    "personal_info",
    "school_edu",
    "project_name",
    "jd_discrimination",
]


format_instructions = """
{
  "comp_name": [],
  "person_name": [],
  "address": [],
  "personal_info": [],
  "school_edu": [],
  "project_name": [],
  "jd_discrimination": []
}
""".strip()


STRICT_SYSTEM_PROMPT = f"""
당신은 한국 채용 데이터의 개인정보 마스킹 전문가입니다.
입력으로 들어온 자유 텍스트(자기소개서, 채용공고(JD) 본문, 회사 소개,
채용 사유, 메모 등)에서 "마스킹이 필요한 표현"을 찾아
아래 7개 카테고리로 분류하여 추출하세요.

[마스킹 카테고리]
1. comp_name        : 회사/기관/고객사/이전 근무처 등 조직 식별명
2. person_name      : 지원자 본인 및 제3자(교수·추천인·동료 등)의 실명
3. address          : 주소 및 출신·거주 지역
4. personal_info    : 고유식별정보·연락처·차별위험정보·민감정보
5. school_edu       : 학교/교육기관/주최기관명
6. project_name     : 내부·제3자 정보가 포함될 수 있는 프로젝트 실명
7. jd_discrimination: JD 내 차별 소지 조항

[출력 규칙]
- 반드시 JSON object 하나만 출력한다.
- 첫 글자는 반드시 {{ 로 시작하고 마지막 글자는 반드시 }} 로 끝난다.
- 코드블록, 코드펜스, ```json, ``` 를 절대 사용하지 않는다.
- 설명, 해설, 마크다운, 리스트 단독 출력, 번역, 영어 변환을 절대 하지 않는다.
- 입력 텍스트에 등장한 원문 표현 그대로 추출한다.
- 동일 표현은 한 번만 넣는다.
- 해당 카테고리에 없으면 빈 리스트 []를 넣는다.
- 키는 반드시 아래 JSON 스키마의 7개만 사용한다.

[출력 형식]
{format_instructions}
""".strip()


def force_system_prompt(messages, include_answer=True):
    new_messages = []

    source_messages = list(messages)
    if not include_answer and source_messages and source_messages[-1].get("role") == "assistant":
        source_messages = source_messages[:-1]

    has_system = source_messages and source_messages[0].get("role") == "system"

    if has_system:
        new_messages.append({
            "role": "system",
            "content": STRICT_SYSTEM_PROMPT,
        })
        new_messages.extend(source_messages[1:])
    else:
        new_messages.append({
            "role": "system",
            "content": STRICT_SYSTEM_PROMPT,
        })
        new_messages.extend(source_messages)

    return new_messages


# 1차 split: test 20%
split_1 = dataset.train_test_split(
    test_size=0.2,
    seed=42,
    stratify_by_column="strata",
)

train_val_dataset = split_1["train"]
test_dataset_raw = split_1["test"]

# 2차 split: 남은 80% 중 validation 25% = 전체 기준 20%
split_2 = train_val_dataset.train_test_split(
    test_size=0.25,
    seed=42,
    stratify_by_column="strata",
)

train_dataset_raw = split_2["train"]
eval_dataset_raw = split_2["test"]

names = dataset.features["strata"].names

print("train strata:", Counter(names[i] for i in train_dataset_raw["strata"]))
print("val   strata:", Counter(names[i] for i in eval_dataset_raw["strata"]))
print("test  strata:", Counter(names[i] for i in test_dataset_raw["strata"]))

remove_cols = ["strata"] + (["label"] if "label" in dataset.column_names else [])

train_dataset = train_dataset_raw.remove_columns(remove_cols)
eval_dataset = eval_dataset_raw.remove_columns(remove_cols)
test_dataset = test_dataset_raw.remove_columns(remove_cols)

print("train size:", len(train_dataset))
print("val size  :", len(eval_dataset))
print("test size :", len(test_dataset))
print("output dir:", OUTPUT_DIR)

train strata: Counter({'sensitive': 240, 'clean': 60})
val   strata: Counter({'sensitive': 80, 'clean': 20})
test  strata: Counter({'sensitive': 80, 'clean': 20})
train size: 300
val size  : 100
test size : 100
output dir: ./exaone-masking-lora-622-epoch8-earlystop

In [6]:
import inspect
import sys
import types
from typing import TypedDict

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from transformers import EarlyStoppingCallback
from peft import LoraConfig, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig


MODEL_NAME = "LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct"

if "OUTPUT_DIR" not in globals():
    OUTPUT_DIR = "./exaone-masking-lora-622-epoch8-earlystop"


# ---------------------------------------------------------------- transformers / EXAONE compatibility patches

try:
    import transformers.modeling_rope_utils as _rope_utils

    if not hasattr(_rope_utils, "RopeParameters"):
        class RopeParameters(TypedDict, total=False):
            rope_type: str
            factor: float
            low_freq_factor: float
            high_freq_factor: float
            original_max_position_embeddings: int
            attention_factor: float
            beta_fast: float
            beta_slow: float
            short_factor: list[float]
            long_factor: list[float]

        _rope_utils.RopeParameters = RopeParameters
        print("[PATCH] Added missing transformers.modeling_rope_utils.RopeParameters shim.")
except Exception as e:
    print(f"[PATCH][WARN] RopeParameters shim skipped: {e}")


try:
    import transformers.integrations as _tf_integrations

    def _noop_kernel_patch(*args, **kwargs):
        if args and callable(args[0]) and len(args) == 1:
            return args[0]

        def _decorator(fn):
            return fn

        return _decorator

    for _name in (
        "use_kernel_forward_from_hub",
        "use_kernel_func_from_hub",
        "use_kernelized_func",
    ):
        if not hasattr(_tf_integrations, _name):
            setattr(_tf_integrations, _name, _noop_kernel_patch)
            print(f"[PATCH] Added missing transformers.integrations.{_name} shim.")
except Exception as e:
    print(f"[PATCH][WARN] integrations shim skipped: {e}")


def _patch_exaone(model):
    if hasattr(model, "_exaone_compat_patched") and model._exaone_compat_patched:
        return model

    if hasattr(model, "transformer") and hasattr(model.transformer, "wte"):
        embed = model.transformer.wte
    elif hasattr(model, "transformer") and hasattr(model.transformer, "embed_tokens"):
        embed = model.transformer.embed_tokens
    elif hasattr(model, "model") and hasattr(model.model, "embed_tokens"):
        embed = model.model.embed_tokens
    else:
        raise AttributeError(
            "embedding layer not found. Check model structure.\n" + str(model)
        )

    model.get_input_embeddings = lambda: embed
    model.set_input_embeddings = lambda v: setattr(embed, "weight", v.weight)

    import transformers.masking_utils as masking_utils

    original_create_causal_mask = masking_utils.create_causal_mask
    original_params = inspect.signature(original_create_causal_mask).parameters

    def _create_causal_mask_compat(*args, **kwargs):
        if "input_embeds" in kwargs and "input_embeds" not in original_params:
            value = kwargs.pop("input_embeds")
            if "inputs_embeds" in original_params:
                kwargs["inputs_embeds"] = value
            elif "input_tensor" in original_params:
                kwargs["input_tensor"] = value
            else:
                kwargs["input_ids"] = value
        elif "inputs_embeds" in kwargs and "inputs_embeds" not in original_params:
            value = kwargs.pop("inputs_embeds")
            if "input_embeds" in original_params:
                kwargs["input_embeds"] = value
            elif "input_tensor" in original_params:
                kwargs["input_tensor"] = value
            else:
                kwargs["input_ids"] = value

        accepts_var_kwargs = any(
            p.kind == inspect.Parameter.VAR_KEYWORD
            for p in original_params.values()
        )

        if not accepts_var_kwargs:
            kwargs = {
                key: value
                for key, value in kwargs.items()
                if key in original_params
            }

        return original_create_causal_mask(*args, **kwargs)

    masking_utils.create_causal_mask = _create_causal_mask_compat

    for module in list(sys.modules.values()):
        if module is None or not hasattr(module, "create_causal_mask"):
            continue
        if getattr(module, "create_causal_mask", None) is original_create_causal_mask:
            setattr(module, "create_causal_mask", _create_causal_mask_compat)

    backbone = getattr(model, "transformer", None) or getattr(model, "model", None)

    if backbone is not None and not hasattr(backbone, "_exaone_forward_patched"):
        original_forward = backbone.forward

        def _patched_forward(self, *args, **kwargs):
            if "input_embeds" in kwargs and "inputs_embeds" not in kwargs:
                kwargs["inputs_embeds"] = kwargs.pop("input_embeds")
            return original_forward(*args, **kwargs)

        backbone.forward = types.MethodType(_patched_forward, backbone)
        backbone._exaone_forward_patched = True

    model._exaone_compat_patched = True
    print("[PATCH] EXAONE embedding + create_causal_mask compatibility patch applied.")
    return model


# ---------------------------------------------------------------- tokenizer

if "tokenizer" not in globals():
    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME,
        trust_remote_code=True,
    )

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "right"


# ---------------------------------------------------------------- model load for QLoRA

if "model" not in globals():
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )

    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    )
    print("[LOAD] 4bit base model loaded.")
else:
    print("[LOAD] Reusing existing model.")

model.config.use_cache = False
model = _patch_exaone(model)

if not hasattr(model, "_kbit_training_prepared"):
    model = prepare_model_for_kbit_training(model)
    model._kbit_training_prepared = True
    print("[PATCH] prepare_model_for_kbit_training applied.")


# ---------------------------------------------------------------- formatting + LoRA + Trainer

def formatting_func(example):
    messages = force_system_prompt(example["messages"], include_answer=True)

    return tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False,
    )


lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj", "k_proj", "v_proj",
        "out_proj",
        "c_fc_0", "c_fc_1", "c_proj",
    ],
)


training_args = SFTConfig(
    output_dir=OUTPUT_DIR,
    num_train_epochs=8,

    per_device_train_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=2e-4,

    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    save_total_limit=2,
    report_to="none",
    disable_tqdm=False,

    bf16=True,
    max_length=4096,
    packing=False,
)


trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=eval_dataset,
    peft_config=lora_config,
    formatting_func=formatting_func,
    processing_class=tokenizer,
    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=2,
            early_stopping_threshold=0.0,
        )
    ],
)


print("=== 학습 전 Validation Eval Loss ===")
initial_eval = trainer.evaluate()
print(f"initial eval_loss: {initial_eval['eval_loss']:.4f}")

trainer.train()

print("\n========================")
print("Best Checkpoint")
print("========================")
print("checkpoint:", trainer.state.best_model_checkpoint)
print("eval_loss :", trainer.state.best_metric)

print("\n=== Best 모델 기준 Validation Eval Loss ===")
final_eval = trainer.evaluate()
print(f"final eval_loss: {final_eval['eval_loss']:.4f}")

trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"\n최종(best) Adapter 저장 완료: {OUTPUT_DIR}")

[LOAD] Reusing existing model.

/usr/local/lib/python3.12/dist-packages/peft/mapping_func.py:72: UserWarning: You are trying to modify a model with PEFT for a second time. If you want to reload the model with a different config, make sure to call `.unload()` before.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/peft/tuners/tuners_utils.py:302: UserWarning: Already found a `peft_config` attribute in the model. This will lead to having multiple adapters in the model. Make sure to know what you are doing!
  warnings.warn(

=== 학습 전 Validation Eval Loss ===

initial eval_loss: 2.3545

========================
Best Checkpoint
========================
checkpoint: ./exaone-masking-lora-622-epoch8-earlystop/checkpoint-190
eval_loss : 0.14071343839168549

=== Best 모델 기준 Validation Eval Loss ===

final eval_loss: 0.1407

최종(best) Adapter 저장 완료: ./exaone-masking-lora-622-epoch8-earlystop

# best 모델로 추론하는 함수

In [13]:
import torch


inference_model = trainer.model
inference_model.eval()

if hasattr(inference_model, "config"):
    inference_model.config.use_cache = True

if tokenizer.pad_token_id is None:
    tokenizer.pad_token = tokenizer.eos_token


def predict_with_strict_prompt(input_json_text, model=inference_model, tokenizer=tokenizer):
    messages = [
        {
            "role": "system",
            "content": STRICT_SYSTEM_PROMPT,
        },
        {
            "role": "user",
            "content": input_json_text,
        },
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    device = next(model.parameters()).device

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        add_special_tokens=False,
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=256,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    generated = outputs[0][inputs["input_ids"].shape[-1]:]

    return tokenizer.decode(
        generated,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    ).strip()

# 평가

In [14]:
import re
import json
from collections import defaultdict


LABEL_CATS = [
    "comp_name",
    "person_name",
    "address",
    "personal_info",
    "school_edu",
    "project_name",
    "jd_discrimination",
]


def empty_masking_result():
    return {key: [] for key in LABEL_CATS}


def parse_prediction_json(text):
    text = text.strip()

    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    first = text.find("{")
    last = text.rfind("}")

    if first == -1 or last == -1 or first >= last:
        raise ValueError(f"JSON object를 찾지 못했습니다: {text}")

    text = text[first:last + 1]

    obj = json.loads(text)

    if not isinstance(obj, dict):
        return empty_masking_result()

    return {
        key: obj.get(key, []) if isinstance(obj.get(key, []), list) else []
        for key in LABEL_CATS
    }


def normalize_gold_json(text):
    obj = json.loads(text)

    return {
        key: obj.get(key, []) if isinstance(obj.get(key, []), list) else []
        for key in LABEL_CATS
    }


def item_set(values):
    return set(
        str(value).strip()
        for value in values
        if str(value).strip()
    )


def safe_div(num, den):
    return num / den if den else 0.0


def f_beta(precision, recall, beta=2):
    beta_sq = beta ** 2
    return safe_div(
        (1 + beta_sq) * precision * recall,
        beta_sq * precision + recall,
    )


def evaluate_field_items(dataset_to_eval, max_samples=None, show_progress=True):
    n = len(dataset_to_eval) if max_samples is None else min(len(dataset_to_eval), max_samples)

    total_tp = 0
    total_fp = 0
    total_fn = 0

    exact_match_count = 0
    parse_fail_count = 0

    by_category = {
        key: {"tp": 0, "fp": 0, "fn": 0, "exact": 0}
        for key in LABEL_CATS
    }

    failed_examples = []
    diff_examples = []

    for i in range(n):
        sample = dataset_to_eval[i]
        input_text = sample["messages"][1]["content"]
        gold_text = sample["messages"][-1]["content"]

        pred_raw = predict_with_strict_prompt(input_text)
        gold = normalize_gold_json(gold_text)

        try:
            pred = parse_prediction_json(pred_raw)
        except Exception as e:
            parse_fail_count += 1
            pred = empty_masking_result()

            if len(failed_examples) < 5:
                failed_examples.append({
                    "index": i,
                    "error": str(e),
                    "pred_raw": pred_raw,
                    "gold": gold,
                })

        sample_exact = True

        for key in LABEL_CATS:
            pred_items = item_set(pred.get(key, []))
            gold_items = item_set(gold.get(key, []))

            tp = len(pred_items & gold_items)
            fp = len(pred_items - gold_items)
            fn = len(gold_items - pred_items)

            by_category[key]["tp"] += tp
            by_category[key]["fp"] += fp
            by_category[key]["fn"] += fn

            total_tp += tp
            total_fp += fp
            total_fn += fn

            if pred_items == gold_items:
                by_category[key]["exact"] += 1
            else:
                sample_exact = False

        if sample_exact:
            exact_match_count += 1
        elif len(diff_examples) < 5:
            diff_examples.append({
                "index": i,
                "input": input_text,
                "pred_raw": pred_raw,
                "pred": pred,
                "gold": gold,
            })

        if show_progress and (i + 1) % 10 == 0:
            print(f"evaluated {i + 1}/{n}")

    micro_precision = safe_div(total_tp, total_tp + total_fp)
    micro_recall = safe_div(total_tp, total_tp + total_fn)
    micro_f1 = f_beta(micro_precision, micro_recall, beta=1)
    micro_f2 = f_beta(micro_precision, micro_recall, beta=2)

    result = {
        "samples": n,
        "parse_fail": parse_fail_count,
        "parse_success_rate": safe_div(n - parse_fail_count, n),
        "exact_match_accuracy": safe_div(exact_match_count, n),
        "micro_precision": micro_precision,
        "micro_recall": micro_recall,
        "micro_f1": micro_f1,
        "micro_f2": micro_f2,
        "by_category": {},
        "failed_examples": failed_examples,
        "diff_examples": diff_examples,
    }

    for key, counts in by_category.items():
        tp = counts["tp"]
        fp = counts["fp"]
        fn = counts["fn"]

        precision = safe_div(tp, tp + fp)
        recall = safe_div(tp, tp + fn)
        f1 = f_beta(precision, recall, beta=1)
        f2 = f_beta(precision, recall, beta=2)

        result["by_category"][key] = {
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "f2": f2,
            "exact_match": safe_div(counts["exact"], n),
            "tp": tp,
            "fp": fp,
            "fn": fn,
        }

    return result

In [15]:
# test_dataset 평가 실행
test_result = evaluate_field_items(test_dataset, show_progress=True)

print("\n==============================")
print("Overall Metrics")
print("==============================")
print("samples              :", test_result["samples"])
print("parse_fail           :", test_result["parse_fail"])
print("parse_success_rate   :", round(test_result["parse_success_rate"], 4))
print("exact_match_accuracy :", round(test_result["exact_match_accuracy"], 4))
print("micro_precision      :", round(test_result["micro_precision"], 4))
print("micro_recall         :", round(test_result["micro_recall"], 4))
print("micro_f1             :", round(test_result["micro_f1"], 4))
print("micro_f2             :", round(test_result["micro_f2"], 4))

print("\n==============================")
print("By Category")
print("==============================")
for key, score in test_result["by_category"].items():
    print(
        key,
        "| exact:", round(score["exact_match"], 4),
        "| P:", round(score["precision"], 4),
        "| R:", round(score["recall"], 4),
        "| F1:", round(score["f1"], 4),
        "| F2:", round(score["f2"], 4),
        "| TP:", score["tp"],
        "| FP:", score["fp"],
        "| FN:", score["fn"],
    )

KeyboardInterrupt:

In [10]:
# 틀린 예시 몇 개 시각적으로 보기
from IPython.display import display, Markdown


def show_diff_examples(result, count=3):
    examples = result["diff_examples"][:count]

    if not examples:
        display(Markdown("## 틀린 예시 없음"))
        return

    for ex in examples:
        rows = []

        for key in LABEL_CATS:
            pred_values = ex["pred"].get(key, [])
            gold_values = ex["gold"].get(key, [])

            pred_set = item_set(pred_values)
            gold_set = item_set(gold_values)

            status = "OK" if pred_set == gold_set else "DIFF"
            extra = sorted(pred_set - gold_set)
            missing = sorted(gold_set - pred_set)

            rows.append(
                "| {key} | {status} | `{pred}` | `{gold}` | `{extra}` | `{missing}` |".format(
                    key=key,
                    status=status,
                    pred=json.dumps(pred_values, ensure_ascii=False),
                    gold=json.dumps(gold_values, ensure_ascii=False),
                    extra=json.dumps(extra, ensure_ascii=False),
                    missing=json.dumps(missing, ensure_ascii=False),
                )
            )

        table = "\n".join([
            "| field | status | prediction | gold | extra_fp | missing_fn |",
            "|---|---:|---|---|---|---|",
            *rows,
        ])

        display(Markdown(f"## Test index `{ex['index']}`"))

        display(Markdown("### 입력"))
        display(Markdown(f"```json\n{ex['input']}\n```"))

        display(Markdown("### 모델 추론 원문"))
        display(Markdown(f"```text\n{ex['pred_raw']}\n```"))

        display(Markdown("### 필드별 비교"))
        display(Markdown(table))


show_diff_examples(test_result, count=3)

## Test index `6`

### 입력

```json
{"id": 66, "job_description_id": 112, "name": "심민서", "skill": ["vite", "react", "JS"], "education_level": {"final_degree": "bachelor", "bachelor": "동국대학교 전기전자공학부", "master": "", "doctoral": ""}, "experience": [{"company_name": "삼성전자", "length": "1년 3개월", "position": "팀장", "experience_description": "REST API 설계 및 구현"}, {"company_name": "배달의민족", "length": "4년 7개월", "position": "과장", "experience_description": "사내 웹 서비스 유지보수 및 기능 개발"}], "self_intoduction": [{"question": "본인의 성장 과정을 소개해 주세요.", "answer": "저는 부산에서 나고 자라 성장해 왔습니다. 맡은 일에 책임을 다하는 자세를 갖추고 있습니다."}, {"question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.", "answer": "동국대학교 정보통신공학과 재학 시절 고지호 교수님 연구실에서 프로젝트를 수행하며 팀원들과 의견 충돌을 겪었습니다. 갈등 상황에서 먼저 경청하고 데이터로 설득하는 방식을 택했습니다."}, {"question": "", "answer": ""}], "certification": ["정보처리기사", "ADsP"], "language": [{"language_name": "영어", "test_name": "TOEIC", "score": "935"}, {"language_name": "", "test_name": "", "score": ""}], "award": [{"award_name": "우수상", "award_from": "넥슨", "time": "2022-11-05"}], "training": [{"education_name": "", "education_from": "", "education_description": "", "start": "", "end": ""}], "other_activity": [{"activity_name": "", "activity_description": "", "start": "", "end": ""}], "reviewed": true, "reviewed_at": "2026-05-10T09:00:00", "created_at": "2026-05-01T09:00:00", "updated_at": "2026-05-10T09:00:00"}
```

### 모델 추론 원문

```text
```json
{
  "comp_name": ["삼성전자", "배달의민족", "넥슨"],
  "person_name": ["심민서", "고지훈"],
  "address": ["부산"],
  "personal_info": [],
  "school_edu": ["동국대학교 전기전자공학부"],
  "project_name": [],
  "jd_discrimination": []
}
```
```

### 필드별 비교

| field | status | prediction | gold | extra_fp | missing_fn |
|---|---:|---|---|---|---|
| comp_name | OK | `["삼성전자", "배달의민족", "넥슨"]` | `["삼성전자", "배달의민족", "넥슨"]` | `[]` | `[]` |
| person_name | DIFF | `["심민서", "고지훈"]` | `["심민서", "고지호"]` | `["고지훈"]` | `["고지호"]` |
| address | OK | `["부산"]` | `["부산"]` | `[]` | `[]` |
| personal_info | OK | `[]` | `[]` | `[]` | `[]` |
| school_edu | DIFF | `["동국대학교 전기전자공학부"]` | `["동국대학교 전기전자공학부", "동국대학교 정보통신공학과"]` | `[]` | `["동국대학교 정보통신공학과"]` |
| project_name | OK | `[]` | `[]` | `[]` | `[]` |
| jd_discrimination | OK | `[]` | `[]` | `[]` | `[]` |

## Test index `7`

### 입력

```json
{"id": 163, "job_description_id": 10, "name": "배예린", "skill": ["kubernetes", "JS", "node.js"], "education_level": {"final_degree": "bachelor", "bachelor": "연세대학교 데이터사이언스학과", "master": "", "doctoral": ""}, "experience": [{"company_name": "넥스트랩", "length": "1년 10개월", "position": "팀장", "experience_description": "사내 웹 서비스 유지보수 및 기능 개발"}, {"company_name": "당근마켓", "length": "5년 8개월", "position": "계약직", "experience_description": "결제 모듈 개발 및 안정화"}], "self_intoduction": [{"question": "본인의 성장 과정을 소개해 주세요.", "answer": "저는 장남으로서 책임감을 배우며 자랐고 색약이 있으나 업무 수행에 지장 없이 성장해 왔습니다. 맡은 일에 책임을 다하는 자세를 갖추고 있습니다."}, {"question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.", "answer": "고려대학교 컴퓨터공학부 재학 시절 류예준 교수님 연구실에서 프로젝트를 수행하며 팀원들과 의견 충돌을 겪었습니다. 이후 퀀텀에이아이에서 인턴으로 일하며 협업 프로세스를 배웠습니다. 갈등 상황에서 먼저 경청하고 데이터로 설득하는 방식을 택했습니다."}, {"question": "", "answer": ""}], "certification": [], "language": [{"language_name": "", "test_name": "", "score": ""}, {"language_name": "", "test_name": "", "score": ""}], "award": [{"award_name": "우수상", "award_from": "크래프톤", "time": "2022-11-05"}], "training": [{"education_name": "Family AI Camp", "education_from": "엘리스", "education_description": "팀 프로젝트 기반 실무 교육 수료", "start": "2024-03-01", "end": "2024-08-31"}], "other_activity": [{"activity_name": "", "activity_description": "", "start": "", "end": ""}], "reviewed": true, "reviewed_at": "2026-05-10T09:00:00", "created_at": "2026-05-01T09:00:00", "updated_at": "2026-05-10T09:00:00"}
```

### 모델 추론 원문

```text
```json
{
  "comp_name": ["넥스트랩", "당근마켓", "크래프톤"],
  "person_name": ["배예린", "류예준"],
  "address": [],
  "personal_info": ["장남", "색약"],
  "school_edu": ["연세대학교 데이터사이언스학과", "고려대학교 컴퓨터공학부", "엘리스"],
  "project_name": [],
  "jd_discrimination": []
}
```
```

### 필드별 비교

| field | status | prediction | gold | extra_fp | missing_fn |
|---|---:|---|---|---|---|
| comp_name | DIFF | `["넥스트랩", "당근마켓", "크래프톤"]` | `["넥스트랩", "당근마켓", "퀀텀에이아이", "크래프톤"]` | `[]` | `["퀀텀에이아이"]` |
| person_name | OK | `["배예린", "류예준"]` | `["배예린", "류예준"]` | `[]` | `[]` |
| address | OK | `[]` | `[]` | `[]` | `[]` |
| personal_info | OK | `["장남", "색약"]` | `["장남", "색약"]` | `[]` | `[]` |
| school_edu | OK | `["연세대학교 데이터사이언스학과", "고려대학교 컴퓨터공학부", "엘리스"]` | `["연세대학교 데이터사이언스학과", "고려대학교 컴퓨터공학부", "엘리스"]` | `[]` | `[]` |
| project_name | OK | `[]` | `[]` | `[]` | `[]` |
| jd_discrimination | OK | `[]` | `[]` | `[]` | `[]` |

## Test index `10`

### 입력

```json
{"id": 37, "job_description_id": 163, "name": "송지민", "skill": ["aws", "java", "react", "mysql", "spring", "redis"], "education_level": {"final_degree": "doctoral", "bachelor": "소프트웨어학과 학사", "master": "", "doctoral": ""}, "experience": [{"company_name": "한 중소 IT 기업", "length": "5년 1개월", "position": "과장", "experience_description": "결제 모듈 개발 및 안정화"}, {"company_name": "한 중소 IT 기업", "length": "5년 6개월", "position": "팀장", "experience_description": "데이터 파이프라인 구축"}], "self_intoduction": [{"question": "본인의 성장 과정을 소개해 주세요.", "answer": "저는 98년생이며 성장해 왔습니다. 맡은 일에 책임을 다하는 자세를 갖추고 있습니다."}, {"question": "지원 동기를 작성해 주세요.", "answer": "사용자 경험을 개선하는 ML 엔지니어 직무에 매력을 느껴 지원했습니다. 꾸준히 성장하며 팀에 기여하는 개발자가 되고 싶습니다."}, {"question": "", "answer": ""}], "certification": ["AWS SAA", "SQLD"], "language": [{"language_name": "영어", "test_name": "OPIc", "score": "IH"}, {"language_name": "", "test_name": "", "score": ""}], "award": [{"award_name": "", "award_from": "", "time": ""}], "training": [{"education_name": "", "education_from": "", "education_description": "", "start": "", "end": ""}], "other_activity": [{"activity_name": "", "activity_description": "", "start": "", "end": ""}], "reviewed": true, "reviewed_at": "2026-05-10T09:00:00", "created_at": "2026-05-01T09:00:00", "updated_at": "2026-05-10T09:00:00"}
```

### 모델 추론 원문

```text
```json
{
  "comp_name": [],
  "person_name": ["송지민"],
  "address": [],
  "personal_info": [],
  "school_edu": [],
  "project_name": [],
  "jd_discrimination": []
}
```
```

### 필드별 비교

| field | status | prediction | gold | extra_fp | missing_fn |
|---|---:|---|---|---|---|
| comp_name | OK | `[]` | `[]` | `[]` | `[]` |
| person_name | OK | `["송지민"]` | `["송지민"]` | `[]` | `[]` |
| address | OK | `[]` | `[]` | `[]` | `[]` |
| personal_info | DIFF | `[]` | `["98년생"]` | `[]` | `["98년생"]` |
| school_edu | OK | `[]` | `[]` | `[]` | `[]` |
| project_name | OK | `[]` | `[]` | `[]` | `[]` |
| jd_discrimination | OK | `[]` | `[]` | `[]` | `[]` |

In [ ]:
# 파싱 실패 예시 보기
def show_parse_fail_examples(result, count=3):
    examples = result["failed_examples"][:count]

    if not examples:
        display(Markdown("## JSON 파싱 실패 예시 없음"))
        return

    for ex in examples:
        display(Markdown(f"## Parse Fail index `{ex['index']}`"))

        display(Markdown("### 에러"))
        display(Markdown(f"```text\n{ex['error']}\n```"))

        display(Markdown("### 모델 추론 원문"))
        display(Markdown(f"```text\n{ex['pred_raw']}\n```"))

        display(Markdown("### 정답"))
        display(Markdown(f"```json\n{json.dumps(ex['gold'], ensure_ascii=False, indent=2)}\n```"))


show_parse_fail_examples(test_result, count=3)

각 필드의 list[str] 안 item이 정답과 같은지 비교

전체 micro precision / recall / F1

샘플 단위 exact match

필드별 exact match / precision / recall / F1

JSON 파싱 실패율

In [12]:
import json

test_original_ids = []

for i, sample in enumerate(test_dataset):
    input_obj = json.loads(sample["messages"][1]["content"])
    test_original_ids.append(input_obj.get("id"))

print(test_original_ids)

[367, 475, 166, 380, 356, 292, 66, 163, 205, 385, 37, 143, 188, 162, 262, 492, 122, 34, 208, 144, 451, 191, 486, 135, 347, 355, 391, 376, 81, 404, 325, 465, 384, 300, 264, 272, 366, 5, 53, 302, 316, 125, 103, 445, 132, 398, 453, 29, 306, 275, 251, 284, 477, 124, 491, 381, 100, 247, 216, 101, 145, 286, 410, 371, 433, 20, 428, 313, 499, 320, 93, 245, 395, 49, 228, 291, 278, 474, 41, 487, 334, 307, 233, 198, 3, 178, 176, 220, 69, 495, 218, 173, 255, 473, 80, 407, 235, 150, 411, 65]

In [13]:
# 학습 모델로 test 3번 데이터 추론 결과
idx = 3
sample = test_dataset[idx]

input_text = sample["messages"][1]["content"]
gold_text = sample["messages"][-1]["content"]
input_obj = json.loads(input_text)

ft_pred = predict_with_strict_prompt(input_text)

print("test_idx:", idx)
print("original_id:", input_obj.get("id"))
print("job_name:", input_obj.get("job_name"))

print("\n=== 입력 ===")
print(input_text)

print("\n=== 학습 모델 추론 원문 ===")
print(ft_pred)

print("\n=== 정답 원문 ===")
print(gold_text)

test_idx: 3
original_id: 380
job_name: QA 엔지니어 채용

=== 입력 ===
{"id": 380, "account_id": 239, "job_name": "QA 엔지니어 채용", "education_level": "초대졸 이상", "major": "컴퓨터공학 또는 관련 학과", "career_level": "경력무관", "required_skill": ["node.js", "JS", "typescript"], "preferred_skill": [], "main_task": "QA 엔지니어 업무 전반", "hiring_reason": "", "work_type": "계약직", "status": "closed", "created_at": "2026-04-01T09:00:00", "updated_at": "2026-04-15T09:00:00"}

=== 학습 모델 추론 원문 ===
```json
{
  "comp_name": [],
  "person_name": [],
  "address": [],
  "personal_info": [],
  "school_edu": [],
  "project_name": [],
  "jd_discrimination": []
}
```

=== 정답 원문 ===
{"comp_name": [], "person_name": [], "address": [], "personal_info": [], "school_edu": [], "project_name": [], "jd_discrimination": []}

# 추가 추론

In [18]:
import torch


# best checkpoint 모델 사용
best_model = trainer.model
best_model.eval()

if hasattr(best_model, "config"):
    best_model.config.use_cache = True

if tokenizer.pad_token_id is None:
    tokenizer.pad_token = tokenizer.eos_token


def predict_best_model(input_json_text, model=best_model, tokenizer=tokenizer):
    messages = [
        {
            "role": "system",
            "content": STRICT_SYSTEM_PROMPT,
        },
        {
            "role": "user",
            "content": input_json_text,
        },
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        add_special_tokens=False,
    ).to(next(model.parameters()).device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=512,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    generated = outputs[0][inputs["input_ids"].shape[-1]:]

    return tokenizer.decode(
        generated,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    ).strip()


def evaluate_best_model(dataset_to_eval, max_samples=None, show_progress=True):
    n = len(dataset_to_eval) if max_samples is None else min(len(dataset_to_eval), max_samples)

    total_tp = 0
    total_fp = 0
    total_fn = 0
    exact_match_count = 0
    parse_fail_count = 0

    for i in range(n):
        sample = dataset_to_eval[i]
        input_text = sample["messages"][1]["content"]
        gold_text = sample["messages"][-1]["content"]

        pred_raw = predict_best_model(input_text)
        gold = normalize_gold_json(gold_text)

        try:
            pred = parse_prediction_json(pred_raw)
        except Exception:
            parse_fail_count += 1
            pred = empty_masking_result()

        sample_exact = True

        for key in LABEL_CATS:
            pred_items = item_set(pred.get(key, []))
            gold_items = item_set(gold.get(key, []))

            tp = len(pred_items & gold_items)
            fp = len(pred_items - gold_items)
            fn = len(gold_items - pred_items)

            total_tp += tp
            total_fp += fp
            total_fn += fn

            if pred_items != gold_items:
                sample_exact = False

        if sample_exact:
            exact_match_count += 1

        if show_progress and (i + 1) % 10 == 0:
            print(f"evaluated {i + 1}/{n}")

    precision = safe_div(total_tp, total_tp + total_fp)
    recall = safe_div(total_tp, total_tp + total_fn)
    f1 = safe_div(2 * precision * recall, precision + recall)

    return {
        "samples": n,
        "parse_fail": parse_fail_count,
        "parse_success_rate": safe_div(n - parse_fail_count, n),
        "exact_match_accuracy": safe_div(exact_match_count, n),
        "micro_precision": precision,
        "micro_recall": recall,
        "micro_f1": f1,
    }


best_result = evaluate_best_model(test_dataset, show_progress=True)

print("\n==============================")
print("Best Checkpoint Test Metrics")
print("==============================")
print("best checkpoint      :", trainer.state.best_model_checkpoint)
print("best eval_loss       :", trainer.state.best_metric)
print("samples              :", best_result["samples"])
print("parse_fail           :", best_result["parse_fail"])
print("parse_success_rate   :", round(best_result["parse_success_rate"], 4))
print("exact_match_accuracy :", round(best_result["exact_match_accuracy"], 4))
print("micro_precision      :", round(best_result["micro_precision"], 4))
print("micro_recall         :", round(best_result["micro_recall"], 4))
print("micro_f1             :", round(best_result["micro_f1"], 4))

evaluated 10/100
evaluated 20/100
evaluated 30/100
evaluated 40/100
evaluated 50/100
evaluated 60/100
evaluated 70/100
evaluated 80/100
evaluated 90/100
evaluated 100/100

==============================
Best Checkpoint Test Metrics
==============================
best checkpoint      : ./exaone-masking-lora-622-epoch8-earlystop/checkpoint-190
best eval_loss       : 0.14071343839168549
samples              : 100
parse_fail           : 0
parse_success_rate   : 1.0
exact_match_accuracy : 0.7
micro_precision      : 0.9689
micro_recall         : 0.8947
micro_f1             : 0.9303

In [19]:
from IPython.display import display, Markdown
import json


def show_best_wrong_examples(dataset_to_eval, count=3, max_scan=None):
    shown = 0
    n = len(dataset_to_eval) if max_scan is None else min(len(dataset_to_eval), max_scan)

    for i in range(n):
        sample = dataset_to_eval[i]
        input_text = sample["messages"][1]["content"]
        gold_text = sample["messages"][-1]["content"]

        pred_raw = predict_best_model(input_text)
        gold = normalize_gold_json(gold_text)

        try:
            pred = parse_prediction_json(pred_raw)
            parse_ok = True
            parse_error = ""
        except Exception as e:
            pred = empty_masking_result()
            parse_ok = False
            parse_error = str(e)

        rows = []
        is_wrong = not parse_ok

        for key in LABEL_CATS:
            pred_values = pred.get(key, [])
            gold_values = gold.get(key, [])

            pred_set = item_set(pred_values)
            gold_set = item_set(gold_values)

            extra = sorted(pred_set - gold_set)
            missing = sorted(gold_set - pred_set)

            if extra or missing:
                is_wrong = True

            status = "OK" if not extra and not missing else "DIFF"

            rows.append(
                "| {key} | {status} | `{pred}` | `{gold}` | `{extra}` | `{missing}` |".format(
                    key=key,
                    status=status,
                    pred=json.dumps(pred_values, ensure_ascii=False),
                    gold=json.dumps(gold_values, ensure_ascii=False),
                    extra=json.dumps(extra, ensure_ascii=False),
                    missing=json.dumps(missing, ensure_ascii=False),
                )
            )

        if not is_wrong:
            continue

        table = "\n".join([
            "| field | status | prediction | gold | extra_fp | missing_fn |",
            "|---|---:|---|---|---|---|",
            *rows,
        ])

        display(Markdown(f"## Wrong Example {shown + 1} / Test index `{i}`"))

        display(Markdown("### 입력"))
        display(Markdown(f"```json\n{input_text}\n```"))

        display(Markdown("### Best Checkpoint 추론 원문"))
        display(Markdown(f"```text\n{pred_raw}\n```"))

        if not parse_ok:
            display(Markdown("### 파싱 오류"))
            display(Markdown(f"```text\n{parse_error}\n```"))

        display(Markdown("### 필드별 비교"))
        display(Markdown(table))

        shown += 1
        if shown >= count:
            break

    if shown == 0:
        display(Markdown("## 틀린 예시 없음"))


show_best_wrong_examples(test_dataset, count=3)

## Wrong Example 1 / Test index `6`

### 입력

```json
{"id": 66, "job_description_id": 112, "name": "심민서", "skill": ["vite", "react", "JS"], "education_level": {"final_degree": "bachelor", "bachelor": "동국대학교 전기전자공학부", "master": "", "doctoral": ""}, "experience": [{"company_name": "삼성전자", "length": "1년 3개월", "position": "팀장", "experience_description": "REST API 설계 및 구현"}, {"company_name": "배달의민족", "length": "4년 7개월", "position": "과장", "experience_description": "사내 웹 서비스 유지보수 및 기능 개발"}], "self_intoduction": [{"question": "본인의 성장 과정을 소개해 주세요.", "answer": "저는 부산에서 나고 자라 성장해 왔습니다. 맡은 일에 책임을 다하는 자세를 갖추고 있습니다."}, {"question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.", "answer": "동국대학교 정보통신공학과 재학 시절 고지호 교수님 연구실에서 프로젝트를 수행하며 팀원들과 의견 충돌을 겪었습니다. 갈등 상황에서 먼저 경청하고 데이터로 설득하는 방식을 택했습니다."}, {"question": "", "answer": ""}], "certification": ["정보처리기사", "ADsP"], "language": [{"language_name": "영어", "test_name": "TOEIC", "score": "935"}, {"language_name": "", "test_name": "", "score": ""}], "award": [{"award_name": "우수상", "award_from": "넥슨", "time": "2022-11-05"}], "training": [{"education_name": "", "education_from": "", "education_description": "", "start": "", "end": ""}], "other_activity": [{"activity_name": "", "activity_description": "", "start": "", "end": ""}], "reviewed": true, "reviewed_at": "2026-05-10T09:00:00", "created_at": "2026-05-01T09:00:00", "updated_at": "2026-05-10T09:00:00"}
```

### Best Checkpoint 추론 원문

```text
```json
{
  "comp_name": ["삼성전자", "배달의민족", "넥슨"],
  "person_name": ["심민서", "고지훈"],
  "address": ["부산"],
  "personal_info": [],
  "school_edu": ["동국대학교 전기전자공학부"],
  "project_name": [],
  "jd_discrimination": []
}
```
```

### 필드별 비교

| field | status | prediction | gold | extra_fp | missing_fn |
|---|---:|---|---|---|---|
| comp_name | OK | `["삼성전자", "배달의민족", "넥슨"]` | `["삼성전자", "배달의민족", "넥슨"]` | `[]` | `[]` |
| person_name | DIFF | `["심민서", "고지훈"]` | `["심민서", "고지호"]` | `["고지훈"]` | `["고지호"]` |
| address | OK | `["부산"]` | `["부산"]` | `[]` | `[]` |
| personal_info | OK | `[]` | `[]` | `[]` | `[]` |
| school_edu | DIFF | `["동국대학교 전기전자공학부"]` | `["동국대학교 전기전자공학부", "동국대학교 정보통신공학과"]` | `[]` | `["동국대학교 정보통신공학과"]` |
| project_name | OK | `[]` | `[]` | `[]` | `[]` |
| jd_discrimination | OK | `[]` | `[]` | `[]` | `[]` |

## Wrong Example 2 / Test index `7`

### 입력

```json
{"id": 163, "job_description_id": 10, "name": "배예린", "skill": ["kubernetes", "JS", "node.js"], "education_level": {"final_degree": "bachelor", "bachelor": "연세대학교 데이터사이언스학과", "master": "", "doctoral": ""}, "experience": [{"company_name": "넥스트랩", "length": "1년 10개월", "position": "팀장", "experience_description": "사내 웹 서비스 유지보수 및 기능 개발"}, {"company_name": "당근마켓", "length": "5년 8개월", "position": "계약직", "experience_description": "결제 모듈 개발 및 안정화"}], "self_intoduction": [{"question": "본인의 성장 과정을 소개해 주세요.", "answer": "저는 장남으로서 책임감을 배우며 자랐고 색약이 있으나 업무 수행에 지장 없이 성장해 왔습니다. 맡은 일에 책임을 다하는 자세를 갖추고 있습니다."}, {"question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.", "answer": "고려대학교 컴퓨터공학부 재학 시절 류예준 교수님 연구실에서 프로젝트를 수행하며 팀원들과 의견 충돌을 겪었습니다. 이후 퀀텀에이아이에서 인턴으로 일하며 협업 프로세스를 배웠습니다. 갈등 상황에서 먼저 경청하고 데이터로 설득하는 방식을 택했습니다."}, {"question": "", "answer": ""}], "certification": [], "language": [{"language_name": "", "test_name": "", "score": ""}, {"language_name": "", "test_name": "", "score": ""}], "award": [{"award_name": "우수상", "award_from": "크래프톤", "time": "2022-11-05"}], "training": [{"education_name": "Family AI Camp", "education_from": "엘리스", "education_description": "팀 프로젝트 기반 실무 교육 수료", "start": "2024-03-01", "end": "2024-08-31"}], "other_activity": [{"activity_name": "", "activity_description": "", "start": "", "end": ""}], "reviewed": true, "reviewed_at": "2026-05-10T09:00:00", "created_at": "2026-05-01T09:00:00", "updated_at": "2026-05-10T09:00:00"}
```

### Best Checkpoint 추론 원문

```text
```json
{
  "comp_name": ["넥스트랩", "당근마켓", "크래프톤"],
  "person_name": ["배예린", "류예준"],
  "address": [],
  "personal_info": ["장남", "색약"],
  "school_edu": ["연세대학교 데이터사이언스학과", "고려대학교 컴퓨터공학부", "엘리스"],
  "project_name": [],
  "jd_discrimination": []
}
```
```

### 필드별 비교

| field | status | prediction | gold | extra_fp | missing_fn |
|---|---:|---|---|---|---|
| comp_name | DIFF | `["넥스트랩", "당근마켓", "크래프톤"]` | `["넥스트랩", "당근마켓", "퀀텀에이아이", "크래프톤"]` | `[]` | `["퀀텀에이아이"]` |
| person_name | OK | `["배예린", "류예준"]` | `["배예린", "류예준"]` | `[]` | `[]` |
| address | OK | `[]` | `[]` | `[]` | `[]` |
| personal_info | OK | `["장남", "색약"]` | `["장남", "색약"]` | `[]` | `[]` |
| school_edu | OK | `["연세대학교 데이터사이언스학과", "고려대학교 컴퓨터공학부", "엘리스"]` | `["연세대학교 데이터사이언스학과", "고려대학교 컴퓨터공학부", "엘리스"]` | `[]` | `[]` |
| project_name | OK | `[]` | `[]` | `[]` | `[]` |
| jd_discrimination | OK | `[]` | `[]` | `[]` | `[]` |

## Wrong Example 3 / Test index `10`

### 입력

```json
{"id": 37, "job_description_id": 163, "name": "송지민", "skill": ["aws", "java", "react", "mysql", "spring", "redis"], "education_level": {"final_degree": "doctoral", "bachelor": "소프트웨어학과 학사", "master": "", "doctoral": ""}, "experience": [{"company_name": "한 중소 IT 기업", "length": "5년 1개월", "position": "과장", "experience_description": "결제 모듈 개발 및 안정화"}, {"company_name": "한 중소 IT 기업", "length": "5년 6개월", "position": "팀장", "experience_description": "데이터 파이프라인 구축"}], "self_intoduction": [{"question": "본인의 성장 과정을 소개해 주세요.", "answer": "저는 98년생이며 성장해 왔습니다. 맡은 일에 책임을 다하는 자세를 갖추고 있습니다."}, {"question": "지원 동기를 작성해 주세요.", "answer": "사용자 경험을 개선하는 ML 엔지니어 직무에 매력을 느껴 지원했습니다. 꾸준히 성장하며 팀에 기여하는 개발자가 되고 싶습니다."}, {"question": "", "answer": ""}], "certification": ["AWS SAA", "SQLD"], "language": [{"language_name": "영어", "test_name": "OPIc", "score": "IH"}, {"language_name": "", "test_name": "", "score": ""}], "award": [{"award_name": "", "award_from": "", "time": ""}], "training": [{"education_name": "", "education_from": "", "education_description": "", "start": "", "end": ""}], "other_activity": [{"activity_name": "", "activity_description": "", "start": "", "end": ""}], "reviewed": true, "reviewed_at": "2026-05-10T09:00:00", "created_at": "2026-05-01T09:00:00", "updated_at": "2026-05-10T09:00:00"}
```

### Best Checkpoint 추론 원문

```text
```json
{
  "comp_name": [],
  "person_name": ["송지민"],
  "address": [],
  "personal_info": [],
  "school_edu": [],
  "project_name": [],
  "jd_discrimination": []
}
```
```

### 필드별 비교

| field | status | prediction | gold | extra_fp | missing_fn |
|---|---:|---|---|---|---|
| comp_name | OK | `[]` | `[]` | `[]` | `[]` |
| person_name | OK | `["송지민"]` | `["송지민"]` | `[]` | `[]` |
| address | OK | `[]` | `[]` | `[]` | `[]` |
| personal_info | DIFF | `[]` | `["98년생"]` | `[]` | `["98년생"]` |
| school_edu | OK | `[]` | `[]` | `[]` | `[]` |
| project_name | OK | `[]` | `[]` | `[]` | `[]` |
| jd_discrimination | OK | `[]` | `[]` | `[]` | `[]` |