In [1]:
!pip install transformers==4.57.1 accelerate==1.14.0 sentencepiece==0.2.1 safetensors==0.8.0 huggingface_hub==0.36.2 langchain-huggingface==1.2.2 langchain-core==1.4.8

Collecting transformers==4.57.1
  Using cached transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Collecting accelerate==1.14.0
  Using cached accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Collecting sentencepiece==0.2.1
  Using cached sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting safetensors==0.8.0
  Using cached safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting huggingface_hub==0.36.2
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Collecting langchain-huggingface==1.2.2
  Using cached langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)
Collecting langchain-core==1.4.8
  Using cached langchain_core-1.4.8-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (3.20.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (6.0.3)
Collecting regex!=2019.12.17 (from transformers==4.57.1)
  Using cached regex-2026.6.28-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.32.5)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers==4.57.1)
  Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting tqdm>=4.27 (from transformers==4.57.1)
  Using cached tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.36.2) (2024.6.1)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface_hub==0.36.2)
  Using cached hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.36.2) (4.15.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate==1.14.0) (7.1.0)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate==1.14.0) (2.8.0+cu128)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core==1.4.8)
  Using cached jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-protocol>=0.0.17 (from langchain-core==1.4.8)
  Using cached langchain_protocol-0.0.18-py3-none-any.whl.metadata (2.4 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core==1.4.8)
  Using cached langsmith-0.9.7-py3-none-any.whl.metadata (22 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain-core==1.4.8)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain-core==1.4.8)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core==1.4.8)
  Using cached uuid_utils-0.16.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core==1.4.8) (3.0.0)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (4.11.0)
Requirement already satisfied: distro>=1.7.0 in /usr/lib/python3/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (0.28.1)
Collecting orjson>=3.9.14 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (1.3.1)
Collecting websockets>=15.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached websockets-16.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.8 kB)
Collecting xxhash>=3.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached xxhash-3.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (0.16.0)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain-core==1.4.8)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.7.4->langchain-core==1.4.8)
  Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain-core==1.4.8)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate==1.14.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate==1.14.0) (3.0.3)
Using cached transformers-4.57.1-py3-none-any.whl (12.0 MB)
Using cached huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
Using cached accelerate-1.14.0-py3-none-any.whl (389 kB)
Using cached sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
Using cached safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (516 kB)
Using cached langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)
Using cached langchain_core-1.4.8-py3-none-any.whl (557 kB)
Using cached hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Using cached langsmith-0.9.7-py3-none-any.whl (671 kB)
Using cached pydantic-2.13.4-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Using cached uuid_utils-0.16.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (323 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached langchain_protocol-0.0.18-py3-none-any.whl (7.2 kB)
Using cached orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (134 kB)
Using cached regex-2026.6.28-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Using cached tqdm-4.68.3-py3-none-any.whl (78 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached websockets-16.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (184 kB)
Using cached xxhash-3.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (220 kB)
Using cached zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
Installing collected packages: zstandard, xxhash, websockets, uuid-utils, typing-inspection, tqdm, tenacity, sentencepiece, safetensors, regex, pydantic-core, orjson, langchain-protocol, jsonpatch, hf-xet, annotated-types, requests-toolbelt, pydantic, huggingface_hub, tokenizers, langsmith, transformers, langchain-core, accelerate, langchain-huggingface
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25/25 [langchain-huggingface]lerate]ore]]t]
Successfully installed accelerate-1.14.0 annotated-types-0.7.0 hf-xet-1.5.1 huggingface_hub-0.36.2 jsonpatch-1.33 langchain-core-1.4.8 langchain-huggingface-1.2.2 langchain-protocol-0.0.18 langsmith-0.9.7 orjson-3.11.9 pydantic-2.13.4 pydantic-core-2.46.4 regex-2026.6.28 requests-toolbelt-1.0.0 safetensors-0.8.0 sentencepiece-0.2.1 tenacity-9.1.4 tokenizers-0.22.2 tqdm-4.68.3 transformers-4.57.1 typing-inspection-0.4.2 uuid-utils-0.16.2 websockets-16.0 xxhash-3.8.0 zstandard-0.25.0

In [2]:
!pip install hf_transfer

Collecting hf_transfer
  Using cached hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Using cached hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
Installing collected packages: hf_transfer
Successfully installed hf_transfer-0.1.9

In [3]:
!pip install -U datasets peft trl accelerate bitsandbytes "transformers==4.57.1"

Collecting datasets
  Using cached datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Collecting peft
  Using cached peft-0.19.1-py3-none-any.whl.metadata (15 kB)
Collecting trl
  Using cached trl-1.7.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Collecting bitsandbytes
  Using cached bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: transformers==4.57.1 in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2026.6.28)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (4.68.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (4.15.0)
Collecting pyarrow>=21.0.0 (from datasets)
  Using cached pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets)
  Using cached pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.0)
Collecting multiprocess<0.70.20 (from datasets)
  Using cached multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached aiohttp-3.14.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (7.1.0)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.8.0+cu128)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached propcache-0.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached yarl-1.24.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (94 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Using cached datasets-5.0.0-py3-none-any.whl (555 kB)
Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Using cached multiprocess-0.70.19-py312-none-any.whl (150 kB)
Using cached peft-0.19.1-py3-none-any.whl (680 kB)
Using cached trl-1.7.1-py3-none-any.whl (842 kB)
Using cached bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
Using cached aiohttp-3.14.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
Using cached multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (256 kB)
Using cached yarl-1.24.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (105 kB)
Using cached aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (242 kB)
Using cached propcache-0.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (61 kB)
Using cached pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
Using cached pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Installing collected packages: pyarrow, propcache, multidict, frozenlist, dill, aiohappyeyeballs, yarl, pandas, multiprocess, aiosignal, aiohttp, bitsandbytes, peft, datasets, trl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/15 [trl]32m14/15 [trl]sets]tes]
Successfully installed aiohappyeyeballs-2.7.1 aiohttp-3.14.1 aiosignal-1.4.0 bitsandbytes-0.49.2 datasets-5.0.0 dill-0.4.1 frozenlist-1.8.0 multidict-6.7.1 multiprocess-0.70.19 pandas-3.0.3 peft-0.19.1 propcache-0.5.2 pyarrow-24.0.0 trl-1.7.1 yarl-1.24.2

In [4]:
pip install -U transformers accelerate bitsandbytes

Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (4.57.1)
Collecting transformers
  Using cached transformers-5.13.0-py3-none-any.whl.metadata (32 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Collecting huggingface-hub<2.0,>=1.5.0 (from transformers)
  Using cached huggingface_hub-1.22.0-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers) (2.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers) (2026.6.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.22.2)
Collecting typer (from transformers)
  Using cached typer-0.26.8-py3-none-any.whl.metadata (15 kB)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers) (0.8.0)
Requirement already satisfied: tqdm>=4.60 in /usr/local/lib/python3.12/dist-packages (from transformers) (4.68.3)
Collecting click<9.0.0,>=8.4.2 (from huggingface-hub<2.0,>=1.5.0->transformers)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.20.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate) (7.1.0)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate) (2.8.0+cu128)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate) (3.0.3)
Collecting shellingham>=1.3.0 (from typer->transformers)
  Using cached shellingham-1.5.4-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting rich>=13.8.0 (from typer->transformers)
  Using cached rich-15.0.0-py3-none-any.whl.metadata (18 kB)
Collecting annotated-doc>=0.0.2 (from typer->transformers)
  Using cached annotated_doc-0.0.4-py3-none-any.whl.metadata (6.6 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=13.8.0->typer->transformers)
  Using cached markdown_it_py-4.2.0-py3-none-any.whl.metadata (7.4 kB)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers) (2.19.2)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers)
  Using cached mdurl-0.1.2-py3-none-any.whl.metadata (1.6 kB)
Using cached transformers-5.13.0-py3-none-any.whl (11.5 MB)
Using cached huggingface_hub-1.22.0-py3-none-any.whl (765 kB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Using cached typer-0.26.8-py3-none-any.whl (122 kB)
Using cached annotated_doc-0.0.4-py3-none-any.whl (5.3 kB)
Using cached rich-15.0.0-py3-none-any.whl (310 kB)
Using cached markdown_it_py-4.2.0-py3-none-any.whl (91 kB)
Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
Installing collected packages: shellingham, mdurl, click, annotated-doc, markdown-it-py, rich, huggingface-hub, typer, transformers
  Attempting uninstall: huggingface-hub╺━━━━━━━━━━━━━━━━━ 5/9 [rich]own-it-py]
    Found existing installation: huggingface_hub 0.36.2━━━━━━━ 5/9 [rich]
    Uninstalling huggingface_hub-0.36.2:91m╸━━━━━━━━━━━━━ 6/9 [huggingface-hub]
      Successfully uninstalled huggingface_hub-0.36.2━━━━━━━━━ 6/9 [huggingface-hub]
  Attempting uninstall: transformers━━━╺━━━━━━━━ 7/9 [typer]gface-hub]
    Found existing installation: transformers 4.57.10m━━━━━━━━ 7/9 [typer]
    Uninstalling transformers-4.57.1:━━━━━━╸━━━━ 8/9 [transformers]
      Successfully uninstalled transformers-4.57.1[0m━━━━ 8/9 [transformers]
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9/9 [transformers][0m [transformers]
Successfully installed annotated-doc-0.0.4 click-8.4.2 huggingface-hub-1.22.0 markdown-it-py-4.2.0 mdurl-0.1.2 rich-15.0.0 shellingham-1.5.4 transformers-5.13.0 typer-0.26.8
Note: you may need to restart the kernel to use updated packages.

In [1]:
import os
from huggingface_hub import login

hf_token = os.environ.get("HF_TOKEN")

if hf_token is None:
    raise ValueError(
        "HF_TOKEN 환경변수가 없습니다. RunPod Secrets에 HF_TOKEN을 등록했는지 확인하세요."
    )

login(token=hf_token)

print("Hugging Face login completed.")

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Hugging Face login completed.

In [2]:
import json
from collections import Counter

from datasets import load_dataset


JSONL_PATH = "masking_train_500.jsonl"

LABEL_CATS = [
    "comp_name",
    "person_name",
    "address",
    "personal_info",
    "school_edu",
    "project_name",
    "jd_discrimination",
]


def _assistant_text(example):
    for message in reversed(example["messages"]):
        if message.get("role") == "assistant":
            return message.get("content", "")
    return ""


def add_strata(example):
    label = example.get("label")

    if isinstance(label, dict):
        clean = all(not label.get(category) for category in LABEL_CATS)
    else:
        try:
            obj = json.loads(_assistant_text(example))
            clean = all(not obj.get(category) for category in LABEL_CATS)
        except Exception:
            clean = False

    return {
        "strata": "clean" if clean else "sensitive"
    }


dataset = load_dataset(
    "json",
    data_files={"train": JSONL_PATH},
)["train"]

dataset = dataset.map(add_strata)
dataset = dataset.class_encode_column("strata")

names = dataset.features["strata"].names
print("total size:", len(dataset))
print("total strata:", Counter(names[i] for i in dataset["strata"]))

total size: 500
total strata: Counter({'sensitive': 400, 'clean': 100})

In [3]:
from collections import Counter
import json


OUTPUT_DIR = "./exaone-masking-lora-622-epoch8-earlystop"

LABEL_CATS = [
    "comp_name",
    "person_name",
    "address",
    "personal_info",
    "school_edu",
    "project_name",
    "jd_discrimination",
]


format_instructions = """
{
  "comp_name": [],
  "person_name": [],
  "address": [],
  "personal_info": [],
  "school_edu": [],
  "project_name": [],
  "jd_discrimination": []
}
""".strip()


STRICT_SYSTEM_PROMPT = f"""
당신은 한국 채용 데이터의 개인정보 마스킹 전문가입니다.
입력으로 들어온 자유 텍스트(자기소개서, 채용공고(JD) 본문, 회사 소개,
채용 사유, 메모 등)에서 "마스킹이 필요한 표현"을 찾아
아래 7개 카테고리로 분류하여 추출하세요.

[마스킹 카테고리]
1. comp_name        : 회사/기관/고객사/이전 근무처 등 조직 식별명
2. person_name      : 지원자 본인 및 제3자(교수·추천인·동료 등)의 실명
3. address          : 주소 및 출신·거주 지역
4. personal_info    : 고유식별정보·연락처·차별위험정보·민감정보
5. school_edu       : 학교/교육기관/주최기관명
6. project_name     : 내부·제3자 정보가 포함될 수 있는 프로젝트 실명
7. jd_discrimination: JD 내 차별 소지 조항

[출력 규칙]
- 반드시 JSON object 하나만 출력한다.
- 첫 글자는 반드시 {{ 로 시작하고 마지막 글자는 반드시 }} 로 끝난다.
- 코드블록, 코드펜스, ```json, ``` 를 절대 사용하지 않는다.
- 설명, 해설, 마크다운, 리스트 단독 출력, 번역, 영어 변환을 절대 하지 않는다.
- 입력 텍스트에 등장한 원문 표현 그대로 추출한다.
- 동일 표현은 한 번만 넣는다.
- 해당 카테고리에 없으면 빈 리스트 []를 넣는다.
- 키는 반드시 아래 JSON 스키마의 7개만 사용한다.

[출력 형식]
{format_instructions}
""".strip()


def force_system_prompt(messages, include_answer=True):
    new_messages = []

    source_messages = list(messages)
    if not include_answer and source_messages and source_messages[-1].get("role") == "assistant":
        source_messages = source_messages[:-1]

    has_system = source_messages and source_messages[0].get("role") == "system"

    if has_system:
        new_messages.append({
            "role": "system",
            "content": STRICT_SYSTEM_PROMPT,
        })
        new_messages.extend(source_messages[1:])
    else:
        new_messages.append({
            "role": "system",
            "content": STRICT_SYSTEM_PROMPT,
        })
        new_messages.extend(source_messages)

    return new_messages


# 1차 split: test 20%
split_1 = dataset.train_test_split(
    test_size=0.2,
    seed=42,
    stratify_by_column="strata",
)

train_val_dataset = split_1["train"]
test_dataset_raw = split_1["test"]

# 2차 split: 남은 80% 중 validation 25% = 전체 기준 20%
split_2 = train_val_dataset.train_test_split(
    test_size=0.25,
    seed=42,
    stratify_by_column="strata",
)

train_dataset_raw = split_2["train"]
eval_dataset_raw = split_2["test"]

names = dataset.features["strata"].names

print("train strata:", Counter(names[i] for i in train_dataset_raw["strata"]))
print("val   strata:", Counter(names[i] for i in eval_dataset_raw["strata"]))
print("test  strata:", Counter(names[i] for i in test_dataset_raw["strata"]))

remove_cols = ["strata"] + (["label"] if "label" in dataset.column_names else [])

train_dataset = train_dataset_raw.remove_columns(remove_cols)
eval_dataset = eval_dataset_raw.remove_columns(remove_cols)
test_dataset = test_dataset_raw.remove_columns(remove_cols)

print("train size:", len(train_dataset))
print("val size  :", len(eval_dataset))
print("test size :", len(test_dataset))
print("output dir:", OUTPUT_DIR)

train strata: Counter({'sensitive': 240, 'clean': 60})
val   strata: Counter({'sensitive': 80, 'clean': 20})
test  strata: Counter({'sensitive': 80, 'clean': 20})
train size: 300
val size  : 100
test size : 100
output dir: ./exaone-masking-lora-622-epoch8-earlystop

In [4]:
# Cell 6-1A. Oversampling repeat=4 버전

from collections import Counter
import json

OUTPUT_DIR = "./exaone-masking-lora-oversample-r4"

NUM_TRAIN_EPOCHS = 8
PER_DEVICE_TRAIN_BATCH_SIZE = 1
GRADIENT_ACCUMULATION_STEPS = 8

def get_gold_obj_from_sample(sample):
    obj = json.loads(sample["messages"][-1]["content"])
    return {
        key: obj.get(key, []) if isinstance(obj.get(key, []), list) else []
        for key in LABEL_CATS
    }

CATEGORY_RECALL_WEIGHTS = {
    "comp_name": 1,
    "person_name": 2,
    "address": 2,
    "personal_info": 3,
    "school_edu": 1,
    "project_name": 1,
    "jd_discrimination": 3,
}

repeat_indices = []
repeat_counter = Counter()
category_counter = Counter()

for idx, sample in enumerate(train_dataset):
    gold = get_gold_obj_from_sample(sample)
    total_items = sum(len(v) for v in gold.values())

    repeat = 1

    if total_items > 0:
        repeat += 1

    if total_items >= 3:
        repeat += 1

    for category, weight in CATEGORY_RECALL_WEIGHTS.items():
        if len(gold.get(category, [])) > 0:
            repeat += weight
            category_counter[category] += 1

    repeat = min(repeat, 4)

    repeat_indices.extend([idx] * repeat)
    repeat_counter[repeat] += 1

train_dataset_for_run = train_dataset.select(repeat_indices).shuffle(seed=42)

print("\n==============================")
print("Version A Dataset Summary")
print("==============================")
print("mode                  : oversampling repeat=4")
print("original train size   :", len(train_dataset))
print("oversampled train size:", len(train_dataset_for_run))
print("val size              :", len(eval_dataset))
print("test size             :", len(test_dataset))
print("oversampling ratio    :", round(len(train_dataset_for_run) / len(train_dataset), 2))
print("repeat dist           :", repeat_counter)
print("positive categories   :", category_counter)
print("==============================")

==============================
Version A Dataset Summary
==============================
mode                  : oversampling repeat=4
original train size   : 300
oversampled train size: 1006
val size              : 100
test size             : 100
oversampling ratio    : 3.35
repeat dist           : Counter({4: 226, 1: 60, 3: 14})
positive categories   : Counter({'comp_name': 181, 'person_name': 181, 'school_edu': 128, 'personal_info': 108, 'project_name': 93, 'address': 77, 'jd_discrimination': 19})
==============================

In [5]:
import inspect
import sys
import types
from typing import TypedDict

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig
from transformers import EarlyStoppingCallback
from peft import LoraConfig, prepare_model_for_kbit_training
from trl import SFTTrainer, SFTConfig


MODEL_NAME = "LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct"

if "OUTPUT_DIR" not in globals():
    OUTPUT_DIR = "./exaone-masking-lora-622-epoch8-earlystop"


# ---------------------------------------------------------------- transformers / EXAONE compatibility patches

try:
    import transformers.modeling_rope_utils as _rope_utils

    if not hasattr(_rope_utils, "RopeParameters"):
        class RopeParameters(TypedDict, total=False):
            rope_type: str
            factor: float
            low_freq_factor: float
            high_freq_factor: float
            original_max_position_embeddings: int
            attention_factor: float
            beta_fast: float
            beta_slow: float
            short_factor: list[float]
            long_factor: list[float]

        _rope_utils.RopeParameters = RopeParameters
        print("[PATCH] Added missing transformers.modeling_rope_utils.RopeParameters shim.")
except Exception as e:
    print(f"[PATCH][WARN] RopeParameters shim skipped: {e}")


try:
    import transformers.integrations as _tf_integrations

    def _noop_kernel_patch(*args, **kwargs):
        if args and callable(args[0]) and len(args) == 1:
            return args[0]

        def _decorator(fn):
            return fn

        return _decorator

    for _name in (
        "use_kernel_forward_from_hub",
        "use_kernel_func_from_hub",
        "use_kernelized_func",
    ):
        if not hasattr(_tf_integrations, _name):
            setattr(_tf_integrations, _name, _noop_kernel_patch)
            print(f"[PATCH] Added missing transformers.integrations.{_name} shim.")
except Exception as e:
    print(f"[PATCH][WARN] integrations shim skipped: {e}")


def _patch_exaone(model):
    if hasattr(model, "_exaone_compat_patched") and model._exaone_compat_patched:
        return model

    if hasattr(model, "transformer") and hasattr(model.transformer, "wte"):
        embed = model.transformer.wte
    elif hasattr(model, "transformer") and hasattr(model.transformer, "embed_tokens"):
        embed = model.transformer.embed_tokens
    elif hasattr(model, "model") and hasattr(model.model, "embed_tokens"):
        embed = model.model.embed_tokens
    else:
        raise AttributeError(
            "embedding layer not found. Check model structure.\n" + str(model)
        )

    model.get_input_embeddings = lambda: embed
    model.set_input_embeddings = lambda v: setattr(embed, "weight", v.weight)

    import transformers.masking_utils as masking_utils

    original_create_causal_mask = masking_utils.create_causal_mask
    original_params = inspect.signature(original_create_causal_mask).parameters

    def _create_causal_mask_compat(*args, **kwargs):
        if "input_embeds" in kwargs and "input_embeds" not in original_params:
            value = kwargs.pop("input_embeds")
            if "inputs_embeds" in original_params:
                kwargs["inputs_embeds"] = value
            elif "input_tensor" in original_params:
                kwargs["input_tensor"] = value
            else:
                kwargs["input_ids"] = value
        elif "inputs_embeds" in kwargs and "inputs_embeds" not in original_params:
            value = kwargs.pop("inputs_embeds")
            if "input_embeds" in original_params:
                kwargs["input_embeds"] = value
            elif "input_tensor" in original_params:
                kwargs["input_tensor"] = value
            else:
                kwargs["input_ids"] = value

        accepts_var_kwargs = any(
            p.kind == inspect.Parameter.VAR_KEYWORD
            for p in original_params.values()
        )

        if not accepts_var_kwargs:
            kwargs = {
                key: value
                for key, value in kwargs.items()
                if key in original_params
            }

        return original_create_causal_mask(*args, **kwargs)

    masking_utils.create_causal_mask = _create_causal_mask_compat

    for module in list(sys.modules.values()):
        if module is None or not hasattr(module, "create_causal_mask"):
            continue
        if getattr(module, "create_causal_mask", None) is original_create_causal_mask:
            setattr(module, "create_causal_mask", _create_causal_mask_compat)

    backbone = getattr(model, "transformer", None) or getattr(model, "model", None)

    if backbone is not None and not hasattr(backbone, "_exaone_forward_patched"):
        original_forward = backbone.forward

        def _patched_forward(self, *args, **kwargs):
            if "input_embeds" in kwargs and "inputs_embeds" not in kwargs:
                kwargs["inputs_embeds"] = kwargs.pop("input_embeds")
            return original_forward(*args, **kwargs)

        backbone.forward = types.MethodType(_patched_forward, backbone)
        backbone._exaone_forward_patched = True

    model._exaone_compat_patched = True
    print("[PATCH] EXAONE embedding + create_causal_mask compatibility patch applied.")
    return model


# ---------------------------------------------------------------- tokenizer

if "tokenizer" not in globals():
    tokenizer = AutoTokenizer.from_pretrained(
        MODEL_NAME,
        trust_remote_code=True,
    )

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

tokenizer.padding_side = "right"


# ---------------------------------------------------------------- model load for QLoRA

if "model" not in globals():
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )

    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    )
    print("[LOAD] 4bit base model loaded.")
else:
    print("[LOAD] Reusing existing model.")

model.config.use_cache = False
model = _patch_exaone(model)

# CheckpointError 방지를 위해 gradient checkpointing 명시적으로 비활성화
if hasattr(model, "gradient_checkpointing_disable"):
    model.gradient_checkpointing_disable()

if not hasattr(model, "_kbit_training_prepared"):
    model = prepare_model_for_kbit_training(
        model,
        use_gradient_checkpointing=False,
    )
    model._kbit_training_prepared = True
    print("[PATCH] prepare_model_for_kbit_training applied without gradient checkpointing.")

if hasattr(model, "gradient_checkpointing_disable"):
    model.gradient_checkpointing_disable()


# ---------------------------------------------------------------- formatting + LoRA + Trainer

def formatting_func(example):
    messages = force_system_prompt(example["messages"], include_answer=True)

    return tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False,
    )


lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=[
        "q_proj", "k_proj", "v_proj",
        "out_proj",
        "c_fc_0", "c_fc_1", "c_proj",
    ],
)


training_args = SFTConfig(
    output_dir=OUTPUT_DIR,
    num_train_epochs=NUM_TRAIN_EPOCHS,

    per_device_train_batch_size=PER_DEVICE_TRAIN_BATCH_SIZE,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=2e-4,

    logging_strategy="epoch",
    eval_strategy="epoch",
    save_strategy="epoch",

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    save_total_limit=3,
    gradient_checkpointing=False,

    report_to="none",
    disable_tqdm=False,

    bf16=True,
    max_length=4096,
    packing=False,
)


trainer = SFTTrainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset_for_run,
    eval_dataset=eval_dataset,
    peft_config=lora_config,
    formatting_func=formatting_func,
    processing_class=tokenizer,
    callbacks=[
        EarlyStoppingCallback(
            early_stopping_patience=2,
            early_stopping_threshold=0.0,
        )
    ],
)


# print("=== 학습 전 Validation Eval Loss ===")
# initial_eval = trainer.evaluate()
# print(f"initial eval_loss: {initial_eval['eval_loss']:.4f}")

trainer.train()

print("\n========================")
print("Best Checkpoint")
print("========================")
print("checkpoint:", trainer.state.best_model_checkpoint)
print("eval_loss :", trainer.state.best_metric)

print("\n=== Best 모델 기준 Validation Eval Loss ===")
final_eval = trainer.evaluate()
print(f"final eval_loss: {final_eval['eval_loss']:.4f}")

trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"\n최종(best) Adapter 저장 완료: {OUTPUT_DIR}")

[transformers] The `check_model_inputs` decorator is deprecated in favor of `merge_with_config_defaults`.

[ERROR] `cache_position` is part of ExaoneModel.forward's signature, but not documented. Make sure to add it to the docstring of the function in /workspace/.cache/huggingface/modules/transformers_modules/LGAI_hyphen_EXAONE/EXAONE_hyphen_3_dot_5_hyphen_2_dot_4B_hyphen_Instruct/ccce25bd39c141fe053e0bc75818a8f5fe962802/modeling_exaone.py.
[ERROR] `cache_position` is part of ExaoneForCausalLM.forward's signature, but not documented. Make sure to add it to the docstring of the function in /workspace/.cache/huggingface/modules/transformers_modules/LGAI_hyphen_EXAONE/EXAONE_hyphen_3_dot_5_hyphen_2_dot_4B_hyphen_Instruct/ccce25bd39c141fe053e0bc75818a8f5fe962802/modeling_exaone.py.

Loading weights:   0%|          | 0/272 [00:00<?, ?it/s]

[LOAD] 4bit base model loaded.

/tmp/ipykernel_1530/1685272044.py:125: UserWarning: Torchaudio's I/O functions now support per-call backend dispatch. Importing backend implementation directly is no longer guaranteed to work. Please use `backend` keyword with load/save/info function, instead of calling the underlying implementation directly.
  if module is None or not hasattr(module, "create_causal_mask"):

[PATCH] EXAONE embedding + create_causal_mask compatibility patch applied.
[PATCH] prepare_model_for_kbit_training applied without gradient checkpointing.

========================
Best Checkpoint
========================
checkpoint: ./exaone-masking-lora-oversample-r4/checkpoint-126
eval_loss : 0.14824339747428894

=== Best 모델 기준 Validation Eval Loss ===

final eval_loss: 0.1482

최종(best) Adapter 저장 완료: ./exaone-masking-lora-oversample-r4

# best 모델로 추론하는 함수

In [6]:
import torch


inference_model = trainer.model
inference_model.eval()

if hasattr(inference_model, "config"):
    inference_model.config.use_cache = True

if tokenizer.pad_token_id is None:
    tokenizer.pad_token = tokenizer.eos_token


def predict_with_strict_prompt(input_json_text, model=inference_model, tokenizer=tokenizer):
    messages = [
        {
            "role": "system",
            "content": STRICT_SYSTEM_PROMPT,
        },
        {
            "role": "user",
            "content": input_json_text,
        },
    ]

    prompt = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

    device = next(model.parameters()).device

    inputs = tokenizer(
        prompt,
        return_tensors="pt",
        add_special_tokens=False,
    ).to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=512,
            do_sample=False,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    generated = outputs[0][inputs["input_ids"].shape[-1]:]

    return tokenizer.decode(
        generated,
        skip_special_tokens=True,
        clean_up_tokenization_spaces=False,
    ).strip()

# 평가

In [10]:
import re
import json
from collections import defaultdict


LABEL_CATS = [
    "comp_name",
    "person_name",
    "address",
    "personal_info",
    "school_edu",
    "project_name",
    "jd_discrimination",
]


def empty_masking_result():
    return {key: [] for key in LABEL_CATS}


def parse_prediction_json(text):
    text = text.strip()

    # 코드펜스 제거
    text = re.sub(r"^```(?:json)?\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    # 앞뒤에 ], | 같은 쓰레기 토큰이 붙어도 JSON object만 추출
    first = text.find("{")
    last = text.rfind("}")

    if first == -1 or last == -1 or first >= last:
        raise ValueError(f"JSON object를 찾지 못했습니다: {text}")

    text = text[first:last + 1]

    obj = json.loads(text)

    if not isinstance(obj, dict):
        return empty_masking_result()

    return {
        key: obj.get(key, []) if isinstance(obj.get(key, []), list) else []
        for key in LABEL_CATS
    }


def normalize_gold_json(text):
    obj = json.loads(text)

    return {
        key: obj.get(key, []) if isinstance(obj.get(key, []), list) else []
        for key in LABEL_CATS
    }


def item_set(values):
    return set(
        str(value).strip()
        for value in values
        if str(value).strip()
    )


def safe_div(num, den):
    return num / den if den else 0.0


def fbeta_score(precision, recall, beta=2):
    beta_sq = beta ** 2
    return safe_div(
        (1 + beta_sq) * precision * recall,
        (beta_sq * precision) + recall,
    )


def evaluate_field_items(dataset_to_eval, max_samples=None, show_progress=True):
    n = len(dataset_to_eval) if max_samples is None else min(len(dataset_to_eval), max_samples)

    total_tp = 0
    total_fp = 0
    total_fn = 0

    exact_match_count = 0
    parse_fail_count = 0

    by_category = {
        key: {"tp": 0, "fp": 0, "fn": 0, "exact": 0}
        for key in LABEL_CATS
    }

    failed_examples = []
    diff_examples = []

    for i in range(n):
        sample = dataset_to_eval[i]
        input_text = sample["messages"][1]["content"]
        gold_text = sample["messages"][-1]["content"]

        pred_raw = predict_with_strict_prompt(input_text)
        gold = normalize_gold_json(gold_text)

        try:
            pred = parse_prediction_json(pred_raw)
        except Exception as e:
            parse_fail_count += 1
            pred = empty_masking_result()

            if len(failed_examples) < 5:
                failed_examples.append({
                    "index": i,
                    "error": str(e),
                    "pred_raw": pred_raw,
                    "gold": gold,
                })

        sample_exact = True

        for key in LABEL_CATS:
            pred_items = item_set(pred.get(key, []))
            gold_items = item_set(gold.get(key, []))

            tp = len(pred_items & gold_items)
            fp = len(pred_items - gold_items)
            fn = len(gold_items - pred_items)

            by_category[key]["tp"] += tp
            by_category[key]["fp"] += fp
            by_category[key]["fn"] += fn

            total_tp += tp
            total_fp += fp
            total_fn += fn

            if pred_items == gold_items:
                by_category[key]["exact"] += 1
            else:
                sample_exact = False

        if sample_exact:
            exact_match_count += 1
        elif len(diff_examples) < 5:
            diff_examples.append({
                "index": i,
                "input": input_text,
                "pred_raw": pred_raw,
                "pred": pred,
                "gold": gold,
            })

        if show_progress and (i + 1) % 10 == 0:
            print(f"evaluated {i + 1}/{n}")

    micro_precision = safe_div(total_tp, total_tp + total_fp)
    micro_recall = safe_div(total_tp, total_tp + total_fn)
    micro_f1 = safe_div(2 * micro_precision * micro_recall, micro_precision + micro_recall)
    micro_f2 = fbeta_score(micro_precision, micro_recall, beta=2)

    result = {
        "samples": n,
        "parse_fail": parse_fail_count,
        "parse_success_rate": safe_div(n - parse_fail_count, n),
        "exact_match_accuracy": safe_div(exact_match_count, n),
        "micro_precision": micro_precision,
        "micro_recall": micro_recall,
        "micro_f1": micro_f1,
        "micro_f2": micro_f2,
        "by_category": {},
        "failed_examples": failed_examples,
        "diff_examples": diff_examples,
    }

    for key, counts in by_category.items():
        tp = counts["tp"]
        fp = counts["fp"]
        fn = counts["fn"]

        precision = safe_div(tp, tp + fp)
        recall = safe_div(tp, tp + fn)
        f1 = safe_div(2 * precision * recall, precision + recall)
        f2 = fbeta_score(precision, recall, beta=2)

        result["by_category"][key] = {
            "precision": precision,
            "recall": recall,
            "f1": f1,
            "f2": f2,
            "exact_match": safe_div(counts["exact"], n),
            "tp": tp,
            "fp": fp,
            "fn": fn,
        }

    return result

In [11]:
# test_dataset 평가 실행
test_result = evaluate_field_items(test_dataset, show_progress=True)

print("\n==============================")
print("Overall Metrics")
print("==============================")
print("samples              :", test_result["samples"])
print("parse_fail           :", test_result["parse_fail"])
print("parse_success_rate   :", round(test_result["parse_success_rate"], 4))
print("exact_match_accuracy :", round(test_result["exact_match_accuracy"], 4))
print("micro_precision      :", round(test_result["micro_precision"], 4))
print("micro_recall         :", round(test_result["micro_recall"], 4))
print("micro_f1             :", round(test_result["micro_f1"], 4))
print("micro_f2             :", round(test_result["micro_f2"], 4))

print("\n==============================")
print("By Category")
print("==============================")
for key, score in test_result["by_category"].items():
    print(
        key,
        "| exact:", round(score["exact_match"], 4),
        "| P:", round(score["precision"], 4),
        "| R:", round(score["recall"], 4),
        "| F1:", round(score["f1"], 4),
        "| F2:", round(score["f2"], 4),
        "| TP:", score["tp"],
        "| FP:", score["fp"],
        "| FN:", score["fn"],
    )

evaluated 10/100
evaluated 20/100
evaluated 30/100
evaluated 40/100
evaluated 50/100
evaluated 60/100
evaluated 70/100
evaluated 80/100
evaluated 90/100
evaluated 100/100

==============================
Overall Metrics
==============================
samples              : 100
parse_fail           : 0
parse_success_rate   : 1.0
exact_match_accuracy : 0.73
micro_precision      : 0.9587
micro_recall         : 0.945
micro_f1             : 0.9518
micro_f2             : 0.9477

==============================
By Category
==============================
comp_name | exact: 0.88 | P: 0.9362 | R: 0.9706 | F1: 0.9531 | F2: 0.9635 | TP: 132 | FP: 9 | FN: 4
person_name | exact: 0.99 | P: 0.9857 | R: 0.9857 | F1: 0.9857 | F2: 0.9857 | TP: 69 | FP: 1 | FN: 1
address | exact: 1.0 | P: 1.0 | R: 1.0 | F1: 1.0 | F2: 1.0 | TP: 25 | FP: 0 | FN: 0
personal_info | exact: 0.95 | P: 0.9492 | R: 0.9032 | F1: 0.9256 | F2: 0.9121 | TP: 56 | FP: 3 | FN: 6
school_edu | exact: 0.92 | P: 0.9494 | R: 0.9494 | F1: 0.9494 | F2: 0.9494 | TP: 75 | FP: 4 | FN: 4
project_name | exact: 1.0 | P: 1.0 | R: 1.0 | F1: 1.0 | F2: 1.0 | TP: 36 | FP: 0 | FN: 0
jd_discrimination | exact: 0.95 | P: 1.0 | R: 0.2 | F1: 0.3333 | F2: 0.2381 | TP: 2 | FP: 0 | FN: 8