In [1]:
!pip install transformers==4.57.1 accelerate==1.14.0 sentencepiece==0.2.1 safetensors==0.8.0 huggingface_hub==0.36.2 langchain-huggingface==1.2.2 langchain-core==1.4.8

Collecting transformers==4.57.1
  Using cached transformers-4.57.1-py3-none-any.whl.metadata (43 kB)
Collecting accelerate==1.14.0
  Using cached accelerate-1.14.0-py3-none-any.whl.metadata (19 kB)
Collecting sentencepiece==0.2.1
  Using cached sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (10 kB)
Collecting safetensors==0.8.0
  Using cached safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (4.2 kB)
Collecting huggingface_hub==0.36.2
  Using cached huggingface_hub-0.36.2-py3-none-any.whl.metadata (15 kB)
Collecting langchain-huggingface==1.2.2
  Using cached langchain_huggingface-1.2.2-py3-none-any.whl.metadata (4.0 kB)
Collecting langchain-core==1.4.8
  Using cached langchain_core-1.4.8-py3-none-any.whl.metadata (4.7 kB)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (3.20.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (6.0.3)
Collecting regex!=2019.12.17 (from transformers==4.57.1)
  Using cached regex-2026.6.28-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (40 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.32.5)
Collecting tokenizers<=0.23.0,>=0.22.0 (from transformers==4.57.1)
  Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.3 kB)
Collecting tqdm>=4.27 (from transformers==4.57.1)
  Using cached tqdm-4.68.3-py3-none-any.whl.metadata (57 kB)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.36.2) (2024.6.1)
Collecting hf-xet<2.0.0,>=1.1.3 (from huggingface_hub==0.36.2)
  Using cached hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface_hub==0.36.2) (4.15.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate==1.14.0) (7.1.0)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate==1.14.0) (2.8.0+cu128)
Collecting jsonpatch<2.0.0,>=1.33.0 (from langchain-core==1.4.8)
  Using cached jsonpatch-1.33-py2.py3-none-any.whl.metadata (3.0 kB)
Collecting langchain-protocol>=0.0.17 (from langchain-core==1.4.8)
  Using cached langchain_protocol-0.0.18-py3-none-any.whl.metadata (2.4 kB)
Collecting langsmith<1.0.0,>=0.3.45 (from langchain-core==1.4.8)
  Downloading langsmith-0.9.7-py3-none-any.whl.metadata (22 kB)
Collecting pydantic<3.0.0,>=2.7.4 (from langchain-core==1.4.8)
  Using cached pydantic-2.13.4-py3-none-any.whl.metadata (109 kB)
Collecting tenacity!=8.4.0,<10.0.0,>=8.1.0 (from langchain-core==1.4.8)
  Using cached tenacity-9.1.4-py3-none-any.whl.metadata (1.2 kB)
Collecting uuid-utils<1.0,>=0.12.0 (from langchain-core==1.4.8)
  Using cached uuid_utils-0.16.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.4 kB)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core==1.4.8) (3.0.0)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (4.11.0)
Requirement already satisfied: distro>=1.7.0 in /usr/lib/python3/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (0.28.1)
Collecting orjson>=3.9.14 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (41 kB)
Collecting requests-toolbelt>=1.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (1.3.1)
Collecting websockets>=15.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached websockets-16.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (6.8 kB)
Collecting xxhash>=3.0.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached xxhash-3.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (14 kB)
Collecting zstandard>=0.23.0 (from langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8)
  Using cached zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (3.3 kB)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.3.45->langchain-core==1.4.8) (0.16.0)
Collecting annotated-types>=0.6.0 (from pydantic<3.0.0,>=2.7.4->langchain-core==1.4.8)
  Using cached annotated_types-0.7.0-py3-none-any.whl.metadata (15 kB)
Collecting pydantic-core==2.46.4 (from pydantic<3.0.0,>=2.7.4->langchain-core==1.4.8)
  Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting typing-inspection>=0.4.2 (from pydantic<3.0.0,>=2.7.4->langchain-core==1.4.8)
  Using cached typing_inspection-0.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (2.5.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate==1.14.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate==1.14.0) (3.0.3)
Using cached transformers-4.57.1-py3-none-any.whl (12.0 MB)
Using cached huggingface_hub-0.36.2-py3-none-any.whl (566 kB)
Using cached accelerate-1.14.0-py3-none-any.whl (389 kB)
Using cached sentencepiece-0.2.1-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (1.4 MB)
Using cached safetensors-0.8.0-cp310-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (516 kB)
Using cached langchain_huggingface-1.2.2-py3-none-any.whl (31 kB)
Using cached langchain_core-1.4.8-py3-none-any.whl (557 kB)
Using cached hf_xet-1.5.1-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.5 MB)
Using cached jsonpatch-1.33-py2.py3-none-any.whl (12 kB)
Downloading langsmith-0.9.7-py3-none-any.whl (671 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 671.1/671.1 kB 3.2 MB/s  0:00:00
Using cached pydantic-2.13.4-py3-none-any.whl (472 kB)
Using cached pydantic_core-2.46.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached tenacity-9.1.4-py3-none-any.whl (28 kB)
Using cached tokenizers-0.22.2-cp39-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.3 MB)
Using cached uuid_utils-0.16.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (323 kB)
Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
Using cached langchain_protocol-0.0.18-py3-none-any.whl (7.2 kB)
Using cached orjson-3.11.9-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (134 kB)
Using cached regex-2026.6.28-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (801 kB)
Using cached requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
Using cached tqdm-4.68.3-py3-none-any.whl (78 kB)
Using cached typing_inspection-0.4.2-py3-none-any.whl (14 kB)
Using cached websockets-16.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (184 kB)
Using cached xxhash-3.8.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (220 kB)
Using cached zstandard-0.25.0-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (5.5 MB)
Installing collected packages: zstandard, xxhash, websockets, uuid-utils, typing-inspection, tqdm, tenacity, sentencepiece, safetensors, regex, pydantic-core, orjson, langchain-protocol, jsonpatch, hf-xet, annotated-types, requests-toolbelt, pydantic, huggingface_hub, tokenizers, langsmith, transformers, langchain-core, accelerate, langchain-huggingface
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25/25 [langchain-huggingface]lerate]ore]]
Successfully installed accelerate-1.14.0 annotated-types-0.7.0 hf-xet-1.5.1 huggingface_hub-0.36.2 jsonpatch-1.33 langchain-core-1.4.8 langchain-huggingface-1.2.2 langchain-protocol-0.0.18 langsmith-0.9.7 orjson-3.11.9 pydantic-2.13.4 pydantic-core-2.46.4 regex-2026.6.28 requests-toolbelt-1.0.0 safetensors-0.8.0 sentencepiece-0.2.1 tenacity-9.1.4 tokenizers-0.22.2 tqdm-4.68.3 transformers-4.57.1 typing-inspection-0.4.2 uuid-utils-0.16.2 websockets-16.0 xxhash-3.8.0 zstandard-0.25.0

In [2]:
!pip install hf_transfer

Collecting hf_transfer
  Using cached hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (1.7 kB)
Using cached hf_transfer-0.1.9-cp38-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
Installing collected packages: hf_transfer
Successfully installed hf_transfer-0.1.9

In [3]:
!pip install -U datasets peft trl accelerate bitsandbytes "transformers==4.57.1"

Collecting datasets
  Using cached datasets-5.0.0-py3-none-any.whl.metadata (23 kB)
Collecting peft
  Using cached peft-0.19.1-py3-none-any.whl.metadata (15 kB)
Collecting trl
  Using cached trl-1.7.0-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: accelerate in /usr/local/lib/python3.12/dist-packages (1.14.0)
Collecting bitsandbytes
  Using cached bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl.metadata (10 kB)
Requirement already satisfied: transformers==4.57.1 in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2026.6.28)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (4.68.3)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (4.15.0)
Collecting pyarrow>=21.0.0 (from datasets)
  Using cached pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl.metadata (3.0 kB)
Collecting dill<0.4.2,>=0.3.0 (from datasets)
  Using cached dill-0.4.1-py3-none-any.whl.metadata (10 kB)
Collecting pandas (from datasets)
  Using cached pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Requirement already satisfied: httpx<1.0.0 in /usr/local/lib/python3.12/dist-packages (from datasets) (0.28.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.12/dist-packages (from datasets) (3.8.0)
Collecting multiprocess<0.70.20 (from datasets)
  Using cached multiprocess-0.70.19-py312-none-any.whl.metadata (7.5 kB)
Collecting aiohttp!=4.0.0a0,!=4.0.0a1 (from fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached aiohttp-3.14.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (8.3 kB)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (4.11.0)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (2025.10.5)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1.0.0->datasets) (3.10)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0.0->datasets) (0.16.0)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from peft) (7.1.0)
Requirement already satisfied: torch>=1.13.0 in /usr/local/lib/python3.12/dist-packages (from peft) (2.8.0+cu128)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from trl) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.3)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.13.0->peft) (3.4.0)
Collecting aiohappyeyeballs>=2.5.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached aiohappyeyeballs-2.7.1-py3-none-any.whl.metadata (5.9 kB)
Collecting aiosignal>=1.4.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached aiosignal-1.4.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets) (25.4.0)
Collecting frozenlist>=1.1.1 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl.metadata (20 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting propcache>=0.2.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached propcache-0.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (16 kB)
Collecting yarl<2.0,>=1.17.0 (from aiohttp!=4.0.0a0,!=4.0.0a1->fsspec[http]<=2026.4.0,>=2023.1.0->datasets)
  Using cached yarl-1.24.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl.metadata (94 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (3.4.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (2.5.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.13.0->peft) (1.3.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from anyio->httpx<1.0.0->datasets) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->trl) (3.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->datasets) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /usr/lib/python3/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Using cached datasets-5.0.0-py3-none-any.whl (555 kB)
Using cached dill-0.4.1-py3-none-any.whl (120 kB)
Using cached multiprocess-0.70.19-py312-none-any.whl (150 kB)
Using cached peft-0.19.1-py3-none-any.whl (680 kB)
Using cached trl-1.7.0-py3-none-any.whl (838 kB)
Using cached bitsandbytes-0.49.2-py3-none-manylinux_2_24_x86_64.whl (60.7 MB)
Using cached aiohttp-3.14.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (1.8 MB)
Using cached multidict-6.7.1-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (256 kB)
Using cached yarl-1.24.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (105 kB)
Using cached aiohappyeyeballs-2.7.1-py3-none-any.whl (15 kB)
Using cached aiosignal-1.4.0-py3-none-any.whl (7.5 kB)
Using cached frozenlist-1.8.0-cp312-cp312-manylinux1_x86_64.manylinux_2_28_x86_64.manylinux_2_5_x86_64.whl (242 kB)
Using cached propcache-0.5.2-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.manylinux_2_28_x86_64.whl (61 kB)
Using cached pyarrow-24.0.0-cp312-cp312-manylinux_2_28_x86_64.whl (48.9 MB)
Using cached pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
Installing collected packages: pyarrow, propcache, multidict, frozenlist, dill, aiohappyeyeballs, yarl, pandas, multiprocess, aiosignal, aiohttp, bitsandbytes, peft, datasets, trl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15/15 [trl]32m14/15 [trl]sets]tes]
Successfully installed aiohappyeyeballs-2.7.1 aiohttp-3.14.1 aiosignal-1.4.0 bitsandbytes-0.49.2 datasets-5.0.0 dill-0.4.1 frozenlist-1.8.0 multidict-6.7.1 multiprocess-0.70.19 pandas-3.0.3 peft-0.19.1 propcache-0.5.2 pyarrow-24.0.0 trl-1.7.0 yarl-1.24.2

In [4]:
# Cell 1. 평가/분할용 추가 패키지
!pip install -U pandas scikit-learn sentence-transformers rouge-score tqdm

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (3.0.3)
Collecting scikit-learn
  Using cached scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (11 kB)
Collecting sentence-transformers
  Using cached sentence_transformers-5.6.0-py3-none-any.whl.metadata (18 kB)
Collecting rouge-score
  Using cached rouge_score-0.1.2-py3-none-any.whl
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (4.68.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Collecting scipy>=1.10.0 (from scikit-learn)
  Using cached scipy-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn)
  Using cached narwhals-2.23.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.57.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (0.36.2)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.8.0+cu128)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.15.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (3.20.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2026.6.28)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Collecting absl-py (from rouge-score)
  Using cached absl_py-2.4.0-py3-none-any.whl.metadata (3.3 kB)
Collecting nltk (from rouge-score)
  Using cached nltk-3.9.4-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: six>=1.14.0 in /usr/lib/python3/dist-packages (from rouge-score) (1.16.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Collecting click (from nltk->rouge-score)
  Using cached click-8.4.2-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.10.5)
Using cached scikit_learn-1.9.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (9.1 MB)
Using cached sentence_transformers-5.6.0-py3-none-any.whl (596 kB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached narwhals-2.23.0-py3-none-any.whl (458 kB)
Using cached scipy-1.18.0-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (35.3 MB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Using cached absl_py-2.4.0-py3-none-any.whl (135 kB)
Using cached nltk-3.9.4-py3-none-any.whl (1.6 MB)
Using cached click-8.4.2-py3-none-any.whl (119 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, joblib, click, absl-py, scikit-learn, nltk, rouge-score, sentence-transformers
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10/10 [sentence-transformers]ence-transformers]
Successfully installed absl-py-2.4.0 click-8.4.2 joblib-1.5.3 narwhals-2.23.0 nltk-3.9.4 rouge-score-0.1.2 scikit-learn-1.9.0 scipy-1.18.0 sentence-transformers-5.6.0 threadpoolctl-3.6.0

In [5]:
!pip install -U "transformers==4.57.1" "accelerate==1.14.0" bitsandbytes

Requirement already satisfied: transformers==4.57.1 in /usr/local/lib/python3.12/dist-packages (4.57.1)
Requirement already satisfied: accelerate==1.14.0 in /usr/local/lib/python3.12/dist-packages (1.14.0)
Requirement already satisfied: bitsandbytes in /usr/local/lib/python3.12/dist-packages (0.49.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (3.20.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.36.2)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.1.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (25.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2026.6.28)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (2.32.5)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.22.2)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.12/dist-packages (from transformers==4.57.1) (4.68.3)
Requirement already satisfied: psutil in /usr/local/lib/python3.12/dist-packages (from accelerate==1.14.0) (7.1.0)
Requirement already satisfied: torch>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from accelerate==1.14.0) (2.8.0+cu128)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (2024.6.1)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (1.5.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers==4.57.1) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (80.9.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.1.6)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.93)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.8.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.3.83 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (11.3.3.83)
Requirement already satisfied: nvidia-curand-cu12==10.3.9.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (10.3.9.90)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.3.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (11.7.3.90)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.5.8.93)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.8.90 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.90)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.8.93 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (12.8.93)
Requirement already satisfied: nvidia-cufile-cu12==1.13.1.3 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (1.13.1.3)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=2.0.0->accelerate==1.14.0) (3.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=2.0.0->accelerate==1.14.0) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=2.0.0->accelerate==1.14.0) (3.0.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (3.4.3)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->transformers==4.57.1) (2025.10.5)

In [1]:
import os
from huggingface_hub import login

hf_token = os.environ.get("HF_TOKEN")

if hf_token is None:
    raise ValueError(
        "HF_TOKEN 환경변수가 없습니다. RunPod Secrets에 HF_TOKEN을 등록했는지 확인하세요."
    )

login(token=hf_token)

print("Hugging Face login completed.")

Note: Environment variable`HF_TOKEN` is set and is the current active token independently from the token you've just configured.

Hugging Face login completed.

In [15]:
# Cell 2. 기본 설정

import os
import re
import gc
import json
import random
import numpy as np
import pandas as pd
import torch

from pathlib import Path
from tqdm.auto import tqdm

SEED = 42
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# RunPod/Colab 환경에 맞게 수정
DATA_PATH = "/workspace/self_intro_star_dataset.jsonl"

# # 예시. 사용하려는 EXAONE 모델로 바꿔도 됨
# MODEL_ID = "LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct"

# # 최신 main은 Transformers v5용 코드라 transformers 4.x와 충돌할 수 있음
# # 2024-12-11 commit: v5 업데이트 이전 revision
# MODEL_REVISION = "e949c91"

# Cell 2 쪽 설정에 추가

MODEL_ID = "LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct"

# 이전에 정상 로드됐던 EXAONE revision
MODEL_REVISION = "e949c91dec92095908d34e6b560af77dd0c993f8"

WORK_DIR = Path("./exaone_self_intro_star")
WORK_DIR.mkdir(parents=True, exist_ok=True)

SPLIT_DIR = WORK_DIR / "splits"
SPLIT_DIR.mkdir(parents=True, exist_ok=True)

PRED_DIR = WORK_DIR / "predictions"
PRED_DIR.mkdir(parents=True, exist_ok=True)

ADAPTER_DIR = WORK_DIR / "exaone_star_lora"

In [3]:
# Cell 3. JSONL 로드

def load_jsonl(path):
    rows = []
    with open(path, "r", encoding="utf-8-sig") as f:
        for i, line in enumerate(f, start=1):
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError as e:
                raise ValueError(f"{i}번째 줄 JSON 파싱 실패: {e}")
    return rows

rows = load_jsonl(DATA_PATH)
df = pd.DataFrame(rows)

required_cols = {"label", "role", "input", "output"}
missing = required_cols - set(df.columns)
if missing:
    raise ValueError(f"필수 컬럼 누락: {missing}")

df["label"] = df["label"].astype(int)
df["role"] = df["role"].astype(str)
df["strata"] = df["label"].astype(str) + "||" + df["role"]

print("전체 데이터 수:", len(df))
print("label 분포")
display(df["label"].value_counts().sort_index())

print("role 수:", df["role"].nunique())
print("label+role strata 수:", df["strata"].nunique())
display(df.groupby(["label", "role"]).size().rename("count").reset_index().head())

전체 데이터 수: 500
label 분포

label
0     75
1    350
2     75
Name: count, dtype: int64

role 수: 10
label+role strata 수: 30

   label                    role  count
0      0     AI 엔지니어 / 머신러닝 엔지니어     15
1      0  DevOps 엔지니어 / 인프라 엔지니어      8
2      0      QA 엔지니어 / 테스트 엔지니어      4
3      0             게임·그래픽스 개발자      3
4      0      데이터 엔지니어 / 데이터 분석가      4

In [4]:
# Cell 4. label + role 기준 stratified 6:2:2 split
# sklearn train_test_split은 작은 strata에서 2차 split이 실패할 수 있어 직접 분배합니다.

def allocate_counts(n, ratios=(0.6, 0.2, 0.2)):
    ideal = np.array(ratios) * n
    counts = np.floor(ideal).astype(int)
    remain = n - counts.sum()

    order = np.argsort(-(ideal - counts))
    for idx in order[:remain]:
        counts[idx] += 1

    # strata 샘플이 3개 이상이면 train/val/test에 최소 1개씩 배치
    if n >= 3:
        for idx in range(3):
            if counts[idx] == 0:
                donor = int(np.argmax(counts))
                counts[donor] -= 1
                counts[idx] += 1

    return counts.tolist()  # train, val, test

def stratified_split_602020(df, strata_col="strata", seed=42):
    rng = np.random.default_rng(seed)

    train_idx, val_idx, test_idx = [], [], []

    small = df.groupby(strata_col).size()
    too_small = small[small < 3]
    if len(too_small) > 0:
        print("주의: 샘플이 3개 미만인 strata는 6:2:2를 완전히 보장할 수 없습니다.")
        display(too_small)

    for _, group in df.groupby(strata_col, sort=False):
        idx = group.index.to_numpy().copy()
        rng.shuffle(idx)

        n_train, n_val, n_test = allocate_counts(len(idx))

        train_idx.extend(idx[:n_train])
        val_idx.extend(idx[n_train:n_train+n_val])
        test_idx.extend(idx[n_train+n_val:n_train+n_val+n_test])

    train_df = df.loc[train_idx].sample(frac=1, random_state=seed).reset_index(drop=True)
    val_df = df.loc[val_idx].sample(frac=1, random_state=seed).reset_index(drop=True)
    test_df = df.loc[test_idx].sample(frac=1, random_state=seed).reset_index(drop=True)

    return train_df, val_df, test_df

train_df, val_df, test_df = stratified_split_602020(df, "strata", SEED)

print(len(train_df), len(val_df), len(test_df))
print("비율:", len(train_df)/len(df), len(val_df)/len(df), len(test_df)/len(df))

for name, part in [("train", train_df), ("val", val_df), ("test", test_df)]:
    part.drop(columns=["strata"]).to_json(
        SPLIT_DIR / f"{name}.jsonl",
        orient="records",
        lines=True,
        force_ascii=False,
    )

display(pd.DataFrame({
    "all": df["label"].value_counts(normalize=True).sort_index(),
    "train": train_df["label"].value_counts(normalize=True).sort_index(),
    "val": val_df["label"].value_counts(normalize=True).sort_index(),
    "test": test_df["label"].value_counts(normalize=True).sort_index(),
}))

298 106 96
비율: 0.596 0.212 0.192

        all     train       val      test
label
0      0.15  0.144295  0.169811  0.145833
1      0.70  0.704698  0.679245  0.708333
2      0.15  0.151007  0.150943  0.145833

In [5]:
# Cell 5. 프롬프트 / 출력 포맷 함수

SYSTEM_PROMPT = """너는 자기소개서 답변을 STAR 구조로 변환하는 평가/작성 보조 모델이다.
반드시 JSON만 출력한다. 설명, 마크다운, 코드블록은 출력하지 않는다.
출력 key는 학습 데이터와 동일하게 self_intoduction, original_quality를 사용한다.
self_intoduction의 각 항목은 question과 answer를 포함하고, answer는 s, t, a, r을 포함한다."""

def build_messages(example):
    payload = {
        "role": example["role"],
        "input": example["input"],
    }

    user_prompt = f"""다음 JSON을 읽고 정답 output과 같은 구조의 JSON만 생성하라.

입력:
{json.dumps(payload, ensure_ascii=False)}

출력 JSON 스키마:
{{
  "self_intoduction": [
    {{
      "question": "...",
      "answer": {{
        "s": "...",
        "t": "...",
        "a": "...",
        "r": "..."
      }}
    }}
  ],
  "original_quality": "..."
}}"""

    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": user_prompt},
    ]

def target_text(example):
    return json.dumps(example["output"], ensure_ascii=False)

# base 평가용

In [16]:
# Cell 6. 모델/토크나이저 로드 - base 평가용

from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

def get_torch_dtype():
    if torch.cuda.is_available() and torch.cuda.is_bf16_supported():
        return torch.bfloat16
    return torch.float16

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=get_torch_dtype(),
    bnb_4bit_use_double_quant=True,
)

tokenizer = AutoTokenizer.from_pretrained(
    MODEL_ID,
    revision=MODEL_REVISION,
    trust_remote_code=True,
    use_fast=True,
)

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    revision=MODEL_REVISION,
    code_revision=MODEL_REVISION,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=get_torch_dtype(),
    trust_remote_code=True,
)

model.eval()
print("loaded:", MODEL_ID, MODEL_REVISION)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

loaded: LGAI-EXAONE/EXAONE-3.5-2.4B-Instruct e949c91dec92095908d34e6b560af77dd0c993f8

In [17]:
# Cell 7. 미니배치 generation 함수

from pathlib import Path

tokenizer.padding_side = "left"

if tokenizer.pad_token is None:
    tokenizer.pad_token = tokenizer.eos_token

model.config.use_cache = True

def build_prompt(example):
    messages = build_messages(example)
    return tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=True,
    )

def generate_batch(
    model,
    tokenizer,
    examples,
    max_new_tokens=800,
    max_input_tokens=2048,
):
    prompts = [build_prompt(ex) for ex in examples]

    inputs = tokenizer(
        prompts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=max_input_tokens,
    ).to(model.device)

    with torch.inference_mode():
        output_ids = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            use_cache=True,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    prompt_len = inputs["input_ids"].shape[1]
    generated = output_ids[:, prompt_len:]

    return [
        tokenizer.decode(ids, skip_special_tokens=True).strip()
        for ids in generated
    ]

def run_generation(
    model,
    tokenizer,
    data_df,
    output_path,
    batch_size=4,
    max_new_tokens=800,
    max_input_tokens=2048,
    resume=True,
):
    output_path = Path(output_path)
    records = []

    if resume and output_path.exists():
        with open(output_path, "r", encoding="utf-8") as f:
            records = [json.loads(line) for line in f if line.strip()]
        print(f"기존 예측 {len(records)}개 발견. 이어서 진행합니다.")

    start = len(records)

    with open(output_path, "a", encoding="utf-8") as f:
        for batch_start in tqdm(range(start, len(data_df), batch_size)):
            batch_df = data_df.iloc[batch_start:batch_start + batch_size]
            examples = [row.to_dict() for _, row in batch_df.iterrows()]

            preds = generate_batch(
                model=model,
                tokenizer=tokenizer,
                examples=examples,
                max_new_tokens=max_new_tokens,
                max_input_tokens=max_input_tokens,
            )

            for ex, pred in zip(examples, preds):
                record = {
                    "label": ex["label"],
                    "role": ex["role"],
                    "input": ex["input"],
                    "reference_output": ex["output"],
                    "prediction_text": pred,
                }
                records.append(record)
                f.write(json.dumps(record, ensure_ascii=False) + "\n")

            f.flush()

    return pd.DataFrame(records)

In [18]:
# Cell 8. 평가 함수

from rouge_score import rouge_scorer
from sentence_transformers import SentenceTransformer

def extract_json_object(text):
    if not isinstance(text, str):
        return None

    text = text.strip()
    text = re.sub(r"^```json\s*", "", text)
    text = re.sub(r"^```\s*", "", text)
    text = re.sub(r"\s*```$", "", text)

    start = text.find("{")
    if start < 0:
        return None

    depth = 0
    in_str = False
    esc = False

    for i in range(start, len(text)):
        ch = text[i]

        if in_str:
            if esc:
                esc = False
            elif ch == "\\":
                esc = True
            elif ch == '"':
                in_str = False
        else:
            if ch == '"':
                in_str = True
            elif ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    return text[start:i+1]

    return None

def parse_prediction(text):
    obj_text = extract_json_object(text)
    if obj_text is None:
        return None
    try:
        return json.loads(obj_text)
    except Exception:
        return None

def schema_valid(obj):
    if not isinstance(obj, dict):
        return False
    if "self_intoduction" not in obj:
        return False
    if "original_quality" not in obj:
        return False
    if not isinstance(obj["self_intoduction"], list):
        return False

    for item in obj["self_intoduction"]:
        if not isinstance(item, dict):
            return False
        if "question" not in item or "answer" not in item:
            return False
        ans = item["answer"]
        if not isinstance(ans, dict):
            return False
        for k in ["s", "t", "a", "r"]:
            if k not in ans:
                return False

    return True

def flatten_output(obj):
    if not isinstance(obj, dict):
        return ""

    parts = []

    for item in obj.get("self_intoduction", []):
        if not isinstance(item, dict):
            continue

        parts.append(str(item.get("question", "")))

        ans = item.get("answer", {})
        if isinstance(ans, dict):
            for k in ["s", "t", "a", "r"]:
                parts.append(str(ans.get(k, "")))
        else:
            parts.append(str(ans))

    parts.append(str(obj.get("original_quality", "")))
    return "\n".join([p for p in parts if p])

def flatten_field(obj, field):
    if not isinstance(obj, dict):
        return ""

    parts = []

    if field == "original_quality":
        return str(obj.get("original_quality", ""))

    for item in obj.get("self_intoduction", []):
        ans = item.get("answer", {}) if isinstance(item, dict) else {}
        if isinstance(ans, dict):
            parts.append(str(ans.get(field, "")))

    return "\n".join([p for p in parts if p])

rouge = rouge_scorer.RougeScorer(["rougeL"], use_stemmer=False)

# 한국어/다국어 의미 유사도용. 더 큰 모델로 바꿔도 됨.
embedder = SentenceTransformer("sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2")

def evaluate_prediction_df(pred_df):
    rows = []

    parsed_preds = [parse_prediction(x) for x in pred_df["prediction_text"]]
    ref_objs = pred_df["reference_output"].tolist()

    ref_texts = [flatten_output(x) for x in ref_objs]
    pred_texts = [flatten_output(x) if x is not None else "" for x in parsed_preds]

    ref_emb = embedder.encode(ref_texts, batch_size=16, normalize_embeddings=True, convert_to_numpy=True)
    pred_emb = embedder.encode(pred_texts, batch_size=16, normalize_embeddings=True, convert_to_numpy=True)
    semantic_sims = (ref_emb * pred_emb).sum(axis=1)

    for i, row in pred_df.reset_index(drop=True).iterrows():
        ref_obj = ref_objs[i]
        pred_obj = parsed_preds[i]

        ref_text = ref_texts[i]
        pred_text = pred_texts[i]

        rouge_l = rouge.score(ref_text, pred_text)["rougeL"].fmeasure if pred_text else 0.0

        metric_row = {
            "label": row["label"],
            "role": row["role"],
            "json_valid": pred_obj is not None,
            "schema_valid": schema_valid(pred_obj),
            "rougeL": rouge_l,
            "semantic_sim": float(semantic_sims[i]),
        }

        for field in ["s", "t", "a", "r", "original_quality"]:
            ref_field = flatten_field(ref_obj, field)
            pred_field = flatten_field(pred_obj, field) if pred_obj is not None else ""

            if ref_field and pred_field:
                f_ref = embedder.encode([ref_field], normalize_embeddings=True, convert_to_numpy=True)
                f_pred = embedder.encode([pred_field], normalize_embeddings=True, convert_to_numpy=True)
                metric_row[f"{field}_sim"] = float((f_ref * f_pred).sum())
            else:
                metric_row[f"{field}_sim"] = 0.0

        rows.append(metric_row)

    return pd.DataFrame(rows)

def summarize_eval(eval_df):
    metric_cols = [
        "json_valid", "schema_valid", "rougeL", "semantic_sim",
        "s_sim", "t_sim", "a_sim", "r_sim", "original_quality_sim",
    ]
    return eval_df[metric_cols].mean().to_frame("mean").T

In [19]:
import transformers
print(transformers.__version__)

4.57.1

In [11]:
# Cell 9. 학습 전 base model test 평가 - 미니배치

base_pred_path = PRED_DIR / "base_test_predictions.jsonl"

base_pred_df = run_generation(
    model=model,
    tokenizer=tokenizer,
    data_df=test_df,
    output_path=base_pred_path,
    batch_size=4,        # OOM 나면 2 또는 1
    max_new_tokens=800,  # 출력 잘리면 1000~1200
    max_input_tokens=2048,
    resume=True,
)

base_eval_df = evaluate_prediction_df(base_pred_df)
base_eval_df.to_csv(PRED_DIR / "base_test_metrics.csv", index=False, encoding="utf-8-sig")

print("Base overall")
display(summarize_eval(base_eval_df))

print("Base by label")
display(base_eval_df.groupby("label").mean(numeric_only=True))

print("Base by role")
display(base_eval_df.groupby("role").mean(numeric_only=True).sort_values("semantic_sim"))

  0%|          | 0/24 [00:00<?, ?it/s]

Base overall

,json_valid,schema_valid,rougeL,semantic_sim,s_sim,t_sim,a_sim,r_sim,original_quality_sim
mean,0.708333,0.604167,0.208947,0.541779,0.425589,0.373006,0.367957,0.068279,0.379814

Base by label

,json_valid,schema_valid,rougeL,semantic_sim,s_sim,t_sim,a_sim,r_sim,original_quality_sim
label,,,,,,,,,
0,0.785714,0.714286,0.142857,0.508894,0.375466,0.437809,0.220688,0.048234,0.387258
1,0.705882,0.632353,0.252328,0.562848,0.453910,0.383613,0.414992,0.036150,0.387248
2,0.642857,0.357143,0.064331,0.472328,0.338154,0.256682,0.286771,0.244380,0.336258

Base by role

,label,json_valid,schema_valid,rougeL,semantic_sim,s_sim,t_sim,a_sim,r_sim,original_quality_sim
role,,,,,,,,,,
게임·그래픽스 개발자,1.111111,0.555556,0.444444,0.210967,0.417006,0.256089,0.227765,0.229070,0.030372,0.300551
AI 엔지니어 / 머신러닝 엔지니어,0.933333,0.533333,0.466667,0.148565,0.446394,0.338563,0.294864,0.282094,0.022234,0.280184
DevOps 엔지니어 / 인프라 엔지니어,1.000000,0.571429,0.571429,0.300340,0.485652,0.304626,0.277589,0.355249,0.038514,0.323181
풀스택 개발자,0.888889,0.555556,0.444444,0.103704,0.487315,0.378852,0.319640,0.258538,0.076551,0.267414
보안 엔지니어,1.000000,0.625000,0.375000,0.125000,0.499492,0.411478,0.362313,0.350322,0.013627,0.354099
QA 엔지니어 / 테스트 엔지니어,1.000000,0.714286,0.571429,0.109890,0.550876,0.312067,0.356750,0.421032,0.134241,0.276950
프론트엔드 개발자,1.000000,0.875000,0.750000,0.050000,0.568146,0.448311,0.412910,0.380895,-0.000698,0.491856
모바일 앱 개발자,1.000000,1.000000,1.000000,0.382381,0.624080,0.622488,0.556814,0.504151,0.057105,0.563915
백엔드 개발자,1.062500,0.812500,0.687500,0.396387,0.650469,0.551914,0.477022,0.472145,0.142144,0.449333
데이터 엔지니어 / 데이터 분석가,1.000000,0.900000,0.800000,0.170794,0.660312,0.568048,0.428676,0.433693,0.127221,0.504240

In [20]:
# Cell 10. base 모델 메모리 정리

del model
gc.collect()
torch.cuda.empty_cache()

In [21]:
# Cell 11. SFT 학습 데이터 구성

from datasets import Dataset

def make_sft_text(example):
    messages = build_messages(example)
    messages.append({
        "role": "assistant",
        "content": target_text(example),
    })

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False,
    )

    if tokenizer.eos_token and not text.endswith(tokenizer.eos_token):
        text += tokenizer.eos_token

    return text

train_records = train_df.drop(columns=["strata"]).to_dict("records")
val_records = val_df.drop(columns=["strata"]).to_dict("records")

train_sft = Dataset.from_list([{"text": make_sft_text(x)} for x in train_records])
val_sft = Dataset.from_list([{"text": make_sft_text(x)} for x in val_records])

print(train_sft[0]["text"][:1000])

[|system|]너는 자기소개서 답변을 STAR 구조로 변환하는 평가/작성 보조 모델이다.
반드시 JSON만 출력한다. 설명, 마크다운, 코드블록은 출력하지 않는다.
출력 key는 학습 데이터와 동일하게 self_intoduction, original_quality를 사용한다.
self_intoduction의 각 항목은 question과 answer를 포함하고, answer는 s, t, a, r을 포함한다.[|endofturn|]
[|user|]다음 JSON을 읽고 정답 output과 같은 구조의 JSON만 생성하라.

입력:
{"role": "풀스택 개발자", "input": {"self_intoduction": [{"question": "지원 동기를 작성해 주세요.", "answer": "귀사의 비전에 공감하여 풀스택 개발자 직무에 지원하게 되었습니다. 성장하는 회사에서 함께 발전하고 싶습니다."}, {"question": "본인의 성장 과정을 소개해 주세요.", "answer": "평범하지만 화목한 가정에서 성실하게 자랐습니다. 부모님께 정직함을 배웠습니다."}, {"question": "직무 수행에 필요한 본인의 역량을 작성해 주세요.", "answer": "다양한 기술을 다룰 줄 압니다. 필요한 건 금방 배웁니다."}, {"question": "", "answer": ""}]}}

출력 JSON 스키마:
{
  "self_intoduction": [
    {
      "question": "...",
      "answer": {
        "s": "...",
        "t": "...",
        "a": "...",
        "r": "..."
      }
    }
  ],
  "original_quality": "..."
}
[|assistant|]{"self_intoduction": [{"question": "지원 동기를 작성해 주세요.", "answer": {"s": "회사 비전에 공감해 지원한 상황이라고 서술

In [23]:
# Cell 12. QLoRA SFT 학습 - early stopping + best checkpoint 저장

from peft import LoraConfig
from trl import SFTTrainer, SFTConfig
from transformers import EarlyStoppingCallback

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    revision=MODEL_REVISION,
    code_revision=MODEL_REVISION,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=get_torch_dtype(),
    trust_remote_code=True,
)

model.config.use_cache = False

def guess_lora_targets(model):
    candidates = {
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    }
    found = sorted({
        name.split(".")[-1]
        for name, module in model.named_modules()
        if name.split(".")[-1] in candidates
    })
    return found or sorted(candidates)

lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
    target_modules=guess_lora_targets(model),
)

# train 약 300개 기준:
# batch 1 * grad_acc 8 => optimizer step 약 38 step / epoch
# eval_steps=20이면 epoch당 약 2번 검증
# patience=3이면 eval loss가 3번 연속 좋아지지 않을 때 조기 종료
sft_args = SFTConfig(
    output_dir=str(ADAPTER_DIR),
    dataset_text_field="text",
    max_length=2048,
    packing=False,

    num_train_epochs=5,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,

    learning_rate=2e-4,
    warmup_ratio=0.03,
    lr_scheduler_type="cosine",

    logging_steps=5,

    eval_strategy="steps",
    eval_steps=20,

    save_strategy="steps",
    save_steps=20,
    save_total_limit=3,

    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,

    bf16=torch.cuda.is_available() and torch.cuda.is_bf16_supported(),
    fp16=torch.cuda.is_available() and not torch.cuda.is_bf16_supported(),

    report_to="none",
    seed=SEED,
)

early_stopping = EarlyStoppingCallback(
    early_stopping_patience=3,
    early_stopping_threshold=0.001,
)

trainer = SFTTrainer(
    model=model,
    args=sft_args,
    train_dataset=train_sft,
    eval_dataset=val_sft,
    peft_config=lora_config,
    processing_class=tokenizer,
    callbacks=[early_stopping],
)

train_result = trainer.train()

print("Best checkpoint:", trainer.state.best_model_checkpoint)
print("Best eval loss:", trainer.state.best_metric)

# load_best_model_at_end=True 이므로 여기서 저장되는 모델은 best checkpoint 기준 adapter
trainer.save_model(str(ADAPTER_DIR))
tokenizer.save_pretrained(str(ADAPTER_DIR))

print("Best LoRA adapter saved to:", ADAPTER_DIR)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

Adding EOS to train dataset:   0%|          | 0/298 [00:00<?, ? examples/s]

Tokenizing train dataset:   0%|          | 0/298 [00:00<?, ? examples/s]

Building labels for train dataset:   0%|          | 0/298 [00:00<?, ? examples/s]

Adding EOS to eval dataset:   0%|          | 0/106 [00:00<?, ? examples/s]

Tokenizing eval dataset:   0%|          | 0/106 [00:00<?, ? examples/s]

Building labels for eval dataset:   0%|          | 0/106 [00:00<?, ? examples/s]

Best checkpoint: exaone_self_intro_star/exaone_star_lora/checkpoint-180
Best eval loss: 0.12479308247566223
Best LoRA adapter saved to: exaone_self_intro_star/exaone_star_lora

In [24]:
# Cell 13. 학습 후 같은 test set 평가 - 미니배치

model.eval()

trained_pred_path = PRED_DIR / "trained_test_predictions.jsonl"

trained_pred_df = run_generation(
    model=model,
    tokenizer=tokenizer,
    data_df=test_df,
    output_path=trained_pred_path,
    batch_size=4,        # OOM 나면 2 또는 1
    max_new_tokens=800,
    max_input_tokens=2048,
    resume=True,
)

trained_eval_df = evaluate_prediction_df(trained_pred_df)
trained_eval_df.to_csv(PRED_DIR / "trained_test_metrics.csv", index=False, encoding="utf-8-sig")

print("Trained overall")
display(summarize_eval(trained_eval_df))

print("Trained by label")
display(trained_eval_df.groupby("label").mean(numeric_only=True))

print("Trained by role")
display(trained_eval_df.groupby("role").mean(numeric_only=True).sort_values("semantic_sim"))

  0%|          | 0/24 [00:00<?, ?it/s]

Trained overall

,json_valid,schema_valid,rougeL,semantic_sim,s_sim,t_sim,a_sim,r_sim,original_quality_sim
mean,0.958333,0.958333,0.913565,0.929599,0.899855,0.884251,0.889824,0.915998,0.895686

Trained by label

,json_valid,schema_valid,rougeL,semantic_sim,s_sim,t_sim,a_sim,r_sim,original_quality_sim
label,,,,,,,,,
0,1.000000,1.000000,0.976190,0.918632,0.912479,0.885623,0.709605,1.000000,0.941126
1,0.970588,0.970588,0.928918,0.953834,0.911747,0.909724,0.952224,0.938214,0.913188
2,0.857143,0.857143,0.776364,0.822857,0.829468,0.759158,0.766961,0.724092,0.765238

Trained by role

,label,json_valid,schema_valid,rougeL,semantic_sim,s_sim,t_sim,a_sim,r_sim,original_quality_sim
role,,,,,,,,,,
AI 엔지니어 / 머신러닝 엔지니어,0.933333,0.866667,0.866667,0.820828,0.847809,0.833944,0.785447,0.777648,0.866667,0.801815
게임·그래픽스 개발자,1.111111,0.888889,0.888889,0.880342,0.857502,0.794844,0.830002,0.822194,0.871051,0.829622
데이터 엔지니어 / 데이터 분석가,1.000000,0.900000,0.900000,0.885714,0.889470,0.852695,0.850811,0.858832,0.815586,0.866507
모바일 앱 개발자,1.000000,1.000000,1.000000,0.951020,0.942932,0.903218,0.896114,0.871052,0.926478,0.931393
DevOps 엔지니어 / 인프라 엔지니어,1.000000,1.000000,1.000000,0.951299,0.951004,0.930522,0.896156,0.924776,0.994687,0.950797
풀스택 개발자,0.888889,1.000000,1.000000,0.847407,0.955023,0.911916,0.892211,0.896340,0.903116,0.908855
프론트엔드 개발자,1.000000,1.000000,1.000000,1.000000,0.957341,0.978585,0.924501,0.917581,0.987531,0.965398
QA 엔지니어 / 테스트 엔지니어,1.000000,1.000000,1.000000,0.857143,0.980053,0.862797,0.867600,0.970576,0.997844,0.882133
백엔드 개발자,1.062500,1.000000,1.000000,0.979167,0.980585,0.964310,0.963080,0.962529,0.953499,0.943088
보안 엔지니어,1.000000,1.000000,1.000000,1.000000,0.981370,0.981962,0.959253,0.949667,0.902895,0.935552

In [25]:
# Cell 14. base vs trained 비교

base_summary = summarize_eval(base_eval_df).rename(index={"mean": "base"})
trained_summary = summarize_eval(trained_eval_df).rename(index={"mean": "trained"})

comparison = pd.concat([base_summary, trained_summary])
comparison.loc["delta_trained_minus_base"] = comparison.loc["trained"] - comparison.loc["base"]

display(comparison)

label_comparison = (
    base_eval_df.groupby("label").mean(numeric_only=True)
    .add_prefix("base_")
    .join(
        trained_eval_df.groupby("label").mean(numeric_only=True).add_prefix("trained_")
    )
)

for col in ["json_valid", "schema_valid", "rougeL", "semantic_sim"]:
    label_comparison[f"delta_{col}"] = (
        label_comparison[f"trained_{col}"] - label_comparison[f"base_{col}"]
    )

display(label_comparison)

,json_valid,schema_valid,rougeL,semantic_sim,s_sim,t_sim,a_sim,r_sim,original_quality_sim
base,0.708333,0.604167,0.208947,0.541779,0.425589,0.373006,0.367957,0.068279,0.379814
trained,0.958333,0.958333,0.913565,0.929599,0.899855,0.884251,0.889824,0.915998,0.895686
delta_trained_minus_base,0.250000,0.354167,0.704618,0.387820,0.474265,0.511246,0.521867,0.847719,0.515872

,base_json_valid,base_schema_valid,base_rougeL,base_semantic_sim,base_s_sim,base_t_sim,base_a_sim,base_r_sim,base_original_quality_sim,trained_json_valid,...,trained_semantic_sim,trained_s_sim,trained_t_sim,trained_a_sim,trained_r_sim,trained_original_quality_sim,delta_json_valid,delta_schema_valid,delta_rougeL,delta_semantic_sim
label,,,,,,,,,,,,,,,,,,,,,
0,0.785714,0.714286,0.142857,0.508894,0.375466,0.437809,0.220688,0.048234,0.387258,1.000000,...,0.918632,0.912479,0.885623,0.709605,1.000000,0.941126,0.214286,0.285714,0.833333,0.409738
1,0.705882,0.632353,0.252328,0.562848,0.453910,0.383613,0.414992,0.036150,0.387248,0.970588,...,0.953834,0.911747,0.909724,0.952224,0.938214,0.913188,0.264706,0.338235,0.676591,0.390986
2,0.642857,0.357143,0.064331,0.472328,0.338154,0.256682,0.286771,0.244380,0.336258,0.857143,...,0.822857,0.829468,0.759158,0.766961,0.724092,0.765238,0.214286,0.500000,0.712032,0.350529

In [26]:
# Cell 15. 나쁜 케이스 직접 확인

inspect_df = trained_eval_df.copy()
inspect_df["prediction_text"] = trained_pred_df["prediction_text"]
inspect_df["reference_output"] = trained_pred_df["reference_output"]

bad_cases = inspect_df.sort_values(["schema_valid", "semantic_sim"], ascending=[True, True]).head(10)

for i, row in bad_cases.iterrows():
    print("=" * 100)
    print("label:", row["label"])
    print("role:", row["role"])
    print("schema_valid:", row["schema_valid"])
    print("semantic_sim:", row["semantic_sim"])
    print("\n[PRED]")
    print(row["prediction_text"][:2000])
    print("\n[REF]")
    print(json.dumps(row["reference_output"], ensure_ascii=False)[:2000])

====================================================================================================
label: 2
role: AI 엔지니어 / 머신러닝 엔지니어
schema_valid: False
semantic_sim: 0.07646963000297546

[PRED]
{
  "self_intoduction": [
    {
      "question": "직무와 관련된 성과 경험을 작성해 주세요.",
      "answer": {
        "s": "전처리를 매번 수동으로 하며 실험 반복이 느렸던 상황이었습니다.",
        "t": "전처리 과정을 자동화해 실험 반복 시간을 줄여야 했습니다.",
        "a": "전처리를 자동화 스크립트를 작성해 적용했습니다.",
        "r": "실험 반복 시간을 줄였다고 원문에 제시되어 있습니다."
      }
    },
    {
      "question": "본인의 강점을 설명해 주세요.",
      "answer": {
        "s": "학습 데이터가 클래스 불균형으로 성능이 낮았던 상황이었습니다.",
        "t": "불균형 데이터를 개선해 예측 성능을 높여야 했습니다.",
        "a": "데이터 증강과 샘플링을 적용해 불균형을 줄였습니다.",
        "r": "소수 클래스 예측 성능을 개선했다고 원문에 제시되어 있습니다."
      }
    },
    {
      "question": "지원 동기를 작성해 주세요.",
      "answer": {
        "s": "AI 엔지니어 / 머신러닝 엔지니어 직무에 관심을 갖고 지원한 상황이었습니다.",
        "t": "보유한 경험을 직무 역량과 연결해 지원 근거를 제시해야 했습니다.",
        "a": "관련 프로젝트에서 기능을 직접 구현한 경험을 언급하며 직무 기여 가능성을 제시했습니다.",
        "r": "직무 역량에 기여할 수 있다는 연결을 구체적으로 서술했습니다."
      }
    },
    {
      "question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.",
      "answer": {
        "s": "[COMP_NAME_1] 인턴으로 [PROJECT_NAME_1]에 참여했을 때 기능 우선순위를 두고 담당자 간 의견이 충돌한 상황이었습니다.",
        "t": "충돌하는 우선순위를 조율해 일정을 재합의해야 했습니다.",
        "a": "요구사항을 표로 정리하고 예상 공수를 근거로 회의를 진행해 일정을 재합의했습니다.",
        "r": "마감 지연 없이 마무리했다고 원문에 제시되어 있습니다."
      }
    }
  },
  "original_quality": "원문은 경험이 구체적이고 행동과 결과의 연결이 명확한 편이어서, 답변만으로도 직무 관련 역량을 어느 정도 확인할 수 있습니다. 구체적인 회사·프로젝트·교육기관 등이 마스킹되어 있어 소속·규모를 근거로 한 판단은 피해야 합니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."
}

[REF]
{"self_intoduction": [{"question": "직무와 관련된 성과 경험을 작성해 주세요.", "answer": {"s": "전처리를 매번 수동으로 하며 실험 반복이 느리던 상황이었습니다.", "t": "전처리를 자동화해 실험을 빠르게 반복해야 했습니다.", "a": "전처리 과정을 자동화 스크립트로 만들었습니다.", "r": "실험 반복 시간을 줄였다고 원문에 제시되어 있습니다."}}, {"question": "본인의 강점을 설명해 주세요.", "answer": {"s": "학습 데이터의 클래스 불균형으로 예측 성능이 낮던 상황이었습니다.", "t": "불균형을 완화해 예측 성능을 높여야 했습니다.", "a": "데이터 증강과 샘플링을 적용해 클래스 균형을 맞췄습니다.", "r": "소수 클래스 예측 성능을 개선했다고 원문에 제시되어 있습니다."}}, {"question": "지원 동기를 작성해 주세요.", "answer": {"s": "AI 엔지니어 / 머신러닝 엔지니어 직무에 관심을 갖고 지원한 상황이었습니다.", "t": "보유한 개발 경험이 직무와 어떻게 연결되는지 제시해야 했습니다.", "a": "관련 프로젝트에서 기능을 직접 구현한 경험을 근거로 직무 기여 가능성을 제시했습니다.", "r": "직무 역량에 기여할 수 있다는 연결을 구체적으로 서술했습니다."}}, {"question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.", "answer": {"s": "[COMP_NAME_1] 인턴으로 [PROJECT_NAME_1]에 참여해 우선순위를 두고 담당자 간 의견이 충돌한 상황이었습니다.", "t": "충돌하는 우선순위를 조율해 일정을 다시 합의해야 했습니다.", "a": "요구사항을 표로 정리하고 예상 공수를 근거로 회의를 진행해 일정을 재합의했습니다.", "r": "마감 지연 없이 마무리했다고 원문에 제시되어 있습니다."}}], "original_quality": "원문은 경험이 구체적이고 행동과 결과의 연결이 명확한 편이어서, 답변만으로도 직무 관련 역량을 어느 정도 확인할 수 있습니다. 구체적인 회사·프로젝트·교육기관 등이 마스킹되어 있어 소속·규모를 근거로 한 판단은 피해야 합니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."}
====================================================================================================
label: 2
role: 게임·그래픽스 개발자
schema_valid: False
semantic_sim: 0.14311347901821136

[PRED]
{
  "self_intoduction": [
    {
      "question": "직무와 관련된 성과 경험을 작성해 주세요.",
      "answer": {
        "s": "장시간 플레이 시 메모리가 쌓여 앱이 튕겼던 상황이었습니다.",
        "t": "메모리 누수를 찾아 리소스 누수를 막아야 했습니다.",
        "a": "해제되지 않던 리소스를 정리했습니다.",
        "r": "장시간 플레이 안정성을 높였다고 원문에 제시되어 있습니다."
      }
    },
    {
      "question": "지원 동기를 작성해 주세요.",
      "answer": {
        "s": "게임·그래픽스 개발자 직무에 관심을 갖고 지원한 상황이었습니다.",
        "t": "보유한 개발 경험이 직무와 어떻게 연결되는지 제시해야 했습니다.",
        "a": "관련 프로젝트에서 기능을 직접 구현한 경험을 근거로 직무 기여 가능성을 제시했습니다.",
        "r": "직무 역량에 기여할 수 있다는 연결을 구체적으로 서술했습니다."
      }
    },
    {
      "question": "본인의 강점을 설명해 주세요.",
      "answer": {
        "s": "물리 연산이 많은 장면에서 렉이 발생하던 상황이었습니다.",
        "t": "연산 부담을 줄여 성능을 개선해야 했습니다.",
        "a": "물리 연산을 최적화해 렉을 줄였습니다.",
        "r": "성능 저하를 개선해 기능 동작을 유지했다고 원문에 제시되어 있습니다."
      }
    },
    {
      "question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.",
      "answer": {
        "s": "[COMP_NAME_1] 인턴으로 [PROJECT_NAME_1]에 참여했을 때 기능 우선순위를 두고 담당자 간 의견이 충돌했던 상황이었습니다.",
        "t": "충돌하는 우선순위를 조율해 일정을 다시 합의해야 했습니다.",
        "a": "요구사항을 표로 정리하고 예상 공수를 근거로 회의를 진행해 일정을 재합의했습니다.",
        "r": "마감 지연 없이 마무리했다고 원문에 제시되어 있습니다."
      }
    }
  },
  "original_quality": "원문은 각 문항에서 상황·행동·결과가 비교적 구체적으로 드러나며, 일부 답변에는 성과나 개선 결과가 함께 제시되어 지원자의 기여도를 판단할 근거가 있습니다. 구체적인 회사·프로젝트·교육기관 등이 마스킹되어 있어 소속·규모를 근거로 한 판단은 피해야 합니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."
}

[REF]
{"self_intoduction": [{"question": "직무와 관련된 성과 경험을 작성해 주세요.", "answer": {"s": "장시간 플레이 시 메모리가 쌓여 튕기던 상황이었습니다.", "t": "메모리 누수를 잡아 안정성을 높여야 했습니다.", "a": "해제되지 않던 리소스를 찾아 정리했습니다.", "r": "장시간 플레이 안정성을 높였다고 원문에 제시되어 있습니다."}}, {"question": "지원 동기를 작성해 주세요.", "answer": {"s": "게임·그래픽스 개발자 직무에 관심을 갖고 지원한 상황이었습니다.", "t": "보유한 개발 경험이 직무와 어떻게 연결되는지 제시해야 했습니다.", "a": "관련 프로젝트에서 기능을 직접 구현한 경험을 근거로 직무 기여 가능성을 제시했습니다.", "r": "직무 역량에 기여할 수 있다는 연결을 구체적으로 서술했습니다."}}, {"question": "본인의 강점을 설명해 주세요.", "answer": {"s": "물리 연산이 많은 장면에서 렉이 발생하던 상황이었습니다.", "t": "연산 부담을 줄여 부드럽게 동작하게 해야 했습니다.", "a": "불필요한 물리 연산을 정리하고 최적화했습니다.", "r": "렉을 줄였다고 원문에 제시되어 있습니다."}}, {"question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.", "answer": {"s": "[COMP_NAME_1] 인턴으로 [PROJECT_NAME_1]에 참여해 우선순위를 두고 담당자 간 의견이 충돌한 상황이었습니다.", "t": "충돌하는 우선순위를 조율해 일정을 다시 합의해야 했습니다.", "a": "요구사항을 표로 정리하고 예상 공수를 근거로 회의를 진행해 일정을 재합의했습니다.", "r": "마감 지연 없이 마무리했다고 원문에 제시되어 있습니다."}}], "original_quality": "원문은 경험이 구체적이고 행동과 결과의 연결이 명확한 편이어서, 답변만으로도 직무 관련 역량을 어느 정도 확인할 수 있습니다. 구체적인 회사·프로젝트·교육기관 등이 마스킹되어 있어 소속·규모를 근거로 한 판단은 피해야 합니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."}
====================================================================================================
label: 1
role: AI 엔지니어 / 머신러닝 엔지니어
schema_valid: False
semantic_sim: 0.17056572437286377

[PRED]
{
  "self_intoduction": [
    {
      "question": "직무 수행에 필요한 본인의 역량을 작성해 주세요.",
      "answer": {
        "s": "[PROJECT_NAME_1]에서 문서 요약 기능을 구현해야 하는 상황이었습니다.",
        "t": "OpenAI API를 활용해 요약 기능을 만들고 결과 품질을 높여야 했습니다.",
        "a": "문맥에 맞는 프롬프트로 요약을 유도하고 결과를 다듬었습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "입사 후 목표나 포부를 작성해 주세요.",
      "answer": {
        "s": "입사 후 협업하며 성장하고자 하는 목표를 밝힌 상황입니다.",
        "t": "포부를 구체적 목표와 연결해 제시해야 했습니다.",
        "a": "협업하며 성장하고 책임감 있게 일하겠다고 서술했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "실패했거나 어려움을 극복한 경험을 작성해 주세요.",
      "answer": {
        "s": "임베딩을 활용해 유사 문서를 찾아야 하는 상황이었습니다.",
        "t": "임베딩 기반 유사도 검색을 구현해야 했습니다.",
        "a": "문서를 임베딩해 유사 문서 검색 기능을 프로토타입으로 구현했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "지원 동기를 작성해 주세요.",
      "answer": {
        "s": "AI 엔지니어 / 머신러닝 엔지니어 직무에 관심을 갖고 지원한 상황이었습니다.",
        "t": "관심과 경험을 지원 동기로 연결해야 했습니다.",
        "a": "관련 프로젝트 경험을 살려 일하고 싶다고 서술했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    }
  },
  "original_quality": "원문은 상황과 행동은 서술되어 있으나 결과가 불명확한 답변이 섞여 있어, 역량을 단정하기보다는 근거가 있는 부분에 한해 평가하는 것이 적절합니다. 구체적인 회사·프로젝트·교육기관 등이 마스킹되어 있어 소속·규모를 근거로 한 판단은 피해야 합니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."
}

[REF]
{"self_intoduction": [{"question": "직무 수행에 필요한 본인의 역량을 작성해 주세요.", "answer": {"s": "[PROJECT_NAME_1]에서 문서 요약 기능을 구현해야 하는 상황이었습니다.", "t": "LLM API로 요약 기능을 만들고 결과 품질을 맞춰야 했습니다.", "a": "OpenAI API로 요약 기능을 구현하고 프롬프트를 조정했습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}, {"question": "입사 후 목표나 포부를 작성해 주세요.", "answer": {"s": "입사 후 협업하며 성장하고자 하는 상황입니다.", "t": "목표와 태도를 제시해야 했습니다.", "a": "협업하며 성장하고 책임감 있게 일하겠다고 서술했습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}, {"question": "실패했거나 어려움을 극복한 경험을 작성해 주세요.", "answer": {"s": "질의와 비슷한 문서를 찾아줘야 하는 상황이었습니다.", "t": "임베딩 기반 유사도 검색을 구현해야 했습니다.", "a": "문서를 임베딩해 유사 문서 검색 기능을 프로토타입으로 구현했습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}, {"question": "지원 동기를 작성해 주세요.", "answer": {"s": "AI 엔지니어 / 머신러닝 엔지니어 직무에 관심을 갖고 지원한 상황이었습니다.", "t": "관심과 경험을 지원 동기로 연결해야 했습니다.", "a": "관련 프로젝트 경험을 살리고 싶다고 서술했습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}], "original_quality": "원문은 각 문항의 핵심 의도는 대체로 드러나지만, 일부 답변에서 구체적인 성과나 정량적 결과가 부족해 지원자의 실제 기여도를 판단하는 데 한계가 있습니다. 구체적인 회사·프로젝트·교육기관 등이 마스킹되어 있어 소속·규모를 근거로 한 판단은 피해야 합니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."}
====================================================================================================
label: 1
role: 데이터 엔지니어 / 데이터 분석가
schema_valid: False
semantic_sim: 0.182024285197258

[PRED]
{
  "self_intoduction": [
    {
      "question": "직무 수행에 필요한 본인의 역량을 작성해 주세요.",
      "answer": {
        "s": "CSV 데이터를 직접 다뤄야 하는 상황이었습니다.",
        "t": "전처리 과정을 수행해 데이터를 분석 가능한 형태로 만들어야 했습니다.",
        "a": "pandas로 CSV 데이터를 전처리했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.",
      "answer": {
        "s": "팀 프로젝트에서 코드 컨벤션을 두고 의견이 갈린 상황이었습니다.",
        "t": "컨벤션에 대한 합의를 이끌어 협업을 이어가야 했습니다.",
        "a": "각자의 이유를 듣고 공통 규칙 문서를 만들어 합의했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "팀 프로젝트에서 어려움을 해결한 경험을 작성해 주세요.",
      "answer": {
        "s": "지표 정의가 사람마다 달라 정리가 안 된 상황이었습니다.",
        "t": "지표 정의를 일관되게 정리해 협업을 이어가야 했습니다.",
        "a": "지표 정의를 정리해 문서로 만들었습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "본인의 강점을 설명해 주세요.",
      "answer": {
        "s": "외부 데이터를 주기적으로 모아야 하는 상황이었습니다.",
        "t": "데이터 수집 작업을 자동으로 수행해야 했습니다.",
        "a": "데이터 수집 스크립트를 작성해 주기적으로 실행했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    }
  },
  "original_quality": "원문은 각 문항의 핵심 의도는 대체로 드러나지만, 일부 답변에서 구체적인 성과나 정량적 결과가 부족해 지원자의 실제 기여도를 판단하는 데 한계가 있습니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."
}

[REF]
{"self_intoduction": [{"question": "직무 수행에 필요한 본인의 역량을 작성해 주세요.", "answer": {"s": "CSV 데이터를 분석 전 정리해야 하는 상황이었습니다.", "t": "데이터를 전처리해 분석 가능하게 만들어야 했습니다.", "a": "pandas로 결측 처리와 형 변환 등 전처리를 수행했습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}, {"question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.", "answer": {"s": "팀 프로젝트에서 코드 컨벤션을 두고 의견이 갈린 상황이었습니다.", "t": "컨벤션에 대한 합의를 이끌어 협업을 이어가야 했습니다.", "a": "각자의 이유를 듣고 공통 규칙 문서를 만들어 합의했습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}, {"question": "팀 프로젝트에서 어려움을 해결한 경험을 작성해 주세요.", "answer": {"s": "같은 지표를 서로 다르게 계산하던 상황이었습니다.", "t": "지표 정의를 통일해 혼선을 줄여야 했습니다.", "a": "지표 정의를 문서로 정리해 공유했습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}, {"question": "본인의 강점을 설명해 주세요.", "answer": {"s": "외부 데이터를 주기적으로 모아야 하는 상황이었습니다.", "t": "데이터 수집을 자동으로 수행해야 했습니다.", "a": "데이터 수집 스크립트를 작성해 주기적으로 실행했습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}], "original_quality": "원문은 각 문항의 핵심 의도는 대체로 드러나지만, 일부 답변에서 구체적인 성과나 정량적 결과가 부족해 지원자의 실제 기여도를 판단하는 데 한계가 있습니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."}
====================================================================================================
label: 0
role: 게임·그래픽스 개발자
schema_valid: True
semantic_sim: 0.7511821389198303

[PRED]
{
  "self_intoduction": [
    {
      "question": "지원 동기를 작성해 주세요.",
      "answer": {
        "s": "게임·그래픽스 개발자 직무 지원을 언급한 상황이습니다.",
        "t": "지원 동기와 학습 의지를 제시해야 했습니다.",
        "a": "직무 전망을 언급하고 열심히 배우겠다고 서술했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "직무와 관련된 성과 경험을 작성해 주세요.",
      "answer": {
        "s": "맡은 일을 성실히 수행한 상황이라고 서술되어 있습니다.",
        "t": "성과 경험을 구체적 결과로 연결해야 했습니다.",
        "a": "좋은 평가를 받았다고 언급했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    }
  ],
  "original_quality": "원문은 일반적이고 상투적인 표현이 많고 구체적 근거가 부족해, 지원자의 실제 경험이나 기여도를 확인하기 어려운 수준입니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."
}

[REF]
{"self_intoduction": [{"question": "지원 동기를 작성해 주세요.", "answer": {"s": "직무 전망을 이유로 지원한 상황이라고 서술되어 있습니다.", "t": "지원 동기를 경험과 연결해 제시해야 했습니다.", "a": "전망이 좋다고 언급했으나 본인 경험과의 연결은 없습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}, {"question": "직무와 관련된 성과 경험을 작성해 주세요.", "answer": {"s": "맡은 일을 수행한 상황이라고만 서술되어 있습니다.", "t": "구체적 성과와 근거를 제시해야 했습니다.", "a": "좋은 평가를 받았다고 언급했으나 구체적 근거는 없습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}], "original_quality": "원문은 일반적이고 상투적인 표현이 많고 구체적 근거가 부족해, 지원자의 실제 경험이나 기여도를 확인하기 어려운 수준입니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."}
====================================================================================================
label: 0
role: 모바일 앱 개발자
schema_valid: True
semantic_sim: 0.8177655935287476

[PRED]
{
  "self_intoduction": [
    {
      "question": "지원 동기를 작성해 주세요.",
      "answer": {
        "s": "모바일 앱 개발자 직무에 지원한 상황이었습니다.",
        "t": "지원 동기를 구체적 근거로 제시해야 했습니다.",
        "a": "직무 전망을 언급하고 열심히 배우겠다는 의지를 서술했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "팀 프로젝트에서 어려움을 해결한 경험을 작성해 주세요.",
      "answer": {
        "s": "팀 프로젝트를 함께 수행한 상황이었습니다.",
        "t": "소통을 통해 협업을 마무리해야 했습니다.",
        "a": "팀원들과 소통을 잘해서 프로젝트를 마쳤습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    }
  ],
  "original_quality": "원문은 일반적이고 추상적인 표현이 많아 지원자의 실제 경험이나 기여도를 확인하기 어려운 수준입니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."
}

[REF]
{"self_intoduction": [{"question": "지원 동기를 작성해 주세요.", "answer": {"s": "직무 전망을 이유로 지원한 상황이라고 서술되어 있습니다.", "t": "지원 동기를 경험과 연결해 제시해야 했습니다.", "a": "전망이 좋다고 언급했으나 본인 경험과의 연결은 없습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}, {"question": "팀 프로젝트에서 어려움을 해결한 경험을 작성해 주세요.", "answer": {"s": "팀으로 프로젝트를 마친 상황이라고만 서술되어 있습니다.", "t": "소통 과정에서 본인의 기여를 제시해야 했습니다.", "a": "소통을 잘했다고 언급했으나 구체적 행동은 없습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}], "original_quality": "원문은 일반적이고 상투적인 표현이 많고 구체적 근거가 부족해, 지원자의 실제 경험이나 기여도를 확인하기 어려운 수준입니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."}
====================================================================================================
label: 2
role: 프론트엔드 개발자
schema_valid: True
semantic_sim: 0.822095513343811

[PRED]
{
  "self_intoduction": [
    {
      "question": "지원 동기를 작성해 주세요.",
      "answer": {
        "s": "[지원 회사에서] 서비스를 만들어 운영하는 환경이었습니다.",
        "t": "본인의 경험이 해당 직무에 어떻게 기여할 수 있는지 제시해야 했습니다.",
        "a": "실제 서비스에 프론트엔드 기능을 구현하며 직무에 확신을 갖게 됐다고 서술했습니다.",
        "r": "서비스 품질 개선에 기여한 경험을 근거로 직무 확신을 제시했습니다."
      }
    },
    {
      "question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.",
      "answer": {
        "s": "[COMP_NAME_1] 인턴으로 [PROJECT_NAME_1]에 참여해 우선순위를 두고 담당자 간 의견이 충돌한 상황이었습니다.",
        "t": "충돌하는 우선순위를 조율해 일정을 다시 합의해야 했습니다.",
        "a": "요구사항을 표로 정리하고 예상 공수를 근거로 회의를 진행해 일정을 재합의했습니다.",
        "r": "마감 지연 없이 마무리했다고 원문에 제시되어 있습니다."
      }
    },
    {
      "question": "직무와 관련된 성과 경험을 작성해 주세요.",
      "answer": {
        "s": "화면 전환마다 불필요한 리렌더링이 발생해 반응이 느렸던 상황이었습니다.",
        "t": "렌더링을 줄여 반응 속도를 개선해야 했습니다.",
        "a": "렌더링을 프로파일링해 불필요한 부분을 찾아 메모이제이션을 적용했습니다.",
        "r": "화면 반응 속도를 개선했다고 원문에 제시되어 있습니다."
      }
    },
    {
      "question": "입사 후 목표나 포부를 작성해 주세요.",
      "answer": {
        "s": "입사 후 서비스 품질을 높이는 프론트엔드 개발자가 되고자 하는 목표를 서술한 상황입니다.",
        "t": "입사 후 구체적인 목표와 실행 계획을 제시해야 했습니다.",
        "a": "기존 코드의 문제를 파악하고 개선을 단계적으로 적용하겠다고 서술했습니다.",
        "r": "품질 개선에 기여할 것이라는 구체적 전망을 제시했습니다."
      }
    }
  ],
  "original_quality": "원문은 경험이 구체적인 상황과 결과에 연결되어 있고, 행동의 영향이 명확한 답변이 많아, 지원자의 역량을 비교적 구체적으로 확인할 수 있습니다. 구체적인 회사·프로젝트·교육기관 등이 마스킹되어 있어 소속·규모를 근거로 한 판단은 피해야 합니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."
}

[REF]
{"self_intoduction": [{"question": "지원 동기를 작성해 주세요.", "answer": {"s": "프론트엔드 개발자 직무로 서비스를 만들고자 지원한 상황이었습니다.", "t": "관심을 갖게 된 계기를 경험과 연결해 설명해야 했습니다.", "a": "프로젝트에서 관련 기능을 구현한 경험을 근거로 지원 이유를 제시했습니다.", "r": "경험을 통해 분야에 확신을 갖게 됐다고 구체적으로 서술했습니다."}}, {"question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.", "answer": {"s": "[COMP_NAME_1] 인턴으로 [PROJECT_NAME_1]에 참여해 우선순위를 두고 담당자 간 의견이 충돌한 상황이었습니다.", "t": "충돌하는 우선순위를 조율해 일정을 다시 합의해야 했습니다.", "a": "요구사항을 표로 정리하고 예상 공수를 근거로 회의를 진행해 일정을 재합의했습니다.", "r": "마감 지연 없이 마무리했다고 원문에 제시되어 있습니다."}}, {"question": "직무와 관련된 성과 경험을 작성해 주세요.", "answer": {"s": "화면 전환마다 불필요한 리렌더링으로 반응이 느린 상황이었습니다.", "t": "리렌더링 원인을 찾아 화면 반응성을 개선해야 했습니다.", "a": "렌더링을 프로파일링하고 메모이제이션을 적용했습니다.", "r": "화면 반응 속도를 개선했다고 원문에 제시되어 있습니다."}}, {"question": "입사 후 목표나 포부를 작성해 주세요.", "answer": {"s": "입사 후 서비스 품질 개선에 기여하고자 하는 목표를 밝힌 상황입니다.", "t": "구체적인 실행 계획으로 포부를 뒷받침해야 했습니다.", "a": "기존 문제를 파악한 뒤 개선을 단계적으로 적용하겠다고 제시했습니다.", "r": "품질 개선에 기여하겠다는 구체적 목표를 제시했습니다."}}], "original_quality": "원문은 경험이 구체적이고 행동과 결과의 연결이 명확한 편이어서, 답변만으로도 직무 관련 역량을 어느 정도 확인할 수 있습니다. 구체적인 회사·프로젝트·교육기관 등이 마스킹되어 있어 소속·규모를 근거로 한 판단은 피해야 합니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."}
====================================================================================================
label: 0
role: 데이터 엔지니어 / 데이터 분석가
schema_valid: True
semantic_sim: 0.872641384601593

[PRED]
{
  "self_intoduction": [
    {
      "question": "직무와 관련된 성과 경험을 작성해 주세요.",
      "answer": {
        "s": "맡은 일을 성실히 수행한 상황이었습니다.",
        "t": "성과를 인정받고 신뢰를 얻어야 했습니다.",
        "a": "좋은 평가를 받고 보람을 느꼈다고 서술했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "실패했거나 어려움을 극복한 경험을 작성해 주세요.",
      "answer": {
        "s": "실패한 상황이었던 것으로 원문에서 확인됩니다.",
        "t": "실패를 극복해 평가에서 긍정적 결과를 얻어야 했습니다.",
        "a": "포기하지 않고 노력해 극복했다고 서술했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "직무 수행에 필요한 본인의 역량을 작성해 주세요.",
      "answer": {
        "s": "기본적인 개발 지식을 갖추고 있다고 서술한 상황입니다.",
        "t": "보유 역량을 구체적 경험으로 뒷받침해야 했습니다.",
        "a": "기본 지식을 갖추고 있다고 언급했으나 구체적 사례는 없습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    }
  ],
  "original_quality": "원문은 일반적이고 상투적인 표현이 많고 구체적 근거가 부족해, 지원자의 실제 경험이나 기여도를 확인하기 어려운 수준입니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."
}

[REF]
{"self_intoduction": [{"question": "직무와 관련된 성과 경험을 작성해 주세요.", "answer": {"s": "맡은 일을 수행한 상황이라고만 서술되어 있습니다.", "t": "구체적 성과와 근거를 제시해야 했습니다.", "a": "좋은 평가를 받았다고 언급했으나 구체적 근거는 없습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}, {"question": "실패했거나 어려움을 극복한 경험을 작성해 주세요.", "answer": {"s": "실패를 겪었던 상황이라고만 서술되어 있습니다.", "t": "실패를 극복하기 위한 구체적 노력을 제시해야 했습니다.", "a": "노력으로 극복했다고 언급했으나 구체적 행동은 없습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}, {"question": "직무 수행에 필요한 본인의 역량을 작성해 주세요.", "answer": {"s": "기본적인 개발 지식을 갖췄다고 밝힌 상황입니다.", "t": "보유 역량을 구체적 사례로 뒷받침해야 했습니다.", "a": "지식을 갖췄다고 언급했으나 구체적 근거는 없습니다.", "r": "구체적 결과는 원문에서 확인되지 않습니다."}}], "original_quality": "원문은 일반적이고 상투적인 표현이 많고 구체적 근거가 부족해, 지원자의 실제 경험이나 기여도를 확인하기 어려운 수준입니다. STAR 변환 후에는 답변 구조가 더 명확해 보일 수 있으므로, 원문에 없는 근거를 채워 넣거나 원문 이상의 평가로 이어지지 않도록 주의해야 합니다."}
====================================================================================================
label: 0
role: AI 엔지니어 / 머신러닝 엔지니어
schema_valid: True
semantic_sim: 0.8778043985366821

[PRED]
{
  "self_intoduction": [
    {
      "question": "팀 프로젝트에서 어려움을 해결한 경험을 작성해 주세요.",
      "answer": {
        "s": "팀 프로젝트를 함께 수행한 상황이라고만 서술되어 있습니다.",
        "t": "본인의 구체적 기여를 제시해야 했습니다.",
        "a": "팀원들과 소통를 잘해 프로젝트를 마쳤다고 서술했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "지원 동기를 작성해 주세요.",
      "answer": {
        "s": "AI 엔지니어 / 머신러닝 엔지니어 직무에 지원한 상황이라고 서술되어 있습니다.",
        "t": "지원 동기를 경험과 연결해 제시해야 했습니다.",
        "a": "직무 전망을 언급해 지원 동기를 제시했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "갈등이 발생한 상황과 이를 해결하기 위해 한 노력을 적어주세요.",
      "answer": {
        "s": "팀원과 갈등이 있었던 상황이라고만 서술되어 있습니다.",
        "t": "갈등을 해소하고 협업을 이어가야 했습니다.",
        "a": "서로 대화해 풀었다고 언급했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    },
    {
      "question": "입사 후 목표나 포부를 작성해 주세요.",
      "answer": {
        "s": "회사에 기여하고자 하는 의도를 밝힌 상황입니다.",
        "t": "입사 후 목표와 포부를 구체적으로 제시해야 했습니다.",
        "a": "회사 발전에 이바지하겠다는 의지를 서술했습니다.",
        "r": "구체적 결과는 원문에서 확인되지 않습니다."
      }
    }
  ],